spring:
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

global-payment:
  trace:
    header-name: X-Trace-Id
