-- BUG-VERIFY-001-001 06B sharding registry migration
-- Generated by tools/sql/transaction-ddl/build-transaction-sharding-registry-06b.mjs on 2026-07-25.
-- Do not execute from automation. Review and run manually in the intended database session only.
-- 本文件不得由 Codex 自动执行；执行前必须先运行 evidence SQL 并人工确认 Guard 结果。
-- 安全边界：不包含按 transaction 表前缀的宽范围删除；历史季度和范围外登记不会被删除。
-- 当前日期 2026-07-25 Asia/Shanghai 仍处于 2026Q3，目标登记为 2026Q3(202603) 与 2026Q4(202604)。
SET NAMES utf8mb4;

-- Phase 1: additive physical table provisioning. These statements are idempotent and target only the 46 generated table names.
CREATE TABLE IF NOT EXISTS `transaction_order_202603` LIKE `transaction_order`;
ALTER TABLE `transaction_order_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_order_202604` LIKE `transaction_order`;
ALTER TABLE `transaction_order_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_operation_202603` LIKE `transaction_operation`;
ALTER TABLE `transaction_operation_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_operation_202604` LIKE `transaction_operation`;
ALTER TABLE `transaction_operation_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_merchant_snapshot_202603` LIKE `transaction_merchant_snapshot`;
ALTER TABLE `transaction_merchant_snapshot_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_merchant_snapshot_202604` LIKE `transaction_merchant_snapshot`;
ALTER TABLE `transaction_merchant_snapshot_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_payment_method_info_202603` LIKE `transaction_payment_method_info`;
ALTER TABLE `transaction_payment_method_info_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_payment_method_info_202604` LIKE `transaction_payment_method_info`;
ALTER TABLE `transaction_payment_method_info_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_payer_info_202603` LIKE `transaction_payer_info`;
ALTER TABLE `transaction_payer_info_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_payer_info_202604` LIKE `transaction_payer_info`;
ALTER TABLE `transaction_payer_info_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_billing_info_202603` LIKE `transaction_billing_info`;
ALTER TABLE `transaction_billing_info_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_billing_info_202604` LIKE `transaction_billing_info`;
ALTER TABLE `transaction_billing_info_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_additional_info_202603` LIKE `transaction_additional_info`;
ALTER TABLE `transaction_additional_info_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_additional_info_202604` LIKE `transaction_additional_info`;
ALTER TABLE `transaction_additional_info_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_authentication_info_202603` LIKE `transaction_authentication_info`;
ALTER TABLE `transaction_authentication_info_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_authentication_info_202604` LIKE `transaction_authentication_info`;
ALTER TABLE `transaction_authentication_info_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_product_item_202603` LIKE `transaction_product_item`;
ALTER TABLE `transaction_product_item_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_product_item_202604` LIKE `transaction_product_item`;
ALTER TABLE `transaction_product_item_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_channel_request_202603` LIKE `transaction_channel_request`;
ALTER TABLE `transaction_channel_request_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_channel_request_202604` LIKE `transaction_channel_request`;
ALTER TABLE `transaction_channel_request_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_channel_interaction_log_202603` LIKE `transaction_channel_interaction_log`;
ALTER TABLE `transaction_channel_interaction_log_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_channel_interaction_log_202604` LIKE `transaction_channel_interaction_log`;
ALTER TABLE `transaction_channel_interaction_log_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_channel_callback_log_202603` LIKE `transaction_channel_callback_log`;
ALTER TABLE `transaction_channel_callback_log_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_channel_callback_log_202604` LIKE `transaction_channel_callback_log`;
ALTER TABLE `transaction_channel_callback_log_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_channel_callback_202603` LIKE `transaction_channel_callback`;
ALTER TABLE `transaction_channel_callback_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_channel_callback_202604` LIKE `transaction_channel_callback`;
ALTER TABLE `transaction_channel_callback_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_flow_event_202603` LIKE `transaction_flow_event`;
ALTER TABLE `transaction_flow_event_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_flow_event_202604` LIKE `transaction_flow_event`;
ALTER TABLE `transaction_flow_event_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_status_history_202603` LIKE `transaction_status_history`;
ALTER TABLE `transaction_status_history_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_status_history_202604` LIKE `transaction_status_history`;
ALTER TABLE `transaction_status_history_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_amount_change_log_202603` LIKE `transaction_amount_change_log`;
ALTER TABLE `transaction_amount_change_log_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_amount_change_log_202604` LIKE `transaction_amount_change_log`;
ALTER TABLE `transaction_amount_change_log_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_finance_state_202603` LIKE `transaction_finance_state`;
ALTER TABLE `transaction_finance_state_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_finance_state_202604` LIKE `transaction_finance_state`;
ALTER TABLE `transaction_finance_state_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_currency_conversion_202603` LIKE `transaction_currency_conversion`;
ALTER TABLE `transaction_currency_conversion_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_currency_conversion_202604` LIKE `transaction_currency_conversion`;
ALTER TABLE `transaction_currency_conversion_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_merchant_notification_202603` LIKE `transaction_merchant_notification`;
ALTER TABLE `transaction_merchant_notification_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_merchant_notification_202604` LIKE `transaction_merchant_notification`;
ALTER TABLE `transaction_merchant_notification_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_merchant_notification_log_202603` LIKE `transaction_merchant_notification_log`;
ALTER TABLE `transaction_merchant_notification_log_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_merchant_notification_log_202604` LIKE `transaction_merchant_notification_log`;
ALTER TABLE `transaction_merchant_notification_log_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_merchant_api_interaction_log_202603` LIKE `transaction_merchant_api_interaction_log`;
ALTER TABLE `transaction_merchant_api_interaction_log_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_merchant_api_interaction_log_202604` LIKE `transaction_merchant_api_interaction_log`;
ALTER TABLE `transaction_merchant_api_interaction_log_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_event_outbox_202603` LIKE `transaction_event_outbox`;
ALTER TABLE `transaction_event_outbox_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_event_outbox_202604` LIKE `transaction_event_outbox`;
ALTER TABLE `transaction_event_outbox_202604` AUTO_INCREMENT = 202604000000000001;
CREATE TABLE IF NOT EXISTS `transaction_abnormal_event_202603` LIKE `transaction_abnormal_event`;
ALTER TABLE `transaction_abnormal_event_202603` AUTO_INCREMENT = 202603000000000001;
CREATE TABLE IF NOT EXISTS `transaction_abnormal_event_202604` LIKE `transaction_abnormal_event`;
ALTER TABLE `transaction_abnormal_event_202604` AUTO_INCREMENT = 202604000000000001;

-- Phase 2: create the precise backup table before the DML transaction because regular MySQL DDL causes implicit commit.
CREATE TABLE IF NOT EXISTS `sys_sharding_physical_table_backup_bug001_06b_20260725` LIKE `sys_sharding_physical_table`;

-- Phase 3: precise registry migration. Run in one session so temporary tables are available for checks.
START TRANSACTION;

CREATE TEMPORARY TABLE `bug001_06b_target_registry` (
  `logical_table` VARCHAR(128) NOT NULL,
  `template_table` VARCHAR(128) NOT NULL,
  `physical_table` VARCHAR(160) NOT NULL,
  `sharding_column` VARCHAR(128) NOT NULL,
  `strategy` VARCHAR(32) NOT NULL,
  `year` INT NOT NULL,
  `quarter` INT NOT NULL,
  `quarter_suffix` VARCHAR(8) NOT NULL,
  `data_source` VARCHAR(64) NOT NULL,
  `table_status` VARCHAR(32) NOT NULL,
  `auto_created` TINYINT NOT NULL,
  `auto_increment_start` BIGINT NOT NULL,
  `auto_increment_current` BIGINT NOT NULL,
  `auto_increment_max` BIGINT NOT NULL,
  `schema_check_status` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`physical_table`)
) ENGINE=MEMORY;

INSERT INTO `bug001_06b_target_registry` (`logical_table`, `template_table`, `physical_table`, `sharding_column`, `strategy`, `year`, `quarter`, `quarter_suffix`, `data_source`, `table_status`, `auto_created`, `auto_increment_start`, `auto_increment_current`, `auto_increment_max`, `schema_check_status`) VALUES
  ('transaction_order', 'transaction_order', 'transaction_order_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_order', 'transaction_order', 'transaction_order_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_operation', 'transaction_operation', 'transaction_operation_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_operation', 'transaction_operation', 'transaction_operation_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_merchant_snapshot', 'transaction_merchant_snapshot', 'transaction_merchant_snapshot_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_merchant_snapshot', 'transaction_merchant_snapshot', 'transaction_merchant_snapshot_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_payment_method_info', 'transaction_payment_method_info', 'transaction_payment_method_info_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_payment_method_info', 'transaction_payment_method_info', 'transaction_payment_method_info_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_payer_info', 'transaction_payer_info', 'transaction_payer_info_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_payer_info', 'transaction_payer_info', 'transaction_payer_info_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_billing_info', 'transaction_billing_info', 'transaction_billing_info_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_billing_info', 'transaction_billing_info', 'transaction_billing_info_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_additional_info', 'transaction_additional_info', 'transaction_additional_info_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_additional_info', 'transaction_additional_info', 'transaction_additional_info_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_authentication_info', 'transaction_authentication_info', 'transaction_authentication_info_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_authentication_info', 'transaction_authentication_info', 'transaction_authentication_info_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_product_item', 'transaction_product_item', 'transaction_product_item_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_product_item', 'transaction_product_item', 'transaction_product_item_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_channel_request', 'transaction_channel_request', 'transaction_channel_request_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_channel_request', 'transaction_channel_request', 'transaction_channel_request_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_channel_interaction_log', 'transaction_channel_interaction_log', 'transaction_channel_interaction_log_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_channel_interaction_log', 'transaction_channel_interaction_log', 'transaction_channel_interaction_log_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_channel_callback_log', 'transaction_channel_callback_log', 'transaction_channel_callback_log_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_channel_callback_log', 'transaction_channel_callback_log', 'transaction_channel_callback_log_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_channel_callback', 'transaction_channel_callback', 'transaction_channel_callback_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_channel_callback', 'transaction_channel_callback', 'transaction_channel_callback_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_flow_event', 'transaction_flow_event', 'transaction_flow_event_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_flow_event', 'transaction_flow_event', 'transaction_flow_event_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_status_history', 'transaction_status_history', 'transaction_status_history_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_status_history', 'transaction_status_history', 'transaction_status_history_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_amount_change_log', 'transaction_amount_change_log', 'transaction_amount_change_log_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_amount_change_log', 'transaction_amount_change_log', 'transaction_amount_change_log_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_finance_state', 'transaction_finance_state', 'transaction_finance_state_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_finance_state', 'transaction_finance_state', 'transaction_finance_state_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_currency_conversion', 'transaction_currency_conversion', 'transaction_currency_conversion_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_currency_conversion', 'transaction_currency_conversion', 'transaction_currency_conversion_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_merchant_notification', 'transaction_merchant_notification', 'transaction_merchant_notification_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_merchant_notification', 'transaction_merchant_notification', 'transaction_merchant_notification_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_merchant_notification_log', 'transaction_merchant_notification_log', 'transaction_merchant_notification_log_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_merchant_notification_log', 'transaction_merchant_notification_log', 'transaction_merchant_notification_log_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_merchant_api_interaction_log', 'transaction_merchant_api_interaction_log', 'transaction_merchant_api_interaction_log_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_merchant_api_interaction_log', 'transaction_merchant_api_interaction_log', 'transaction_merchant_api_interaction_log_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_event_outbox', 'transaction_event_outbox', 'transaction_event_outbox_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_event_outbox', 'transaction_event_outbox', 'transaction_event_outbox_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_abnormal_event', 'transaction_abnormal_event', 'transaction_abnormal_event_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_abnormal_event', 'transaction_abnormal_event', 'transaction_abnormal_event_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED');

CREATE TEMPORARY TABLE `bug001_06b_guard` (
  `guard_id` INT NOT NULL PRIMARY KEY
) ENGINE=MEMORY;

INSERT INTO `bug001_06b_guard` (`guard_id`) VALUES (1);

-- Guard 1: the generated target list must stay exactly 46 rows.
INSERT INTO `bug001_06b_guard` (`guard_id`)
SELECT 1 WHERE (SELECT COUNT(*) FROM `bug001_06b_target_registry`) <> 46;

-- Guard 2: every target physical table must be distinct.
INSERT INTO `bug001_06b_guard` (`guard_id`)
SELECT 1 WHERE (SELECT COUNT(DISTINCT `physical_table`) FROM `bug001_06b_target_registry`) <> 46;

-- Guard 3: existing registry rows must not contain duplicate target physical_table values.
INSERT INTO `bug001_06b_guard` (`guard_id`)
SELECT 1
FROM (
  SELECT s.`physical_table`
  FROM `sys_sharding_physical_table` s
  JOIN `bug001_06b_target_registry` t ON s.`physical_table` = t.`physical_table`
  GROUP BY s.`physical_table`
  HAVING COUNT(*) > 1
) duplicated_target_physical_table
LIMIT 1;

-- Backup only target registry rows. Historical quarters and out-of-range transaction_* rows are not selected.
INSERT INTO `sys_sharding_physical_table_backup_bug001_06b_20260725` (`id`, `logical_table`, `template_table`, `physical_table`, `sharding_column`, `strategy`, `year`, `quarter`, `quarter_suffix`, `data_source`, `table_status`, `auto_created`, `auto_increment_start`, `auto_increment_current`, `auto_increment_max`, `schema_check_status`, `last_check_time`, `created_time`, `error_message`, `create_time`, `update_time`)
SELECT s.`id`, s.`logical_table`, s.`template_table`, s.`physical_table`, s.`sharding_column`, s.`strategy`, s.`year`, s.`quarter`, s.`quarter_suffix`, s.`data_source`, s.`table_status`, s.`auto_created`, s.`auto_increment_start`, s.`auto_increment_current`, s.`auto_increment_max`, s.`schema_check_status`, s.`last_check_time`, s.`created_time`, s.`error_message`, s.`create_time`, s.`update_time`
FROM `sys_sharding_physical_table` s
JOIN `bug001_06b_target_registry` t ON s.`physical_table` = t.`physical_table`
WHERE NOT EXISTS (
  SELECT 1 FROM `sys_sharding_physical_table_backup_bug001_06b_20260725` b
  WHERE b.`physical_table` = s.`physical_table`
);

-- Update existing target registrations by exact physical_table match.
UPDATE `sys_sharding_physical_table` s
JOIN `bug001_06b_target_registry` t ON s.`physical_table` = t.`physical_table`
SET
  s.`logical_table` = t.`logical_table`,
  s.`template_table` = t.`template_table`,
  s.`sharding_column` = t.`sharding_column`,
  s.`strategy` = t.`strategy`,
  s.`year` = t.`year`,
  s.`quarter` = t.`quarter`,
  s.`quarter_suffix` = t.`quarter_suffix`,
  s.`data_source` = t.`data_source`,
  s.`table_status` = 'EXISTS',
  s.`auto_increment_start` = t.`auto_increment_start`,
  s.`auto_increment_current` = GREATEST(COALESCE(s.`auto_increment_current`, t.`auto_increment_current`), t.`auto_increment_start`),
  s.`auto_increment_max` = t.`auto_increment_max`,
  s.`schema_check_status` = t.`schema_check_status`,
  s.`last_check_time` = NOW(),
  s.`created_time` = COALESCE(s.`created_time`, NOW()),
  s.`error_message` = NULL,
  s.`create_time` = COALESCE(s.`create_time`, NOW()),
  s.`update_time` = NOW()
WHERE s.`physical_table` = t.`physical_table`;

-- Insert missing target registrations by exact physical_table anti-join.
INSERT INTO `sys_sharding_physical_table` (`logical_table`, `template_table`, `physical_table`, `sharding_column`, `strategy`, `year`, `quarter`, `quarter_suffix`, `data_source`, `table_status`, `auto_created`, `auto_increment_start`, `auto_increment_current`, `auto_increment_max`, `schema_check_status`, `last_check_time`, `created_time`, `error_message`, `create_time`, `update_time`)
SELECT
  t.`logical_table`,
  t.`template_table`,
  t.`physical_table`,
  t.`sharding_column`,
  t.`strategy`,
  t.`year`,
  t.`quarter`,
  t.`quarter_suffix`,
  t.`data_source`,
  t.`table_status`,
  t.`auto_created`,
  t.`auto_increment_start`,
  t.`auto_increment_current`,
  t.`auto_increment_max`,
  t.`schema_check_status`,
  NOW(),
  NOW(),
  NULL,
  NOW(),
  NOW()
FROM `bug001_06b_target_registry` t
WHERE NOT EXISTS (
  SELECT 1
  FROM `sys_sharding_physical_table` s
  WHERE s.`physical_table` = t.`physical_table`
);

-- Post-check 1: should return 46 registered target rows.
SELECT COUNT(*) AS target_registered_rows
FROM `sys_sharding_physical_table` s
JOIN `bug001_06b_target_registry` t ON s.`physical_table` = t.`physical_table`;

-- Post-check 2: should return zero missing target rows.
SELECT t.`physical_table` AS missing_physical_table
FROM `bug001_06b_target_registry` t
LEFT JOIN `sys_sharding_physical_table` s ON s.`physical_table` = t.`physical_table`
WHERE s.`physical_table` IS NULL;

-- Post-check 3: should return zero duplicate target registry rows.
SELECT s.`physical_table`, COUNT(*) AS duplicate_count
FROM `sys_sharding_physical_table` s
JOIN `bug001_06b_target_registry` t ON s.`physical_table` = t.`physical_table`
GROUP BY s.`physical_table`
HAVING COUNT(*) > 1;

-- Expected target count: 46.

COMMIT;
