-- BUG-VERIFY-001-001 06B sharding registry rollback
-- Generated by tools/sql/transaction-ddl/build-transaction-sharding-registry-06b.mjs on 2026-07-25.
-- Do not execute from automation. Review and run manually in the intended database session only.
-- 本文件不得由 Codex 自动执行；只回滚 sys_sharding_physical_table 的 06B 目标登记。
-- 物理表 DROP 不纳入自动回滚，避免误删业务数据；如需清理，先用 evidence SQL 确认空表后人工处理。
SET NAMES utf8mb4;

START TRANSACTION;

CREATE TEMPORARY TABLE `bug001_06b_target_registry` (
  `logical_table` VARCHAR(128) NOT NULL,
  `template_table` VARCHAR(128) NOT NULL,
  `physical_table` VARCHAR(160) NOT NULL,
  `sharding_column` VARCHAR(128) NOT NULL,
  `strategy` VARCHAR(32) NOT NULL,
  `year` INT NOT NULL,
  `quarter` INT NOT NULL,
  `quarter_suffix` VARCHAR(8) NOT NULL,
  `data_source` VARCHAR(64) NOT NULL,
  `table_status` VARCHAR(32) NOT NULL,
  `auto_created` TINYINT NOT NULL,
  `auto_increment_start` BIGINT NOT NULL,
  `auto_increment_current` BIGINT NOT NULL,
  `auto_increment_max` BIGINT NOT NULL,
  `schema_check_status` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`physical_table`)
) ENGINE=MEMORY;

INSERT INTO `bug001_06b_target_registry` (`logical_table`, `template_table`, `physical_table`, `sharding_column`, `strategy`, `year`, `quarter`, `quarter_suffix`, `data_source`, `table_status`, `auto_created`, `auto_increment_start`, `auto_increment_current`, `auto_increment_max`, `schema_check_status`) VALUES
  ('transaction_order', 'transaction_order', 'transaction_order_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_order', 'transaction_order', 'transaction_order_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_operation', 'transaction_operation', 'transaction_operation_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_operation', 'transaction_operation', 'transaction_operation_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_merchant_snapshot', 'transaction_merchant_snapshot', 'transaction_merchant_snapshot_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_merchant_snapshot', 'transaction_merchant_snapshot', 'transaction_merchant_snapshot_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_payment_method_info', 'transaction_payment_method_info', 'transaction_payment_method_info_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_payment_method_info', 'transaction_payment_method_info', 'transaction_payment_method_info_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_payer_info', 'transaction_payer_info', 'transaction_payer_info_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_payer_info', 'transaction_payer_info', 'transaction_payer_info_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_billing_info', 'transaction_billing_info', 'transaction_billing_info_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_billing_info', 'transaction_billing_info', 'transaction_billing_info_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_additional_info', 'transaction_additional_info', 'transaction_additional_info_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_additional_info', 'transaction_additional_info', 'transaction_additional_info_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_authentication_info', 'transaction_authentication_info', 'transaction_authentication_info_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_authentication_info', 'transaction_authentication_info', 'transaction_authentication_info_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_product_item', 'transaction_product_item', 'transaction_product_item_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_product_item', 'transaction_product_item', 'transaction_product_item_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_channel_request', 'transaction_channel_request', 'transaction_channel_request_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_channel_request', 'transaction_channel_request', 'transaction_channel_request_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_channel_interaction_log', 'transaction_channel_interaction_log', 'transaction_channel_interaction_log_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_channel_interaction_log', 'transaction_channel_interaction_log', 'transaction_channel_interaction_log_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_channel_callback_log', 'transaction_channel_callback_log', 'transaction_channel_callback_log_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_channel_callback_log', 'transaction_channel_callback_log', 'transaction_channel_callback_log_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_channel_callback', 'transaction_channel_callback', 'transaction_channel_callback_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_channel_callback', 'transaction_channel_callback', 'transaction_channel_callback_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_flow_event', 'transaction_flow_event', 'transaction_flow_event_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_flow_event', 'transaction_flow_event', 'transaction_flow_event_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_status_history', 'transaction_status_history', 'transaction_status_history_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_status_history', 'transaction_status_history', 'transaction_status_history_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_amount_change_log', 'transaction_amount_change_log', 'transaction_amount_change_log_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_amount_change_log', 'transaction_amount_change_log', 'transaction_amount_change_log_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_finance_state', 'transaction_finance_state', 'transaction_finance_state_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_finance_state', 'transaction_finance_state', 'transaction_finance_state_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_currency_conversion', 'transaction_currency_conversion', 'transaction_currency_conversion_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_currency_conversion', 'transaction_currency_conversion', 'transaction_currency_conversion_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_merchant_notification', 'transaction_merchant_notification', 'transaction_merchant_notification_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_merchant_notification', 'transaction_merchant_notification', 'transaction_merchant_notification_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_merchant_notification_log', 'transaction_merchant_notification_log', 'transaction_merchant_notification_log_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_merchant_notification_log', 'transaction_merchant_notification_log', 'transaction_merchant_notification_log_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_merchant_api_interaction_log', 'transaction_merchant_api_interaction_log', 'transaction_merchant_api_interaction_log_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_merchant_api_interaction_log', 'transaction_merchant_api_interaction_log', 'transaction_merchant_api_interaction_log_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_event_outbox', 'transaction_event_outbox', 'transaction_event_outbox_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_event_outbox', 'transaction_event_outbox', 'transaction_event_outbox_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED'),
  ('transaction_abnormal_event', 'transaction_abnormal_event', 'transaction_abnormal_event_202603', 'transaction_date_time', 'quarter', 2026, 3, '202603', 'master', 'CREATED', 1, 202603000000000001, 202603000000000001, 202603999999999999, 'MATCHED'),
  ('transaction_abnormal_event', 'transaction_abnormal_event', 'transaction_abnormal_event_202604', 'transaction_date_time', 'quarter', 2026, 4, '202604', 'master', 'CREATED', 1, 202604000000000001, 202604000000000001, 202604999999999999, 'MATCHED');

CREATE TEMPORARY TABLE `bug001_06b_guard` (
  `guard_id` INT NOT NULL PRIMARY KEY
) ENGINE=MEMORY;

INSERT INTO `bug001_06b_guard` (`guard_id`) VALUES (1);

-- Guard 1: the generated target list must stay exactly 46 rows.
INSERT INTO `bug001_06b_guard` (`guard_id`)
SELECT 1 WHERE (SELECT COUNT(*) FROM `bug001_06b_target_registry`) <> 46;

-- Guard 2: every target physical table must be distinct.
INSERT INTO `bug001_06b_guard` (`guard_id`)
SELECT 1 WHERE (SELECT COUNT(DISTINCT `physical_table`) FROM `bug001_06b_target_registry`) <> 46;

-- Guard 3: existing registry rows must not contain duplicate target physical_table values.
INSERT INTO `bug001_06b_guard` (`guard_id`)
SELECT 1
FROM (
  SELECT s.`physical_table`
  FROM `sys_sharding_physical_table` s
  JOIN `bug001_06b_target_registry` t ON s.`physical_table` = t.`physical_table`
  GROUP BY s.`physical_table`
  HAVING COUNT(*) > 1
) duplicated_target_physical_table
LIMIT 1;

-- Delete rows inserted by 06B when no pre-migration backup row exists.
DELETE s
FROM `sys_sharding_physical_table` s
JOIN `bug001_06b_target_registry` t ON s.`physical_table` = t.`physical_table`
LEFT JOIN `sys_sharding_physical_table_backup_bug001_06b_20260725` b ON b.`physical_table` = s.`physical_table`
WHERE b.`physical_table` IS NULL;

-- Restore rows that existed before 06B by exact physical_table match.
UPDATE `sys_sharding_physical_table` s
JOIN `sys_sharding_physical_table_backup_bug001_06b_20260725` b ON b.`physical_table` = s.`physical_table`
JOIN `bug001_06b_target_registry` t ON t.`physical_table` = s.`physical_table`
SET
  s.`logical_table` = b.`logical_table`,
  s.`template_table` = b.`template_table`,
  s.`physical_table` = b.`physical_table`,
  s.`sharding_column` = b.`sharding_column`,
  s.`strategy` = b.`strategy`,
  s.`year` = b.`year`,
  s.`quarter` = b.`quarter`,
  s.`quarter_suffix` = b.`quarter_suffix`,
  s.`data_source` = b.`data_source`,
  s.`table_status` = b.`table_status`,
  s.`auto_created` = b.`auto_created`,
  s.`auto_increment_start` = b.`auto_increment_start`,
  s.`auto_increment_current` = b.`auto_increment_current`,
  s.`auto_increment_max` = b.`auto_increment_max`,
  s.`schema_check_status` = b.`schema_check_status`,
  s.`last_check_time` = b.`last_check_time`,
  s.`created_time` = b.`created_time`,
  s.`error_message` = b.`error_message`,
  s.`create_time` = b.`create_time`,
  s.`update_time` = b.`update_time`
WHERE s.`physical_table` = t.`physical_table`;

-- Reinsert backup rows if a target row was removed after migration.
INSERT INTO `sys_sharding_physical_table` (`id`, `logical_table`, `template_table`, `physical_table`, `sharding_column`, `strategy`, `year`, `quarter`, `quarter_suffix`, `data_source`, `table_status`, `auto_created`, `auto_increment_start`, `auto_increment_current`, `auto_increment_max`, `schema_check_status`, `last_check_time`, `created_time`, `error_message`, `create_time`, `update_time`)
SELECT b.`id`, b.`logical_table`, b.`template_table`, b.`physical_table`, b.`sharding_column`, b.`strategy`, b.`year`, b.`quarter`, b.`quarter_suffix`, b.`data_source`, b.`table_status`, b.`auto_created`, b.`auto_increment_start`, b.`auto_increment_current`, b.`auto_increment_max`, b.`schema_check_status`, b.`last_check_time`, b.`created_time`, b.`error_message`, b.`create_time`, b.`update_time`
FROM `sys_sharding_physical_table_backup_bug001_06b_20260725` b
JOIN `bug001_06b_target_registry` t ON b.`physical_table` = t.`physical_table`
WHERE NOT EXISTS (
  SELECT 1
  FROM `sys_sharding_physical_table` s
  WHERE s.`physical_table` = b.`physical_table`
);

-- Post-check 1: should return 46 registered target rows.
SELECT COUNT(*) AS target_registered_rows
FROM `sys_sharding_physical_table` s
JOIN `bug001_06b_target_registry` t ON s.`physical_table` = t.`physical_table`;

-- Post-check 2: should return zero missing target rows.
SELECT t.`physical_table` AS missing_physical_table
FROM `bug001_06b_target_registry` t
LEFT JOIN `sys_sharding_physical_table` s ON s.`physical_table` = t.`physical_table`
WHERE s.`physical_table` IS NULL;

-- Post-check 3: should return zero duplicate target registry rows.
SELECT s.`physical_table`, COUNT(*) AS duplicate_count
FROM `sys_sharding_physical_table` s
JOIN `bug001_06b_target_registry` t ON s.`physical_table` = t.`physical_table`
GROUP BY s.`physical_table`
HAVING COUNT(*) > 1;

-- Expected target count: 46.

COMMIT;
