-- BUG-VERIFY-001-001 06B sharding registry read-only evidence SQL
-- Generated by tools/sql/transaction-ddl/build-transaction-sharding-registry-06b.mjs on 2026-07-25.
-- Do not execute from automation. Review and run manually in the intended database session only.
-- 本文件只包含 SELECT，不包含 DDL/DML；用于执行前后留存 SQL 证据。
SET NAMES utf8mb4;

SELECT DATABASE() AS current_schema, NOW() AS evidence_time;

-- Evidence 1: sys_sharding_physical_table columns and index shape.
SELECT `COLUMN_NAME`, `COLUMN_TYPE`, `IS_NULLABLE`, `COLUMN_DEFAULT`, `COLUMN_KEY`
FROM `information_schema`.`COLUMNS`
WHERE `TABLE_SCHEMA` = DATABASE()
  AND `TABLE_NAME` = 'sys_sharding_physical_table'
ORDER BY `ORDINAL_POSITION`;

SELECT `INDEX_NAME`, `NON_UNIQUE`, GROUP_CONCAT(`COLUMN_NAME` ORDER BY `SEQ_IN_INDEX`) AS indexed_columns
FROM `information_schema`.`STATISTICS`
WHERE `TABLE_SCHEMA` = DATABASE()
  AND `TABLE_NAME` = 'sys_sharding_physical_table'
GROUP BY `INDEX_NAME`, `NON_UNIQUE`
ORDER BY `INDEX_NAME`;

-- Evidence 2: generated target list must be 46 rows with no duplicate physical_table.
SELECT COUNT(*) AS target_count, COUNT(DISTINCT target.`physical_table`) AS distinct_physical_table_count
FROM (
SELECT 'transaction_order' AS logical_table, 'transaction_order' AS template_table, 'transaction_order_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_order' AS logical_table, 'transaction_order' AS template_table, 'transaction_order_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_operation' AS logical_table, 'transaction_operation' AS template_table, 'transaction_operation_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_operation' AS logical_table, 'transaction_operation' AS template_table, 'transaction_operation_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_snapshot' AS logical_table, 'transaction_merchant_snapshot' AS template_table, 'transaction_merchant_snapshot_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_snapshot' AS logical_table, 'transaction_merchant_snapshot' AS template_table, 'transaction_merchant_snapshot_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_payment_method_info' AS logical_table, 'transaction_payment_method_info' AS template_table, 'transaction_payment_method_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_payment_method_info' AS logical_table, 'transaction_payment_method_info' AS template_table, 'transaction_payment_method_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_payer_info' AS logical_table, 'transaction_payer_info' AS template_table, 'transaction_payer_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_payer_info' AS logical_table, 'transaction_payer_info' AS template_table, 'transaction_payer_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_billing_info' AS logical_table, 'transaction_billing_info' AS template_table, 'transaction_billing_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_billing_info' AS logical_table, 'transaction_billing_info' AS template_table, 'transaction_billing_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_additional_info' AS logical_table, 'transaction_additional_info' AS template_table, 'transaction_additional_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_additional_info' AS logical_table, 'transaction_additional_info' AS template_table, 'transaction_additional_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_authentication_info' AS logical_table, 'transaction_authentication_info' AS template_table, 'transaction_authentication_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_authentication_info' AS logical_table, 'transaction_authentication_info' AS template_table, 'transaction_authentication_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_product_item' AS logical_table, 'transaction_product_item' AS template_table, 'transaction_product_item_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_product_item' AS logical_table, 'transaction_product_item' AS template_table, 'transaction_product_item_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_request' AS logical_table, 'transaction_channel_request' AS template_table, 'transaction_channel_request_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_request' AS logical_table, 'transaction_channel_request' AS template_table, 'transaction_channel_request_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_interaction_log' AS logical_table, 'transaction_channel_interaction_log' AS template_table, 'transaction_channel_interaction_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_interaction_log' AS logical_table, 'transaction_channel_interaction_log' AS template_table, 'transaction_channel_interaction_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback_log' AS logical_table, 'transaction_channel_callback_log' AS template_table, 'transaction_channel_callback_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback_log' AS logical_table, 'transaction_channel_callback_log' AS template_table, 'transaction_channel_callback_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback' AS logical_table, 'transaction_channel_callback' AS template_table, 'transaction_channel_callback_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback' AS logical_table, 'transaction_channel_callback' AS template_table, 'transaction_channel_callback_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_flow_event' AS logical_table, 'transaction_flow_event' AS template_table, 'transaction_flow_event_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_flow_event' AS logical_table, 'transaction_flow_event' AS template_table, 'transaction_flow_event_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_status_history' AS logical_table, 'transaction_status_history' AS template_table, 'transaction_status_history_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_status_history' AS logical_table, 'transaction_status_history' AS template_table, 'transaction_status_history_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_amount_change_log' AS logical_table, 'transaction_amount_change_log' AS template_table, 'transaction_amount_change_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_amount_change_log' AS logical_table, 'transaction_amount_change_log' AS template_table, 'transaction_amount_change_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_finance_state' AS logical_table, 'transaction_finance_state' AS template_table, 'transaction_finance_state_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_finance_state' AS logical_table, 'transaction_finance_state' AS template_table, 'transaction_finance_state_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_currency_conversion' AS logical_table, 'transaction_currency_conversion' AS template_table, 'transaction_currency_conversion_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_currency_conversion' AS logical_table, 'transaction_currency_conversion' AS template_table, 'transaction_currency_conversion_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification' AS logical_table, 'transaction_merchant_notification' AS template_table, 'transaction_merchant_notification_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification' AS logical_table, 'transaction_merchant_notification' AS template_table, 'transaction_merchant_notification_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification_log' AS logical_table, 'transaction_merchant_notification_log' AS template_table, 'transaction_merchant_notification_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification_log' AS logical_table, 'transaction_merchant_notification_log' AS template_table, 'transaction_merchant_notification_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_api_interaction_log' AS logical_table, 'transaction_merchant_api_interaction_log' AS template_table, 'transaction_merchant_api_interaction_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_api_interaction_log' AS logical_table, 'transaction_merchant_api_interaction_log' AS template_table, 'transaction_merchant_api_interaction_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_event_outbox' AS logical_table, 'transaction_event_outbox' AS template_table, 'transaction_event_outbox_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_event_outbox' AS logical_table, 'transaction_event_outbox' AS template_table, 'transaction_event_outbox_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_abnormal_event' AS logical_table, 'transaction_abnormal_event' AS template_table, 'transaction_abnormal_event_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_abnormal_event' AS logical_table, 'transaction_abnormal_event' AS template_table, 'transaction_abnormal_event_202604' AS physical_table, '202604' AS quarter_suffix
) target;

-- Evidence 3: existing duplicate rows for target physical tables must be zero before migration.
SELECT s.`physical_table`, COUNT(*) AS duplicate_count
FROM `sys_sharding_physical_table` s
JOIN (
SELECT 'transaction_order' AS logical_table, 'transaction_order' AS template_table, 'transaction_order_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_order' AS logical_table, 'transaction_order' AS template_table, 'transaction_order_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_operation' AS logical_table, 'transaction_operation' AS template_table, 'transaction_operation_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_operation' AS logical_table, 'transaction_operation' AS template_table, 'transaction_operation_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_snapshot' AS logical_table, 'transaction_merchant_snapshot' AS template_table, 'transaction_merchant_snapshot_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_snapshot' AS logical_table, 'transaction_merchant_snapshot' AS template_table, 'transaction_merchant_snapshot_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_payment_method_info' AS logical_table, 'transaction_payment_method_info' AS template_table, 'transaction_payment_method_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_payment_method_info' AS logical_table, 'transaction_payment_method_info' AS template_table, 'transaction_payment_method_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_payer_info' AS logical_table, 'transaction_payer_info' AS template_table, 'transaction_payer_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_payer_info' AS logical_table, 'transaction_payer_info' AS template_table, 'transaction_payer_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_billing_info' AS logical_table, 'transaction_billing_info' AS template_table, 'transaction_billing_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_billing_info' AS logical_table, 'transaction_billing_info' AS template_table, 'transaction_billing_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_additional_info' AS logical_table, 'transaction_additional_info' AS template_table, 'transaction_additional_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_additional_info' AS logical_table, 'transaction_additional_info' AS template_table, 'transaction_additional_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_authentication_info' AS logical_table, 'transaction_authentication_info' AS template_table, 'transaction_authentication_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_authentication_info' AS logical_table, 'transaction_authentication_info' AS template_table, 'transaction_authentication_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_product_item' AS logical_table, 'transaction_product_item' AS template_table, 'transaction_product_item_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_product_item' AS logical_table, 'transaction_product_item' AS template_table, 'transaction_product_item_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_request' AS logical_table, 'transaction_channel_request' AS template_table, 'transaction_channel_request_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_request' AS logical_table, 'transaction_channel_request' AS template_table, 'transaction_channel_request_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_interaction_log' AS logical_table, 'transaction_channel_interaction_log' AS template_table, 'transaction_channel_interaction_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_interaction_log' AS logical_table, 'transaction_channel_interaction_log' AS template_table, 'transaction_channel_interaction_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback_log' AS logical_table, 'transaction_channel_callback_log' AS template_table, 'transaction_channel_callback_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback_log' AS logical_table, 'transaction_channel_callback_log' AS template_table, 'transaction_channel_callback_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback' AS logical_table, 'transaction_channel_callback' AS template_table, 'transaction_channel_callback_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback' AS logical_table, 'transaction_channel_callback' AS template_table, 'transaction_channel_callback_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_flow_event' AS logical_table, 'transaction_flow_event' AS template_table, 'transaction_flow_event_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_flow_event' AS logical_table, 'transaction_flow_event' AS template_table, 'transaction_flow_event_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_status_history' AS logical_table, 'transaction_status_history' AS template_table, 'transaction_status_history_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_status_history' AS logical_table, 'transaction_status_history' AS template_table, 'transaction_status_history_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_amount_change_log' AS logical_table, 'transaction_amount_change_log' AS template_table, 'transaction_amount_change_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_amount_change_log' AS logical_table, 'transaction_amount_change_log' AS template_table, 'transaction_amount_change_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_finance_state' AS logical_table, 'transaction_finance_state' AS template_table, 'transaction_finance_state_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_finance_state' AS logical_table, 'transaction_finance_state' AS template_table, 'transaction_finance_state_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_currency_conversion' AS logical_table, 'transaction_currency_conversion' AS template_table, 'transaction_currency_conversion_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_currency_conversion' AS logical_table, 'transaction_currency_conversion' AS template_table, 'transaction_currency_conversion_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification' AS logical_table, 'transaction_merchant_notification' AS template_table, 'transaction_merchant_notification_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification' AS logical_table, 'transaction_merchant_notification' AS template_table, 'transaction_merchant_notification_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification_log' AS logical_table, 'transaction_merchant_notification_log' AS template_table, 'transaction_merchant_notification_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification_log' AS logical_table, 'transaction_merchant_notification_log' AS template_table, 'transaction_merchant_notification_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_api_interaction_log' AS logical_table, 'transaction_merchant_api_interaction_log' AS template_table, 'transaction_merchant_api_interaction_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_api_interaction_log' AS logical_table, 'transaction_merchant_api_interaction_log' AS template_table, 'transaction_merchant_api_interaction_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_event_outbox' AS logical_table, 'transaction_event_outbox' AS template_table, 'transaction_event_outbox_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_event_outbox' AS logical_table, 'transaction_event_outbox' AS template_table, 'transaction_event_outbox_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_abnormal_event' AS logical_table, 'transaction_abnormal_event' AS template_table, 'transaction_abnormal_event_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_abnormal_event' AS logical_table, 'transaction_abnormal_event' AS template_table, 'transaction_abnormal_event_202604' AS physical_table, '202604' AS quarter_suffix
) target ON s.`physical_table` = target.`physical_table`
GROUP BY s.`physical_table`
HAVING COUNT(*) > 1;

-- Evidence 4: existing target rows before or after migration.
SELECT s.*
FROM `sys_sharding_physical_table` s
JOIN (
SELECT 'transaction_order' AS logical_table, 'transaction_order' AS template_table, 'transaction_order_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_order' AS logical_table, 'transaction_order' AS template_table, 'transaction_order_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_operation' AS logical_table, 'transaction_operation' AS template_table, 'transaction_operation_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_operation' AS logical_table, 'transaction_operation' AS template_table, 'transaction_operation_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_snapshot' AS logical_table, 'transaction_merchant_snapshot' AS template_table, 'transaction_merchant_snapshot_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_snapshot' AS logical_table, 'transaction_merchant_snapshot' AS template_table, 'transaction_merchant_snapshot_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_payment_method_info' AS logical_table, 'transaction_payment_method_info' AS template_table, 'transaction_payment_method_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_payment_method_info' AS logical_table, 'transaction_payment_method_info' AS template_table, 'transaction_payment_method_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_payer_info' AS logical_table, 'transaction_payer_info' AS template_table, 'transaction_payer_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_payer_info' AS logical_table, 'transaction_payer_info' AS template_table, 'transaction_payer_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_billing_info' AS logical_table, 'transaction_billing_info' AS template_table, 'transaction_billing_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_billing_info' AS logical_table, 'transaction_billing_info' AS template_table, 'transaction_billing_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_additional_info' AS logical_table, 'transaction_additional_info' AS template_table, 'transaction_additional_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_additional_info' AS logical_table, 'transaction_additional_info' AS template_table, 'transaction_additional_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_authentication_info' AS logical_table, 'transaction_authentication_info' AS template_table, 'transaction_authentication_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_authentication_info' AS logical_table, 'transaction_authentication_info' AS template_table, 'transaction_authentication_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_product_item' AS logical_table, 'transaction_product_item' AS template_table, 'transaction_product_item_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_product_item' AS logical_table, 'transaction_product_item' AS template_table, 'transaction_product_item_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_request' AS logical_table, 'transaction_channel_request' AS template_table, 'transaction_channel_request_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_request' AS logical_table, 'transaction_channel_request' AS template_table, 'transaction_channel_request_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_interaction_log' AS logical_table, 'transaction_channel_interaction_log' AS template_table, 'transaction_channel_interaction_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_interaction_log' AS logical_table, 'transaction_channel_interaction_log' AS template_table, 'transaction_channel_interaction_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback_log' AS logical_table, 'transaction_channel_callback_log' AS template_table, 'transaction_channel_callback_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback_log' AS logical_table, 'transaction_channel_callback_log' AS template_table, 'transaction_channel_callback_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback' AS logical_table, 'transaction_channel_callback' AS template_table, 'transaction_channel_callback_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback' AS logical_table, 'transaction_channel_callback' AS template_table, 'transaction_channel_callback_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_flow_event' AS logical_table, 'transaction_flow_event' AS template_table, 'transaction_flow_event_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_flow_event' AS logical_table, 'transaction_flow_event' AS template_table, 'transaction_flow_event_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_status_history' AS logical_table, 'transaction_status_history' AS template_table, 'transaction_status_history_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_status_history' AS logical_table, 'transaction_status_history' AS template_table, 'transaction_status_history_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_amount_change_log' AS logical_table, 'transaction_amount_change_log' AS template_table, 'transaction_amount_change_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_amount_change_log' AS logical_table, 'transaction_amount_change_log' AS template_table, 'transaction_amount_change_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_finance_state' AS logical_table, 'transaction_finance_state' AS template_table, 'transaction_finance_state_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_finance_state' AS logical_table, 'transaction_finance_state' AS template_table, 'transaction_finance_state_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_currency_conversion' AS logical_table, 'transaction_currency_conversion' AS template_table, 'transaction_currency_conversion_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_currency_conversion' AS logical_table, 'transaction_currency_conversion' AS template_table, 'transaction_currency_conversion_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification' AS logical_table, 'transaction_merchant_notification' AS template_table, 'transaction_merchant_notification_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification' AS logical_table, 'transaction_merchant_notification' AS template_table, 'transaction_merchant_notification_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification_log' AS logical_table, 'transaction_merchant_notification_log' AS template_table, 'transaction_merchant_notification_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification_log' AS logical_table, 'transaction_merchant_notification_log' AS template_table, 'transaction_merchant_notification_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_api_interaction_log' AS logical_table, 'transaction_merchant_api_interaction_log' AS template_table, 'transaction_merchant_api_interaction_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_api_interaction_log' AS logical_table, 'transaction_merchant_api_interaction_log' AS template_table, 'transaction_merchant_api_interaction_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_event_outbox' AS logical_table, 'transaction_event_outbox' AS template_table, 'transaction_event_outbox_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_event_outbox' AS logical_table, 'transaction_event_outbox' AS template_table, 'transaction_event_outbox_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_abnormal_event' AS logical_table, 'transaction_abnormal_event' AS template_table, 'transaction_abnormal_event_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_abnormal_event' AS logical_table, 'transaction_abnormal_event' AS template_table, 'transaction_abnormal_event_202604' AS physical_table, '202604' AS quarter_suffix
) target ON s.`physical_table` = target.`physical_table`
ORDER BY s.`physical_table`, s.`id`;

-- Evidence 5: transaction-prefix registry rows outside 06B target list; these rows must be preserved.
SELECT s.*
FROM `sys_sharding_physical_table` s
LEFT JOIN (
SELECT 'transaction_order' AS logical_table, 'transaction_order' AS template_table, 'transaction_order_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_order' AS logical_table, 'transaction_order' AS template_table, 'transaction_order_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_operation' AS logical_table, 'transaction_operation' AS template_table, 'transaction_operation_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_operation' AS logical_table, 'transaction_operation' AS template_table, 'transaction_operation_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_snapshot' AS logical_table, 'transaction_merchant_snapshot' AS template_table, 'transaction_merchant_snapshot_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_snapshot' AS logical_table, 'transaction_merchant_snapshot' AS template_table, 'transaction_merchant_snapshot_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_payment_method_info' AS logical_table, 'transaction_payment_method_info' AS template_table, 'transaction_payment_method_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_payment_method_info' AS logical_table, 'transaction_payment_method_info' AS template_table, 'transaction_payment_method_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_payer_info' AS logical_table, 'transaction_payer_info' AS template_table, 'transaction_payer_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_payer_info' AS logical_table, 'transaction_payer_info' AS template_table, 'transaction_payer_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_billing_info' AS logical_table, 'transaction_billing_info' AS template_table, 'transaction_billing_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_billing_info' AS logical_table, 'transaction_billing_info' AS template_table, 'transaction_billing_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_additional_info' AS logical_table, 'transaction_additional_info' AS template_table, 'transaction_additional_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_additional_info' AS logical_table, 'transaction_additional_info' AS template_table, 'transaction_additional_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_authentication_info' AS logical_table, 'transaction_authentication_info' AS template_table, 'transaction_authentication_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_authentication_info' AS logical_table, 'transaction_authentication_info' AS template_table, 'transaction_authentication_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_product_item' AS logical_table, 'transaction_product_item' AS template_table, 'transaction_product_item_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_product_item' AS logical_table, 'transaction_product_item' AS template_table, 'transaction_product_item_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_request' AS logical_table, 'transaction_channel_request' AS template_table, 'transaction_channel_request_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_request' AS logical_table, 'transaction_channel_request' AS template_table, 'transaction_channel_request_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_interaction_log' AS logical_table, 'transaction_channel_interaction_log' AS template_table, 'transaction_channel_interaction_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_interaction_log' AS logical_table, 'transaction_channel_interaction_log' AS template_table, 'transaction_channel_interaction_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback_log' AS logical_table, 'transaction_channel_callback_log' AS template_table, 'transaction_channel_callback_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback_log' AS logical_table, 'transaction_channel_callback_log' AS template_table, 'transaction_channel_callback_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback' AS logical_table, 'transaction_channel_callback' AS template_table, 'transaction_channel_callback_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback' AS logical_table, 'transaction_channel_callback' AS template_table, 'transaction_channel_callback_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_flow_event' AS logical_table, 'transaction_flow_event' AS template_table, 'transaction_flow_event_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_flow_event' AS logical_table, 'transaction_flow_event' AS template_table, 'transaction_flow_event_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_status_history' AS logical_table, 'transaction_status_history' AS template_table, 'transaction_status_history_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_status_history' AS logical_table, 'transaction_status_history' AS template_table, 'transaction_status_history_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_amount_change_log' AS logical_table, 'transaction_amount_change_log' AS template_table, 'transaction_amount_change_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_amount_change_log' AS logical_table, 'transaction_amount_change_log' AS template_table, 'transaction_amount_change_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_finance_state' AS logical_table, 'transaction_finance_state' AS template_table, 'transaction_finance_state_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_finance_state' AS logical_table, 'transaction_finance_state' AS template_table, 'transaction_finance_state_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_currency_conversion' AS logical_table, 'transaction_currency_conversion' AS template_table, 'transaction_currency_conversion_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_currency_conversion' AS logical_table, 'transaction_currency_conversion' AS template_table, 'transaction_currency_conversion_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification' AS logical_table, 'transaction_merchant_notification' AS template_table, 'transaction_merchant_notification_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification' AS logical_table, 'transaction_merchant_notification' AS template_table, 'transaction_merchant_notification_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification_log' AS logical_table, 'transaction_merchant_notification_log' AS template_table, 'transaction_merchant_notification_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification_log' AS logical_table, 'transaction_merchant_notification_log' AS template_table, 'transaction_merchant_notification_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_api_interaction_log' AS logical_table, 'transaction_merchant_api_interaction_log' AS template_table, 'transaction_merchant_api_interaction_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_api_interaction_log' AS logical_table, 'transaction_merchant_api_interaction_log' AS template_table, 'transaction_merchant_api_interaction_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_event_outbox' AS logical_table, 'transaction_event_outbox' AS template_table, 'transaction_event_outbox_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_event_outbox' AS logical_table, 'transaction_event_outbox' AS template_table, 'transaction_event_outbox_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_abnormal_event' AS logical_table, 'transaction_abnormal_event' AS template_table, 'transaction_abnormal_event_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_abnormal_event' AS logical_table, 'transaction_abnormal_event' AS template_table, 'transaction_abnormal_event_202604' AS physical_table, '202604' AS quarter_suffix
) target ON s.`physical_table` = target.`physical_table`
WHERE LEFT(s.`logical_table`, 12) = 'transaction_'
  AND target.`physical_table` IS NULL
ORDER BY s.`logical_table`, s.`quarter_suffix`, s.`physical_table`, s.`id`;

-- Evidence 6: physical tables and AUTO_INCREMENT values for 06B target tables.
SELECT target.`physical_table`, tables.`TABLE_NAME`, tables.`AUTO_INCREMENT`, tables.`CREATE_TIME`, tables.`UPDATE_TIME`
FROM (
SELECT 'transaction_order' AS logical_table, 'transaction_order' AS template_table, 'transaction_order_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_order' AS logical_table, 'transaction_order' AS template_table, 'transaction_order_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_operation' AS logical_table, 'transaction_operation' AS template_table, 'transaction_operation_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_operation' AS logical_table, 'transaction_operation' AS template_table, 'transaction_operation_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_snapshot' AS logical_table, 'transaction_merchant_snapshot' AS template_table, 'transaction_merchant_snapshot_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_snapshot' AS logical_table, 'transaction_merchant_snapshot' AS template_table, 'transaction_merchant_snapshot_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_payment_method_info' AS logical_table, 'transaction_payment_method_info' AS template_table, 'transaction_payment_method_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_payment_method_info' AS logical_table, 'transaction_payment_method_info' AS template_table, 'transaction_payment_method_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_payer_info' AS logical_table, 'transaction_payer_info' AS template_table, 'transaction_payer_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_payer_info' AS logical_table, 'transaction_payer_info' AS template_table, 'transaction_payer_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_billing_info' AS logical_table, 'transaction_billing_info' AS template_table, 'transaction_billing_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_billing_info' AS logical_table, 'transaction_billing_info' AS template_table, 'transaction_billing_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_additional_info' AS logical_table, 'transaction_additional_info' AS template_table, 'transaction_additional_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_additional_info' AS logical_table, 'transaction_additional_info' AS template_table, 'transaction_additional_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_authentication_info' AS logical_table, 'transaction_authentication_info' AS template_table, 'transaction_authentication_info_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_authentication_info' AS logical_table, 'transaction_authentication_info' AS template_table, 'transaction_authentication_info_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_product_item' AS logical_table, 'transaction_product_item' AS template_table, 'transaction_product_item_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_product_item' AS logical_table, 'transaction_product_item' AS template_table, 'transaction_product_item_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_request' AS logical_table, 'transaction_channel_request' AS template_table, 'transaction_channel_request_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_request' AS logical_table, 'transaction_channel_request' AS template_table, 'transaction_channel_request_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_interaction_log' AS logical_table, 'transaction_channel_interaction_log' AS template_table, 'transaction_channel_interaction_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_interaction_log' AS logical_table, 'transaction_channel_interaction_log' AS template_table, 'transaction_channel_interaction_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback_log' AS logical_table, 'transaction_channel_callback_log' AS template_table, 'transaction_channel_callback_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback_log' AS logical_table, 'transaction_channel_callback_log' AS template_table, 'transaction_channel_callback_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback' AS logical_table, 'transaction_channel_callback' AS template_table, 'transaction_channel_callback_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_channel_callback' AS logical_table, 'transaction_channel_callback' AS template_table, 'transaction_channel_callback_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_flow_event' AS logical_table, 'transaction_flow_event' AS template_table, 'transaction_flow_event_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_flow_event' AS logical_table, 'transaction_flow_event' AS template_table, 'transaction_flow_event_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_status_history' AS logical_table, 'transaction_status_history' AS template_table, 'transaction_status_history_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_status_history' AS logical_table, 'transaction_status_history' AS template_table, 'transaction_status_history_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_amount_change_log' AS logical_table, 'transaction_amount_change_log' AS template_table, 'transaction_amount_change_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_amount_change_log' AS logical_table, 'transaction_amount_change_log' AS template_table, 'transaction_amount_change_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_finance_state' AS logical_table, 'transaction_finance_state' AS template_table, 'transaction_finance_state_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_finance_state' AS logical_table, 'transaction_finance_state' AS template_table, 'transaction_finance_state_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_currency_conversion' AS logical_table, 'transaction_currency_conversion' AS template_table, 'transaction_currency_conversion_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_currency_conversion' AS logical_table, 'transaction_currency_conversion' AS template_table, 'transaction_currency_conversion_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification' AS logical_table, 'transaction_merchant_notification' AS template_table, 'transaction_merchant_notification_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification' AS logical_table, 'transaction_merchant_notification' AS template_table, 'transaction_merchant_notification_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification_log' AS logical_table, 'transaction_merchant_notification_log' AS template_table, 'transaction_merchant_notification_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_notification_log' AS logical_table, 'transaction_merchant_notification_log' AS template_table, 'transaction_merchant_notification_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_api_interaction_log' AS logical_table, 'transaction_merchant_api_interaction_log' AS template_table, 'transaction_merchant_api_interaction_log_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_merchant_api_interaction_log' AS logical_table, 'transaction_merchant_api_interaction_log' AS template_table, 'transaction_merchant_api_interaction_log_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_event_outbox' AS logical_table, 'transaction_event_outbox' AS template_table, 'transaction_event_outbox_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_event_outbox' AS logical_table, 'transaction_event_outbox' AS template_table, 'transaction_event_outbox_202604' AS physical_table, '202604' AS quarter_suffix
UNION ALL
SELECT 'transaction_abnormal_event' AS logical_table, 'transaction_abnormal_event' AS template_table, 'transaction_abnormal_event_202603' AS physical_table, '202603' AS quarter_suffix
UNION ALL
SELECT 'transaction_abnormal_event' AS logical_table, 'transaction_abnormal_event' AS template_table, 'transaction_abnormal_event_202604' AS physical_table, '202604' AS quarter_suffix
) target
LEFT JOIN `information_schema`.`TABLES` tables
  ON tables.`TABLE_SCHEMA` = DATABASE()
 AND tables.`TABLE_NAME` = target.`physical_table`
ORDER BY target.`physical_table`;
