-- Hosted Checkout V1 dev/test DDL
-- 说明：
-- 1. 本脚本仅用于 dev/test 环境建表和变更评审，生产执行前必须走正式数据库变更流程。
-- 2. 收银台表只保存会话、URL token、支付尝试、页面事件和安全事件，不保存 PAN、CVV、JWT、CAVV 明文。
-- 3. opaqueToken 和 3DS return token 均只保存 HMAC-SHA256 摘要。

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `payment_checkout_session` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理主键。',
  `checkout_session_id` VARCHAR(64) NOT NULL COMMENT '收银台会话号，平台内部唯一。',
  `merchant_id` VARCHAR(64) NOT NULL COMMENT '平台商户号。',
  `merchant_order_no` VARCHAR(128) NOT NULL COMMENT '商户订单号，用于展示和排查。',
  `merchant_request_id` VARCHAR(128) NOT NULL COMMENT '商户创建收银台请求幂等号。',
  `request_fingerprint` VARCHAR(128) NULL COMMENT '创建请求摘要，用于识别同幂等号请求内容变化。',
  `payment_action` VARCHAR(32) NOT NULL COMMENT '付款动作，如 PAYMENT、AUTHORIZATION。',
  `integration_type` VARCHAR(32) NOT NULL DEFAULT 'HOSTED_CHECKOUT' COMMENT '接入方式。',
  `checkout_status` VARCHAR(64) NOT NULL COMMENT '收银台会话状态。',
  `process_stage` VARCHAR(64) NOT NULL COMMENT '内部处理阶段。',
  `last_status_time` DATETIME(3) NOT NULL COMMENT '最近一次状态更新时间。',
  `operation_id` VARCHAR(64) NULL COMMENT '交易生命周期聚合号。',
  `root_transaction_id` VARCHAR(64) NULL COMMENT '首笔平台交易号。',
  `latest_transaction_id` VARCHAR(64) NULL COMMENT '最近一次平台交易号。',
  `transaction_date_time` DATETIME(3) NULL COMMENT '交易业务时间，用于交易分表路由。',
  `label_currency` CHAR(3) NOT NULL COMMENT '页面展示币种，ISO 4217 三位代码。',
  `label_amount` DECIMAL(20,6) NOT NULL COMMENT '页面展示金额，主币种单位。',
  `currency_exponent` TINYINT NOT NULL COMMENT '币种小数位精度。',
  `order_subject` VARCHAR(256) NULL COMMENT '订单标题。',
  `order_description` VARCHAR(1024) NULL COMMENT '订单描述。',
  `order_items_json` JSON NULL COMMENT '订单明细展示快照。',
  `allowed_payment_methods_json` JSON NOT NULL COMMENT '商户允许的支付方式快照。',
  `selected_payment_method` VARCHAR(32) NULL COMMENT '最近一次选择的支付方式。',
  `selected_payment_brand` VARCHAR(32) NULL COMMENT '最近一次选择的支付品牌。',
  `channel_code` VARCHAR(32) NULL COMMENT '最近一次使用的渠道编码。',
  `channel_mid_config_id` BIGINT NULL COMMENT '最近一次使用的渠道 MID 配置 ID。',
  `merchant_display_name` VARCHAR(256) NULL COMMENT '商户主体展示名称。',
  `merchant_logo_url` VARCHAR(512) NULL COMMENT '商户 Logo URL。',
  `merchant_return_url` VARCHAR(512) NULL COMMENT '付款完成后返回商户页面的 URL。',
  `merchant_cancel_url` VARCHAR(512) NULL COMMENT '付款人取消时返回商户页面的 URL。',
  `merchant_notify_url_hash` CHAR(64) NULL COMMENT '商户通知地址 SHA-256 摘要。',
  `locale` VARCHAR(16) NULL COMMENT '默认页面语言。',
  `payer_country` CHAR(3) NULL COMMENT '付款人国家或地区，ISO 3166-1 alpha-3。',
  `payer_email_masked` VARCHAR(256) NULL COMMENT '付款人邮箱脱敏值。',
  `payer_email_hash` CHAR(64) NULL COMMENT '付款人邮箱 SHA-256 摘要。',
  `retry_allowed` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许付款失败后重试，0否，1是。',
  `max_attempt_count` INT NOT NULL DEFAULT 3 COMMENT '最大付款尝试次数。',
  `attempt_count` INT NOT NULL DEFAULT 0 COMMENT '已创建付款尝试次数。',
  `success_attempt_id` VARCHAR(64) NULL COMMENT '成功付款尝试号。',
  `last_attempt_id` VARCHAR(64) NULL COMMENT '最近一次付款尝试号。',
  `checkout_domain` VARCHAR(256) NOT NULL COMMENT '收银台页面域名。',
  `expire_time` DATETIME(3) NOT NULL COMMENT '会话过期时间。',
  `paid_time` DATETIME(3) NULL COMMENT '支付成功时间。',
  `cancel_time` DATETIME(3) NULL COMMENT '取消时间。',
  `blocked_time` DATETIME(3) NULL COMMENT '安全拦截时间。',
  `block_reason_code` VARCHAR(64) NULL COMMENT '安全拦截原因码。',
  `last_open_time` DATETIME(3) NULL COMMENT '最近一次打开页面时间。',
  `last_submit_time` DATETIME(3) NULL COMMENT '最近一次提交支付时间。',
  `next_channel_match_time` DATETIME(3) NULL COMMENT '下一次渠道结果查询补偿时间。',
  `result_snapshot` JSON NULL COMMENT '收银台结果页脱敏快照。',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号。',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标识，0未删除，1已删除。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_checkout_session_id` (`checkout_session_id`),
  UNIQUE KEY `uk_merchant_request` (`merchant_id`, `merchant_request_id`),
  KEY `idx_merchant_order_time` (`merchant_id`, `merchant_order_no`, `create_time`),
  KEY `idx_status_expire` (`checkout_status`, `expire_time`),
  KEY `idx_latest_transaction` (`latest_transaction_id`, `transaction_date_time`),
  KEY `idx_operation` (`operation_id`, `transaction_date_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Hosted Checkout 会话主表。';

CREATE TABLE IF NOT EXISTS `payment_checkout_token` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理主键。',
  `checkout_token_id` VARCHAR(64) NOT NULL COMMENT 'URL token 记录号。',
  `checkout_session_id` VARCHAR(64) NOT NULL COMMENT '收银台会话号。',
  `merchant_id` VARCHAR(64) NOT NULL COMMENT '平台商户号。',
  `token_hash` CHAR(64) NOT NULL COMMENT 'opaqueToken HMAC-SHA256 摘要。',
  `token_hash_alg` VARCHAR(32) NOT NULL DEFAULT 'HMAC_SHA256' COMMENT 'token 摘要算法。',
  `token_key_version` VARCHAR(32) NOT NULL COMMENT 'token pepper/key 版本。',
  `token_status` VARCHAR(32) NOT NULL COMMENT 'token 状态，如 ACTIVE、REVOKED、EXPIRED。',
  `issue_reason` VARCHAR(64) NULL COMMENT '签发原因，如 CREATE、REISSUE。',
  `expire_time` DATETIME(3) NOT NULL COMMENT 'token 过期时间。',
  `first_used_time` DATETIME(3) NULL COMMENT '首次使用时间。',
  `last_used_time` DATETIME(3) NULL COMMENT '最近一次使用时间。',
  `use_count` INT NOT NULL DEFAULT 0 COMMENT '使用次数。',
  `last_client_ip_hash` CHAR(64) NULL COMMENT '最近一次使用客户端 IP 摘要。',
  `last_user_agent_hash` CHAR(64) NULL COMMENT '最近一次使用 User-Agent 摘要。',
  `revoked_time` DATETIME(3) NULL COMMENT '吊销时间。',
  `revoke_reason_code` VARCHAR(64) NULL COMMENT '吊销原因码。',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号。',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标识，0未删除，1已删除。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_checkout_token_id` (`checkout_token_id`),
  UNIQUE KEY `uk_token_hash` (`token_hash`),
  KEY `idx_session_status` (`checkout_session_id`, `token_status`),
  KEY `idx_merchant_expire` (`merchant_id`, `expire_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Hosted Checkout URL token 摘要表。';

CREATE TABLE IF NOT EXISTS `payment_checkout_attempt` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理主键。',
  `checkout_attempt_id` VARCHAR(64) NOT NULL COMMENT '付款尝试号。',
  `checkout_session_id` VARCHAR(64) NOT NULL COMMENT '收银台会话号。',
  `merchant_id` VARCHAR(64) NOT NULL COMMENT '平台商户号。',
  `merchant_order_no` VARCHAR(128) NOT NULL COMMENT '商户订单号。',
  `attempt_no` INT NOT NULL COMMENT '会话内付款尝试序号，从 1 递增。',
  `attempt_request_id` VARCHAR(128) NOT NULL COMMENT '前端本次提交幂等号。',
  `request_fingerprint` VARCHAR(128) NULL COMMENT '本次提交摘要，不能包含 PAN/CVV 明文。',
  `attempt_status` VARCHAR(64) NOT NULL COMMENT '付款尝试状态。',
  `process_stage` VARCHAR(64) NOT NULL COMMENT '内部处理阶段。',
  `payment_method` VARCHAR(32) NOT NULL COMMENT '支付方式。',
  `payment_brand` VARCHAR(32) NULL COMMENT '支付品牌或卡组织。',
  `label_currency` CHAR(3) NOT NULL COMMENT '页面展示币种。',
  `label_amount` DECIMAL(20,6) NOT NULL COMMENT '页面展示金额。',
  `channel_request_currency` CHAR(3) NULL COMMENT '上送渠道币种。',
  `channel_request_amount` DECIMAL(20,6) NULL COMMENT '上送渠道金额。',
  `operation_id` VARCHAR(64) NULL COMMENT '交易生命周期聚合号。',
  `transaction_id` VARCHAR(64) NULL COMMENT '本次支付尝试对应的平台交易号。',
  `transaction_date_time` DATETIME(3) NULL COMMENT '交易业务时间，用于交易分表路由。',
  `channel_code` VARCHAR(32) NULL COMMENT '渠道编码。',
  `channel_mid_config_id` BIGINT NULL COMMENT '渠道 MID 配置 ID。',
  `channel_order_no` VARCHAR(128) NULL COMMENT '渠道订单号。',
  `channel_transaction_id` VARCHAR(128) NULL COMMENT '渠道支付交易号。',
  `channel_request_id` VARCHAR(64) NULL COMMENT '最近一次渠道请求号。',
  `channel_status` VARCHAR(64) NULL COMMENT '渠道原始状态。',
  `channel_response_code` VARCHAR(64) NULL COMMENT '渠道响应码。',
  `channel_response_message` VARCHAR(512) NULL COMMENT '渠道响应摘要。',
  `card_bin` VARCHAR(8) NULL COMMENT '卡 BIN。',
  `card_last4` CHAR(4) NULL COMMENT '卡尾四位。',
  `card_number_masked` VARCHAR(32) NULL COMMENT '卡号脱敏展示值。',
  `cardholder_name_masked` VARCHAR(128) NULL COMMENT '持卡人姓名脱敏值。',
  `payment_account_hash` CHAR(64) NULL COMMENT '付款账户不可逆摘要。',
  `three_ds_required` TINYINT NOT NULL DEFAULT 0 COMMENT '是否要求 3DS，0否，1是。',
  `three_ds_status` VARCHAR(64) NULL COMMENT '3DS 认证状态摘要。',
  `three_ds_version` VARCHAR(32) NULL COMMENT '3DS 协议版本。',
  `three_ds_transaction_id` VARCHAR(128) NULL COMMENT 'MPGS 认证交易号。',
  `three_ds_server_transaction_id` VARCHAR(128) NULL COMMENT '3DS Server 交易号。',
  `acs_transaction_id` VARCHAR(128) NULL COMMENT 'ACS 交易号。',
  `ds_transaction_id` VARCHAR(128) NULL COMMENT 'Directory Server 交易号。',
  `eci` VARCHAR(8) NULL COMMENT 'ECI 值。',
  `liability_shift` TINYINT NULL COMMENT '是否责任转移，0否，1是。',
  `three_ds_return_token_hash` CHAR(64) NULL COMMENT '3DS return token HMAC-SHA256 摘要。',
  `authentication_redirect_url_hash` CHAR(64) NULL COMMENT '认证回跳 URL 摘要。',
  `browser_info_json` JSON NULL COMMENT '浏览器信息脱敏快照。',
  `device_info_json` JSON NULL COMMENT '设备信息脱敏快照。',
  `failure_reason_code` VARCHAR(64) NULL COMMENT '失败原因码。',
  `failure_reason_message` VARCHAR(512) NULL COMMENT '失败原因摘要。',
  `payer_visible_message` VARCHAR(512) NULL COMMENT '付款人可见提示。',
  `submit_time` DATETIME(3) NOT NULL COMMENT '提交支付时间。',
  `authentication_start_time` DATETIME(3) NULL COMMENT '3DS 认证开始时间。',
  `authentication_complete_time` DATETIME(3) NULL COMMENT '3DS 认证完成时间。',
  `channel_submit_time` DATETIME(3) NULL COMMENT '支付请求上送渠道时间。',
  `complete_time` DATETIME(3) NULL COMMENT '本次尝试完成时间。',
  `result_snapshot` JSON NULL COMMENT '本次尝试结果页脱敏快照。',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号。',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标识，0未删除，1已删除。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_checkout_attempt_id` (`checkout_attempt_id`),
  UNIQUE KEY `uk_session_attempt_request` (`checkout_session_id`, `attempt_request_id`),
  UNIQUE KEY `uk_session_attempt_no` (`checkout_session_id`, `attempt_no`),
  UNIQUE KEY `uk_three_ds_return_token_hash` (`three_ds_return_token_hash`),
  KEY `idx_session_status_time` (`checkout_session_id`, `attempt_status`, `create_time`),
  KEY `idx_transaction` (`transaction_id`, `transaction_date_time`),
  KEY `idx_operation` (`operation_id`, `transaction_date_time`),
  KEY `idx_channel_reference` (`channel_code`, `channel_order_no`, `channel_transaction_id`),
  KEY `idx_channel_request_id` (`channel_request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Hosted Checkout 付款尝试表。';

CREATE TABLE IF NOT EXISTS `payment_checkout_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理主键。',
  `checkout_event_id` VARCHAR(64) NOT NULL COMMENT '收银台事件号。',
  `checkout_session_id` VARCHAR(64) NOT NULL COMMENT '收银台会话号。',
  `checkout_attempt_id` VARCHAR(64) NULL COMMENT '付款尝试号。',
  `merchant_id` VARCHAR(64) NULL COMMENT '平台商户号。',
  `event_type` VARCHAR(64) NOT NULL COMMENT '事件类型。',
  `event_stage` VARCHAR(64) NULL COMMENT '事件阶段。',
  `event_result` VARCHAR(32) NOT NULL COMMENT '事件结果。',
  `checkout_status_before` VARCHAR(64) NULL COMMENT '事件前会话状态。',
  `checkout_status_after` VARCHAR(64) NULL COMMENT '事件后会话状态。',
  `attempt_status_before` VARCHAR(64) NULL COMMENT '事件前尝试状态。',
  `attempt_status_after` VARCHAR(64) NULL COMMENT '事件后尝试状态。',
  `operation_id` VARCHAR(64) NULL COMMENT '交易生命周期聚合号。',
  `transaction_id` VARCHAR(64) NULL COMMENT '平台交易号。',
  `transaction_date_time` DATETIME(3) NULL COMMENT '交易业务时间，用于交易分表路由。',
  `trace_id` VARCHAR(128) NULL COMMENT '链路追踪号。',
  `request_id` VARCHAR(128) NULL COMMENT '请求号。',
  `client_ip_hash` CHAR(64) NULL COMMENT '客户端 IP 摘要。',
  `user_agent_hash` CHAR(64) NULL COMMENT 'User-Agent 摘要。',
  `origin_hash` CHAR(64) NULL COMMENT 'Origin 摘要。',
  `referer_hash` CHAR(64) NULL COMMENT 'Referer 摘要。',
  `event_payload_json` JSON NULL COMMENT '事件载荷脱敏快照。',
  `event_time` DATETIME(3) NOT NULL COMMENT '事件发生时间。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_checkout_event_id` (`checkout_event_id`),
  KEY `idx_session_time` (`checkout_session_id`, `event_time`),
  KEY `idx_attempt_time` (`checkout_attempt_id`, `event_time`),
  KEY `idx_event_type_time` (`event_type`, `event_time`),
  KEY `idx_trace_id` (`trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Hosted Checkout 业务和页面事件表。';

CREATE TABLE IF NOT EXISTS `payment_checkout_security_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理主键。',
  `security_event_id` VARCHAR(64) NOT NULL COMMENT '安全事件号。',
  `checkout_session_id` VARCHAR(64) NULL COMMENT '收银台会话号。',
  `checkout_attempt_id` VARCHAR(64) NULL COMMENT '付款尝试号。',
  `merchant_id` VARCHAR(64) NULL COMMENT '平台商户号。',
  `token_hash` CHAR(64) NULL COMMENT 'opaqueToken 或 3DS return token 摘要。',
  `security_event_type` VARCHAR(64) NOT NULL COMMENT '安全事件类型。',
  `security_decision` VARCHAR(32) NOT NULL COMMENT '安全决策，如 ALLOW、BLOCK。',
  `block_reason_code` VARCHAR(64) NULL COMMENT '拦截原因码。',
  `http_status` SMALLINT NULL COMMENT 'HTTP 状态码。',
  `request_method` VARCHAR(16) NULL COMMENT '请求方法。',
  `request_path_hash` CHAR(64) NULL COMMENT '请求路径摘要。',
  `client_ip_hash` CHAR(64) NULL COMMENT '客户端 IP 摘要。',
  `client_ip_country` CHAR(3) NULL COMMENT '客户端 IP 国家或地区。',
  `user_agent_hash` CHAR(64) NULL COMMENT 'User-Agent 摘要。',
  `device_id_hash` CHAR(64) NULL COMMENT '设备 ID 摘要。',
  `origin_hash` CHAR(64) NULL COMMENT 'Origin 摘要。',
  `referer_hash` CHAR(64) NULL COMMENT 'Referer 摘要。',
  `risk_score` DECIMAL(10,4) NULL COMMENT '风险评分。',
  `evidence_json` JSON NULL COMMENT '安全证据脱敏快照。',
  `trace_id` VARCHAR(128) NULL COMMENT '链路追踪号。',
  `event_time` DATETIME(3) NOT NULL COMMENT '事件发生时间。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_security_event_id` (`security_event_id`),
  KEY `idx_token_hash` (`token_hash`),
  KEY `idx_session_time` (`checkout_session_id`, `event_time`),
  KEY `idx_decision_time` (`security_decision`, `event_time`),
  KEY `idx_type_time` (`security_event_type`, `event_time`),
  KEY `idx_trace_id` (`trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Hosted Checkout 安全事件表。';
