-- 轻量级任务调度中心 SQL 草案。
-- 当前文件只提供建表参考，不在本次代码改造中自动执行数据库变更。

CREATE TABLE `sys_job_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `job_code` VARCHAR(100) NOT NULL COMMENT '任务编码',
  `job_name` VARCHAR(100) NOT NULL COMMENT '任务名称',
  `job_group` VARCHAR(50) NOT NULL DEFAULT 'system' COMMENT '任务分组：system/payment/settlement/notification',
  `handler_code` VARCHAR(100) NOT NULL COMMENT '任务处理器编码',
  `cron_expression` VARCHAR(100) DEFAULT NULL COMMENT 'Cron表达式',
  `scheduler_mode` VARCHAR(30) NOT NULL DEFAULT 'STANDALONE' COMMENT '调度模式：STANDALONE/DISTRIBUTED',
  `trigger_mode` VARCHAR(30) NOT NULL DEFAULT 'CRON' COMMENT '触发模式：CRON/MANUAL',
  `execute_mode` VARCHAR(30) NOT NULL DEFAULT 'SYNC' COMMENT '执行模式：SYNC/ASYNC',
  `route_strategy` VARCHAR(30) NOT NULL DEFAULT 'LOCAL' COMMENT '路由策略：LOCAL/FIRST',
  `misfire_strategy` VARCHAR(30) NOT NULL DEFAULT 'IGNORE' COMMENT '错过调度策略：IGNORE/FIRE_ONCE',
  `timeout_seconds` INT NOT NULL DEFAULT 300 COMMENT '超时时间，单位秒',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '失败重试次数',
  `retry_interval_seconds` INT NOT NULL DEFAULT 60 COMMENT '失败重试间隔，单位秒',
  `allow_concurrent` TINYINT NOT NULL DEFAULT 0 COMMENT '是否允许同一任务并发执行：0=否，1=是',
  `params` JSON DEFAULT NULL COMMENT '默认任务参数JSON',
  `status` VARCHAR(30) NOT NULL DEFAULT 'DISABLED' COMMENT '任务状态：ENABLED/DISABLED',
  `description` VARCHAR(500) DEFAULT NULL COMMENT '任务描述',
  `next_trigger_time` DATETIME DEFAULT NULL COMMENT '下次触发时间',
  `last_trigger_time` DATETIME DEFAULT NULL COMMENT '上次触发时间',
  `last_run_status` VARCHAR(30) DEFAULT NULL COMMENT '上次执行状态',
  `lock_owner` VARCHAR(100) DEFAULT NULL COMMENT '锁持有节点',
  `lock_until` DATETIME DEFAULT NULL COMMENT '锁过期时间',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0=否，1=是',
  `create_by` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_job_code` (`job_code`),
  KEY `idx_status_next_trigger_time` (`status`, `next_trigger_time`),
  KEY `idx_handler_code` (`handler_code`),
  KEY `idx_job_group` (`job_group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统任务定义表';

CREATE TABLE `sys_job_run_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `run_id` VARCHAR(100) NOT NULL COMMENT '执行批次号',
  `job_id` BIGINT NOT NULL COMMENT '任务ID',
  `job_code` VARCHAR(100) NOT NULL COMMENT '任务编码',
  `job_name` VARCHAR(100) NOT NULL COMMENT '任务名称',
  `handler_code` VARCHAR(100) NOT NULL COMMENT '任务处理器编码',
  `trigger_type` VARCHAR(30) NOT NULL COMMENT '触发方式：SCHEDULE/MANUAL/RETRY',
  `scheduler_mode` VARCHAR(30) NOT NULL COMMENT '调度模式：STANDALONE/DISTRIBUTED',
  `execute_mode` VARCHAR(30) NOT NULL DEFAULT 'SYNC' COMMENT '执行模式：SYNC/ASYNC',
  `executor_node` VARCHAR(100) DEFAULT NULL COMMENT '执行节点',
  `run_status` VARCHAR(30) NOT NULL COMMENT '执行状态：WAITING/RUNNING/SUCCESS/FAILED/TIMEOUT/CANCELLED',
  `start_time` DATETIME DEFAULT NULL COMMENT '开始时间',
  `end_time` DATETIME DEFAULT NULL COMMENT '结束时间',
  `duration_ms` BIGINT DEFAULT NULL COMMENT '执行耗时，毫秒',
  `retry_index` INT NOT NULL DEFAULT 0 COMMENT '当前重试序号',
  `max_retry_count` INT NOT NULL DEFAULT 0 COMMENT '最大重试次数',
  `timeout_seconds` INT NOT NULL DEFAULT 300 COMMENT '超时时间快照，单位秒',
  `params_snapshot` JSON DEFAULT NULL COMMENT '脱敏后的参数快照',
  `result_message` VARCHAR(1000) DEFAULT NULL COMMENT '执行结果摘要',
  `error_message` VARCHAR(2000) DEFAULT NULL COMMENT '失败原因摘要',
  `trace_id` VARCHAR(100) DEFAULT NULL COMMENT '链路追踪ID',
  `operator_id` VARCHAR(64) DEFAULT NULL COMMENT '操作人ID',
  `operator_name` VARCHAR(100) DEFAULT NULL COMMENT '操作人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_run_id` (`run_id`),
  KEY `idx_job_code_create_time` (`job_code`, `create_time`),
  KEY `idx_run_status_create_time` (`run_status`, `create_time`),
  KEY `idx_executor_node_create_time` (`executor_node`, `create_time`),
  KEY `idx_job_id_create_time` (`job_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统任务执行日志表';

CREATE TABLE `sys_job_executor_node` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `node_id` VARCHAR(100) NOT NULL COMMENT '节点ID',
  `app_name` VARCHAR(100) NOT NULL COMMENT '服务名称',
  `host` VARCHAR(100) NOT NULL COMMENT '节点Host',
  `port` INT DEFAULT NULL COMMENT '节点端口',
  `instance_id` VARCHAR(150) DEFAULT NULL COMMENT '实例ID',
  `status` VARCHAR(30) NOT NULL DEFAULT 'ONLINE' COMMENT '节点状态：ONLINE/OFFLINE/UNKNOWN',
  `last_heartbeat_time` DATETIME NOT NULL COMMENT '最后心跳时间',
  `current_running_count` INT NOT NULL DEFAULT 0 COMMENT '当前运行任务数',
  `max_concurrent_count` INT NOT NULL DEFAULT 10 COMMENT '最大并发数',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_node_id` (`node_id`),
  KEY `idx_status_heartbeat` (`status`, `last_heartbeat_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统任务执行节点表';
