-- 分表治理表结构 SQL 草案。
-- 该脚本用于记录分表物理表状态和建表任务结果，不创建真实交易分表。

CREATE TABLE IF NOT EXISTS `sys_sharding_physical_table` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `logical_table` VARCHAR(64) NOT NULL COMMENT '逻辑表名',
  `template_table` VARCHAR(64) NOT NULL COMMENT '模板表名',
  `physical_table` VARCHAR(128) NOT NULL COMMENT '物理表名',
  `sharding_column` VARCHAR(64) NOT NULL COMMENT '分表字段',
  `strategy` VARCHAR(32) NOT NULL COMMENT '分表策略',
  `year` INT NOT NULL COMMENT '年份',
  `quarter` TINYINT NOT NULL COMMENT '季度：1-4',
  `quarter_suffix` VARCHAR(6) NOT NULL COMMENT '季度后缀，例如202602',
  `data_source` VARCHAR(64) NOT NULL COMMENT '数据源',
  `table_status` VARCHAR(32) NOT NULL COMMENT '表状态：EXISTS/CREATED/MISSING/FAILED',
  `auto_created` TINYINT NOT NULL DEFAULT 0 COMMENT '是否自动创建：0=否，1=是',
  `auto_increment_start` BIGINT DEFAULT NULL COMMENT 'AUTO_INCREMENT起始值',
  `auto_increment_current` BIGINT DEFAULT NULL COMMENT 'AUTO_INCREMENT当前值',
  `auto_increment_max` BIGINT DEFAULT NULL COMMENT '当前季度最大安全值',
  `schema_check_status` VARCHAR(32) DEFAULT NULL COMMENT '结构校验状态：MATCHED/MISMATCHED/SKIPPED/FAILED',
  `last_check_time` DATETIME(3) DEFAULT NULL COMMENT '最后检查时间',
  `created_time` DATETIME(3) DEFAULT NULL COMMENT '物理表创建时间',
  `error_message` VARCHAR(1000) DEFAULT NULL COMMENT '失败原因',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '记录创建时间',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_physical_table` (`physical_table`),
  KEY `idx_logic_year_quarter` (`logical_table`, `year`, `quarter`),
  KEY `idx_table_status` (`table_status`),
  KEY `idx_last_check_time` (`last_check_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='分表物理表登记表';

CREATE TABLE IF NOT EXISTS `sys_sharding_table_create_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `batch_no` VARCHAR(64) NOT NULL COMMENT '任务批次号',
  `trigger_type` VARCHAR(32) NOT NULL COMMENT '触发方式：SCHEDULE/MANUAL',
  `dry_run` TINYINT NOT NULL DEFAULT 0 COMMENT '是否仅预演：0=否，1=是',
  `target_quarters` VARCHAR(255) NOT NULL COMMENT '目标季度，例如2026-Q2,2026-Q3',
  `planned_count` INT NOT NULL DEFAULT 0 COMMENT '计划处理数量',
  `created_count` INT NOT NULL DEFAULT 0 COMMENT '创建数量',
  `skipped_count` INT NOT NULL DEFAULT 0 COMMENT '跳过数量',
  `failed_count` INT NOT NULL DEFAULT 0 COMMENT '失败数量',
  `schema_mismatch_count` INT NOT NULL DEFAULT 0 COMMENT '结构不一致数量',
  `run_status` VARCHAR(32) NOT NULL COMMENT '执行状态：SUCCESS/PARTIAL_FAILED/FAILED',
  `result_summary` TEXT DEFAULT NULL COMMENT '执行摘要JSON',
  `error_message` VARCHAR(1000) DEFAULT NULL COMMENT '失败原因',
  `start_time` DATETIME(3) NOT NULL COMMENT '开始时间',
  `end_time` DATETIME(3) DEFAULT NULL COMMENT '结束时间',
  `duration_ms` BIGINT DEFAULT NULL COMMENT '耗时毫秒',
  `operator_id` VARCHAR(64) DEFAULT NULL COMMENT '操作人ID',
  `operator_name` VARCHAR(100) DEFAULT NULL COMMENT '操作人名称',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_batch_no` (`batch_no`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_run_status` (`run_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='分表建表任务日志表';
