-- 收单交易核心表结构 v1.6
-- 说明：
-- 1. 本文件用于 dev/test 环境初始化和评审，生产执行前必须做变更评审与数据备份。
-- 2. 所有交易相关表统一使用 transaction_ 前缀。
-- 3. operation_id 是平台内部生命周期关联标识，同一原始交易生命周期内保持不变；transaction_id 是平台当前交易唯一标识，每一笔授权、请款、退款、Void、拒付等资金动作各不相同。
-- 4. 除 transaction_idempotency 不分表外，交易事实、日志、状态、通知、outbox 均按 transaction_date_time DATETIME(3) 季度分表。
-- 5. 交易查询、关联查询、更新和删除必须携带 transaction_date_time 或明确时间范围，避免跨分表误扫。
-- 6. 金额字段统一 DECIMAL(20,6)，汇率字段统一 DECIMAL(24,12)，币种使用 ISO 4217 三位代码。
-- 7. 渠道请求、响应、回调、商户通知日志允许保存可读 JSON，但完整卡号、CVV、JWT、密钥、认证头必须入库前脱敏。
-- 8. 本版不设计店铺、物流、外风控结构化表，也不建设 transaction_global_index。

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `transaction_idempotency` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID，使用系统统一主键规则。',
  `idempotency_scope` VARCHAR(64) NOT NULL COMMENT '幂等范围，如 PAYMENT_CREATE、AUTHORIZATION、CAPTURE、REFUND、CHANNEL_CALLBACK、MQ_CONSUME。',
  `idempotency_key` VARCHAR(256) NOT NULL COMMENT '幂等键，同一范围内唯一；建议由 merchant_id、商户订单/动作号、交易类型等稳定字段组成。',
  `merchant_id` VARCHAR(64) NULL COMMENT '平台商户号；渠道回调或系统任务无法识别商户时可为空。',
  `merchant_order_no` VARCHAR(128) NULL COMMENT '商户订单号，用于商户侧创建交易幂等和排查。',
  `merchant_order_id` VARCHAR(128) NULL COMMENT '商户本次API请求唯一标识，来自 orderInfo.orderId，用于资金类幂等。',
  `transaction_type` VARCHAR(32) NULL COMMENT '交易类型，对齐字典 transaction_type。',
  `transaction_id` VARCHAR(64) NULL COMMENT '平台当前交易唯一标识；创建前可为空，成功创建后回填。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识；创建前可为空，成功创建后回填。',
  `transaction_status` VARCHAR(32) NOT NULL COMMENT '幂等处理对应交易状态，对齐字典 transaction_status。',
  `request_amount` DECIMAL(20,6) NULL COMMENT '请求金额，主币种单位，用于幂等冲突排查。',
  `request_currency` CHAR(3) NULL COMMENT '请求币种，ISO 4217 三位代码。',
  `transaction_amount` DECIMAL(20,6) NULL COMMENT '系统交易金额，主币种单位。',
  `transaction_currency` CHAR(3) NULL COMMENT '系统交易币种，ISO 4217 三位代码。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间；幂等表不分表，但保留交易路由和审计语义。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间，用于跨时区统一排序和审计。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区，如 Asia/Shanghai。',
  `transaction_timezone_offset` VARCHAR(6) NULL COMMENT '交易发生时区偏移，如 +08:00，仅用于审计展示。',
  `request_fingerprint` VARCHAR(128) NULL COMMENT '请求体安全摘要，用于识别同幂等键但请求内容不一致。',
  `result_snapshot` JSON NULL COMMENT '首次处理结果快照，用于重复请求直接返回。',
  `expire_time` DATETIME(3) NULL COMMENT '幂等记录过期时间；资金类通常为空表示长期保留。',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号。',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标识，0未删除，1已删除。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scope_key` (`idempotency_scope`, `idempotency_key`),
  KEY `idx_transaction_id` (`transaction_id`),
  KEY `idx_operation_id` (`operation_id`),
  KEY `idx_merchant_order_type` (`merchant_id`, `merchant_order_no`, `transaction_type`),
  KEY `idx_merchant_order_id` (`merchant_id`, `merchant_order_id`, `transaction_type`),
  KEY `idx_status_time` (`transaction_status`, `transaction_date_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='资金类请求、渠道回调、MQ消费等全局幂等兜底；沿用现有表，不再新建第二套幂等表。';

CREATE TABLE IF NOT EXISTS `transaction_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID，季度物理表可按系统分表规则设置自增起始值。',
  `operation_id` VARCHAR(64) NOT NULL COMMENT '平台内部生命周期关联标识，同一原始交易生命周期内保持不变，不返回商户。',
  `root_transaction_id` VARCHAR(64) NOT NULL COMMENT '生命周期内首个平台开户交易ID。',
  `latest_transaction_id` VARCHAR(64) NOT NULL COMMENT '最近一次平台开户交易ID。',
  `merchant_id` VARCHAR(64) NOT NULL COMMENT '平台商户号。',
  `merchant_order_no` VARCHAR(128) NOT NULL COMMENT '商户原始订单号，用于商户查询和创建交易幂等。',
  `merchant_order_id` VARCHAR(128) NOT NULL COMMENT '商户本次API请求唯一标识，来自 orderInfo.orderId，用于幂等和排查。',
  `source_transaction_id` VARCHAR(64) NULL COMMENT '源平台交易ID；用于复制、补单、争议等扩展关联。',
  `payment_method` VARCHAR(32) NOT NULL COMMENT '支付方式，如 CARD、APPLE_PAY、GOOGLE_PAY。',
  `payment_brand` VARCHAR(32) NULL COMMENT '卡品牌或支付品牌，如 VISA、MASTERCARD。',
  `transaction_type` VARCHAR(32) NOT NULL COMMENT '首个交易类型，对齐字典 transaction_type。',
  `transaction_status` VARCHAR(32) NOT NULL COMMENT '生命周期当前交易状态，对齐字典 transaction_status。',
  `process_stage` VARCHAR(64) NOT NULL COMMENT '内部处理阶段，如 ACCEPTED、WAITING_3DS、WAITING_CALLBACK。',
  `pending_reason_code` VARCHAR(64) NULL COMMENT '挂起原因码，仅 PENDING 时使用。',
  `fail_reason_code` VARCHAR(64) NULL COMMENT '失败原因码，用于后台展示真实原因。',
  `fail_reason_message` VARCHAR(512) NULL COMMENT '后台可见失败原因描述。',
  `merchant_visible_message` VARCHAR(512) NULL COMMENT '商户可见的模糊失败原因。',
  `payer_visible_message` VARCHAR(512) NULL COMMENT '付款人可见的模糊失败原因。',
  `label_currency` CHAR(3) NOT NULL COMMENT '标签币种，即商户上送/页面展示的原始交易币种。',
  `label_amount` DECIMAL(20,6) NOT NULL COMMENT '标签金额，即商户上送/页面展示的原始交易金额。',
  `transaction_currency` CHAR(3) NOT NULL COMMENT '系统交易币种，经过 DCC/EDC 后用于交易核心处理。',
  `transaction_amount` DECIMAL(20,6) NOT NULL COMMENT '系统交易金额，经过 DCC/EDC 后用于交易核心处理。',
  `channel_request_currency` CHAR(3) NULL COMMENT '上送渠道的币种。',
  `channel_request_amount` DECIMAL(20,6) NULL COMMENT '上送渠道的金额。',
  `settlement_currency` CHAR(3) NULL COMMENT '预计或最终结算币种。',
  `settlement_amount` DECIMAL(20,6) NULL COMMENT '预计或最终结算金额。',
  `currency_exponent` TINYINT NOT NULL COMMENT '交易币种小数位精度，如 USD=2、JPY=0。',
  `dcc_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '是否启用 DCC，0否，1是。',
  `edc_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '是否启用 EDC，0否，1是；渠道不支持商户币种时使用。',
  `transaction_rate` DECIMAL(24,12) NULL COMMENT '标签金额转交易金额使用的汇率。',
  `rate_source` VARCHAR(64) NULL COMMENT '汇率来源，如 PLATFORM、CHANNEL、MERCHANT。',
  `rate_time` DATETIME(3) NULL COMMENT '汇率生效或报价时间。',
  `authorized_amount` DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '累计授权成功金额，交易币种单位。',
  `captured_amount` DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '累计请款成功金额，交易币种单位。',
  `refunded_amount` DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '累计退款成功金额，交易币种单位。',
  `chargeback_amount` DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '累计拒付金额，交易币种单位。',
  `available_capture_amount` DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '当前可请款金额，交易币种单位。',
  `available_refund_amount` DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '当前可退款金额，交易币种单位。',
  `settlement_status` VARCHAR(32) NOT NULL DEFAULT 'NOT_SETTLED' COMMENT '结算状态，建议进入字典 settlement_status。',
  `reconciliation_status` VARCHAR(32) NOT NULL DEFAULT 'NOT_RECONCILED' COMMENT '对账状态，建议进入字典 reconciliation_status。',
  `accounting_status` VARCHAR(32) NOT NULL DEFAULT 'NOT_ACCOUNTED' COMMENT '入账状态，建议进入字典 accounting_status。',
  `channel_match_status` VARCHAR(32) NOT NULL DEFAULT 'NOT_REQUIRED' COMMENT '渠道结果勾兑/查询确认状态；定时任务按该字段调用渠道查询API同步一致。',
  `channel_match_result` VARCHAR(64) NULL COMMENT '最近一次渠道查询确认结果，如 SAME、STATUS_CHANGED、AMOUNT_CHANGED、CHANNEL_NOT_FOUND。',
  `channel_match_count` INT NOT NULL DEFAULT 0 COMMENT '渠道结果勾兑查询次数。',
  `last_channel_match_request_id` VARCHAR(64) NULL COMMENT '最近一次渠道查询确认请求ID，关联 transaction_channel_request.request_id。',
  `last_channel_match_time` DATETIME(3) NULL COMMENT '最近一次渠道查询确认时间。',
  `next_channel_match_time` DATETIME(3) NULL COMMENT '下一次渠道查询确认计划时间。',
  `channel_match_fail_reason` VARCHAR(512) NULL COMMENT '最近一次渠道查询确认失败原因。',
  `settlement_batch_no` VARCHAR(64) NULL COMMENT '最近一次结算批次号。',
  `reconciliation_batch_no` VARCHAR(64) NULL COMMENT '最近一次对账批次号。',
  `channel_id` BIGINT NULL COMMENT '渠道信息ID，关联 channel_info.id。',
  `channel_code` VARCHAR(32) NULL COMMENT '渠道编码，如 MPGS。',
  `channel_mid_config_id` BIGINT NULL COMMENT '交易使用的渠道MID配置ID。',
  `channel_merchant_id` VARCHAR(128) NULL COMMENT '渠道真实商户号或渠道MID，来自MID元数据快照。',
  `channel_order_no` VARCHAR(128) NULL COMMENT '渠道侧主订单号。',
  `internal_risk_decision` VARCHAR(32) NULL COMMENT '最近一次内风控决策，如 PASS、REJECT、REVIEW、REQUIRE_3DS；外风控结构化字段本版不设计。',
  `internal_risk_record_no` VARCHAR(64) NULL COMMENT '最近一次内风控评估流水号；不承载外风控平台RequestID。',
  `callback_url_hash` CHAR(64) NULL COMMENT '商户通知地址 SHA-256，用于审计排查。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间，所有交易分表统一字段。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `transaction_timezone_offset` VARCHAR(6) NULL COMMENT '交易发生时区偏移，如 +08:00。',
  `last_status_time` DATETIME(3) NOT NULL COMMENT '最近一次交易状态更新时间。',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号，用于状态机 CAS 更新。',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标识，0未删除，1已删除。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_operation_id` (`operation_id`),
  UNIQUE KEY `uk_root_transaction_id` (`root_transaction_id`),
  KEY `idx_latest_transaction_id` (`latest_transaction_id`),
  KEY `idx_merchant_order_time` (`merchant_id`, `merchant_order_no`, `transaction_date_time`),
  KEY `idx_status_time` (`transaction_status`, `transaction_date_time`),
  KEY `idx_channel_match_next` (`channel_match_status`, `next_channel_match_time`),
  KEY `idx_settlement_time` (`settlement_status`, `transaction_date_time`),
  KEY `idx_reconciliation_time` (`reconciliation_status`, `transaction_date_time`),
  KEY `idx_channel_order` (`channel_code`, `channel_order_no`, `transaction_date_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='交易生命周期主单；同一笔原始交易的授权、增量授权、请款、退款、拒付等动作共用同一个 operation_id。';

CREATE TABLE IF NOT EXISTS `transaction_operation` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `operation_id` VARCHAR(64) NOT NULL COMMENT '平台内部生命周期关联标识，同一原始交易生命周期内保持不变。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识，每一笔授权、请款、退款、撤销都不同。',
  `source_transaction_id` VARCHAR(64) NULL COMMENT '源平台交易ID；退款、请款、撤销等后续动作关联原交易时使用。',
  `source_operation_id` VARCHAR(64) NULL COMMENT '源平台内部生命周期关联标识；请款关联授权、退款关联请款或原授权时使用。',
  `merchant_id` VARCHAR(64) NOT NULL COMMENT '平台商户号。',
  `merchant_order_no` VARCHAR(128) NOT NULL COMMENT '商户订单号。',
  `merchant_operation_no` VARCHAR(128) NOT NULL COMMENT '商户动作单号，如 captureNo、refundNo；首笔可等于 merchant_order_no。',
  `operation_sequence` INT NOT NULL COMMENT '生命周期内动作序号，从1递增。',
  `transaction_type` VARCHAR(32) NOT NULL COMMENT '交易类型，对齐字典 transaction_type。',
  `transaction_status` VARCHAR(32) NOT NULL COMMENT '动作当前交易状态，对齐字典 transaction_status。',
  `process_stage` VARCHAR(64) NOT NULL COMMENT '内部处理阶段。',
  `pending_reason_code` VARCHAR(64) NULL COMMENT '挂起原因码。',
  `fail_reason_code` VARCHAR(64) NULL COMMENT '失败原因码。',
  `fail_reason_message` VARCHAR(512) NULL COMMENT '后台可见失败原因描述。',
  `label_currency` CHAR(3) NOT NULL COMMENT '商户上送/标签币种。',
  `label_amount` DECIMAL(20,6) NOT NULL COMMENT '商户上送/标签金额。',
  `transaction_currency` CHAR(3) NOT NULL COMMENT '系统交易币种。',
  `transaction_amount` DECIMAL(20,6) NOT NULL COMMENT '系统交易金额。',
  `approved_currency` CHAR(3) NULL COMMENT '渠道批准或最终成功币种。',
  `approved_amount` DECIMAL(20,6) NULL COMMENT '渠道批准或最终成功金额。',
  `channel_request_currency` CHAR(3) NULL COMMENT '上送渠道币种。',
  `channel_request_amount` DECIMAL(20,6) NULL COMMENT '上送渠道金额。',
  `settlement_currency` CHAR(3) NULL COMMENT '动作预计或最终结算币种。',
  `settlement_amount` DECIMAL(20,6) NULL COMMENT '动作预计或最终结算金额。',
  `currency_exponent` TINYINT NOT NULL COMMENT '交易币种小数位精度。',
  `dcc_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '当前动作是否启用 DCC。',
  `edc_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '当前动作是否启用 EDC。',
  `transaction_rate` DECIMAL(24,12) NULL COMMENT '标签金额转交易金额使用的汇率。',
  `channel_id` BIGINT NULL COMMENT '渠道信息ID。',
  `channel_code` VARCHAR(32) NULL COMMENT '渠道编码。',
  `channel_mid_config_id` BIGINT NULL COMMENT '渠道MID配置ID。',
  `channel_terminal_id` VARCHAR(128) NULL COMMENT '渠道终端号或子MID。',
  `channel_order_no` VARCHAR(128) NULL COMMENT '渠道订单号。',
  `channel_transaction_id` VARCHAR(128) NULL COMMENT '渠道交易ID。',
  `channel_status` VARCHAR(64) NULL COMMENT '渠道原始交易状态。',
  `channel_response_code` VARCHAR(64) NULL COMMENT '渠道响应码，如 MPGS response.acquirerCode。',
  `channel_response_message` VARCHAR(512) NULL COMMENT '渠道响应摘要。',
  `auth_code` VARCHAR(64) NULL COMMENT '授权码。',
  `rrn` VARCHAR(64) NULL COMMENT '检索参考号或渠道参考号。',
  `acquirer_reference_no` VARCHAR(128) NULL COMMENT '收单机构参考号，用于对账和争议。',
  `settlement_status` VARCHAR(32) NOT NULL DEFAULT 'NOT_SETTLED' COMMENT '当前动作结算状态。',
  `reconciliation_status` VARCHAR(32) NOT NULL DEFAULT 'NOT_RECONCILED' COMMENT '当前动作对账状态。',
  `accounting_status` VARCHAR(32) NOT NULL DEFAULT 'NOT_ACCOUNTED' COMMENT '当前动作入账状态。',
  `channel_match_status` VARCHAR(32) NOT NULL DEFAULT 'NOT_REQUIRED' COMMENT '当前动作的渠道结果勾兑/查询确认状态。',
  `channel_match_result` VARCHAR(64) NULL COMMENT '最近一次渠道查询确认结果。',
  `channel_match_count` INT NOT NULL DEFAULT 0 COMMENT '当前动作渠道查询确认次数。',
  `last_channel_match_request_id` VARCHAR(64) NULL COMMENT '最近一次渠道查询确认请求ID。',
  `last_channel_match_time` DATETIME(3) NULL COMMENT '最近一次渠道查询确认时间。',
  `next_channel_match_time` DATETIME(3) NULL COMMENT '下一次渠道查询确认计划时间。',
  `channel_match_fail_reason` VARCHAR(512) NULL COMMENT '最近一次渠道查询确认失败原因。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间，所有交易分表统一字段。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `operation_time` DATETIME(3) NOT NULL COMMENT '动作受理时间。',
  `complete_time` DATETIME(3) NULL COMMENT '动作完成时间。',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号。',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标识。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_transaction_id` (`transaction_id`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_operation_time` (`operation_id`, `transaction_date_time`),
  KEY `idx_source_operation` (`source_operation_id`, `transaction_date_time`),
  UNIQUE KEY `uk_merchant_operation` (`merchant_id`, `source_transaction_id`, `transaction_type`, `merchant_operation_no`),
  KEY `idx_status_time` (`transaction_status`, `transaction_date_time`),
  KEY `idx_channel_match_next` (`channel_match_status`, `next_channel_match_time`),
  KEY `idx_channel_order` (`channel_code`, `channel_order_no`, `transaction_date_time`),
  KEY `idx_channel_transaction` (`channel_code`, `channel_transaction_id`, `transaction_date_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='交易动作单；授权、增量授权、请款、退款、Void、拒付等每一个动作一条记录。';

CREATE TABLE IF NOT EXISTS `transaction_merchant_snapshot` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `snapshot_id` VARCHAR(64) NOT NULL COMMENT '交易商户快照ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识；订单级快照可为空。',
  `merchant_id` VARCHAR(64) NOT NULL COMMENT '平台商户号。',
  `merchant_name` VARCHAR(256) NULL COMMENT '交易发生时商户名称快照。',
  `merchant_country` VARCHAR(3) NULL COMMENT '商户国家/地区，ISO 3166-1 alpha-3。',
  `merchant_category_code` VARCHAR(16) NULL COMMENT 'MCC。',
  `merchant_status` VARCHAR(32) NULL COMMENT '交易发生时商户状态。',
  `channel_id` BIGINT NULL COMMENT '渠道信息ID。',
  `channel_code` VARCHAR(32) NULL COMMENT '渠道编码。',
  `channel_mid_config_id` BIGINT NULL COMMENT '渠道MID配置ID。',
  `channel_merchant_id` VARCHAR(128) NULL COMMENT '渠道真实MID，来自MID元数据。',
  `terminal_id` VARCHAR(128) NULL COMMENT '终端号。',
  `channel_mid_metadata_json` JSON NULL COMMENT '交易使用的MID核心元数据快照。',
  `settlement_config_snapshot_json` JSON NULL COMMENT '结算配置快照。',
  `fee_config_snapshot_json` JSON NULL COMMENT '费率配置快照。',
  `internal_risk_config_snapshot_json` JSON NULL COMMENT '内风控配置快照；外风控平台、RequestID、触发时间、审核记录本版不结构化。',
  `route_config_snapshot_json` JSON NULL COMMENT '路由决策配置快照。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_snapshot_id` (`snapshot_id`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_operation_time` (`operation_id`, `transaction_date_time`),
  KEY `idx_merchant_time` (`merchant_id`, `transaction_date_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='保存交易发生时的商户、渠道、MID、费率、结算、内风控配置快照，避免后续配置变更影响历史交易解释。';

CREATE TABLE IF NOT EXISTS `transaction_payment_method_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `payment_info_id` VARCHAR(64) NOT NULL COMMENT '支付工具信息ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识。',
  `payment_method` VARCHAR(32) NOT NULL COMMENT '支付方式，如 CARD、APPLE_PAY。',
  `payment_brand` VARCHAR(32) NULL COMMENT '卡品牌或钱包品牌，如 VISA、MASTERCARD。',
  `card_bin` VARCHAR(12) NULL COMMENT '卡BIN，可按合规要求保留前6或前8。',
  `card_last4` VARCHAR(4) NULL COMMENT '卡号后四位。',
  `card_number_masked` VARCHAR(32) NULL COMMENT '脱敏卡号，如 512345******0008。',
  `cardholder_name_masked` VARCHAR(128) NULL COMMENT '持卡人姓名脱敏展示值。',
  `expiry_month` VARCHAR(2) NULL COMMENT '卡有效期月份。',
  `expiry_year` VARCHAR(4) NULL COMMENT '卡有效期年份。',
  `token_id` VARCHAR(128) NULL COMMENT '平台或渠道支付令牌ID。',
  `wallet_type` VARCHAR(32) NULL COMMENT '钱包类型。',
  `payment_account_hash` CHAR(64) NULL COMMENT '支付账户哈希，用于风控和排查。',
  `issuer_country` VARCHAR(3) NULL COMMENT '发卡国家/地区。',
  `funding_method` VARCHAR(32) NULL COMMENT '资金类型，如 CREDIT、DEBIT。',
  `three_ds_indicator` VARCHAR(32) NULL COMMENT '3DS标识或策略结果。',
  `csc_result` VARCHAR(32) NULL COMMENT 'CVV/CSC校验结果；不保存CVV原文。',
  `avs_result` VARCHAR(32) NULL COMMENT 'AVS校验结果。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_info_id` (`payment_info_id`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_operation_time` (`operation_id`, `transaction_date_time`),
  KEY `idx_account_hash` (`payment_account_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='保存卡、钱包、令牌、渠道绑卡标识等支付工具摘要。';

CREATE TABLE IF NOT EXISTS `transaction_payer_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `payer_info_id` VARCHAR(64) NOT NULL COMMENT '付款人信息ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识。',
  `payer_id` VARCHAR(128) NULL COMMENT '商户侧付款人ID或客户ID。',
  `payer_name_masked` VARCHAR(128) NULL COMMENT '付款人姓名脱敏展示值。',
  `payer_email_masked` VARCHAR(256) NULL COMMENT '付款人邮箱脱敏展示值。',
  `payer_email_hash` CHAR(64) NULL COMMENT '付款人邮箱哈希。',
  `payer_phone_masked` VARCHAR(64) NULL COMMENT '付款人手机号脱敏展示值。',
  `payer_phone_hash` CHAR(64) NULL COMMENT '付款人手机号哈希。',
  `payer_country` VARCHAR(3) NULL COMMENT '付款人国家/地区。',
  `client_ip` VARCHAR(64) NULL COMMENT '付款人客户端IP。',
  `client_ip_country` VARCHAR(3) NULL COMMENT 'IP解析国家/地区。',
  `user_agent_hash` CHAR(64) NULL COMMENT 'User-Agent 哈希。',
  `device_id_hash` CHAR(64) NULL COMMENT '设备ID哈希。',
  `device_info_json` JSON NULL COMMENT '设备摘要信息。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payer_info_id` (`payer_info_id`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_email_hash` (`payer_email_hash`),
  KEY `idx_phone_hash` (`payer_phone_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='保存付款人身份、联系方式、IP、设备摘要，用于风控、审计和后台展示。';

CREATE TABLE IF NOT EXISTS `transaction_billing_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `billing_info_id` VARCHAR(64) NOT NULL COMMENT '账单信息ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识。',
  `billing_name_masked` VARCHAR(128) NULL COMMENT '账单姓名脱敏展示值。',
  `billing_email_masked` VARCHAR(256) NULL COMMENT '账单邮箱脱敏展示值。',
  `billing_phone_masked` VARCHAR(64) NULL COMMENT '账单手机号脱敏展示值。',
  `billing_country` VARCHAR(3) NULL COMMENT '账单国家/地区。',
  `billing_state` VARCHAR(64) NULL COMMENT '账单州/省。',
  `billing_city` VARCHAR(128) NULL COMMENT '账单城市。',
  `billing_address_line1_masked` VARCHAR(256) NULL COMMENT '账单地址1脱敏值。',
  `billing_address_line2_masked` VARCHAR(256) NULL COMMENT '账单地址2脱敏值。',
  `billing_postal_code` VARCHAR(32) NULL COMMENT '账单邮编。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_billing_info_id` (`billing_info_id`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_country_time` (`billing_country`, `transaction_date_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='保存交易维度账单地址和邮编等信息，供卡组织、渠道、风控、争议场景使用。';

CREATE TABLE IF NOT EXISTS `transaction_additional_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `additional_id` VARCHAR(64) NOT NULL COMMENT '附属信息ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识。',
  `recurring_type` VARCHAR(32) NULL COMMENT '循环付款类型。',
  `installment_count` INT NULL COMMENT '分期期数。',
  `auth_incremental_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '是否增量授权。',
  `auth_valid_until` DATETIME(3) NULL COMMENT '授权有效截止时间。',
  `checkout_session_id` VARCHAR(128) NULL COMMENT 'Hosted Checkout 会话ID。',
  `payment_link_id` VARCHAR(128) NULL COMMENT '支付链接ID。',
  `qr_code_id` VARCHAR(128) NULL COMMENT '二维码支付ID。',
  `browser_info_json` JSON NULL COMMENT '浏览器摘要信息。',
  `order_extra_json` JSON NULL COMMENT '商户订单扩展信息。',
  `channel_extra_json` JSON NULL COMMENT '渠道扩展摘要。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_additional_id` (`additional_id`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_operation_time` (`operation_id`, `transaction_date_time`),
  KEY `idx_checkout_session` (`checkout_session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='保存循环付款、分期、Hosted Checkout、二维码、支付链接等扩展属性，避免主表字段膨胀。';

CREATE TABLE IF NOT EXISTS `transaction_authentication_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `authentication_info_id` VARCHAR(64) NOT NULL COMMENT '认证信息ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识。',
  `authentication_type` VARCHAR(32) NOT NULL COMMENT '认证类型，如 3DS、SCA、NETWORK_TOKEN_AUTH。',
  `authentication_status` VARCHAR(64) NULL COMMENT '平台归一后的认证状态，如 NOT_REQUIRED、AUTHENTICATED、FAILED、ATTEMPTED。',
  `authentication_source` VARCHAR(64) NULL COMMENT '认证结果来源，如 CHANNEL、CARD_SCHEME、PLATFORM。',
  `three_ds_version` VARCHAR(32) NULL COMMENT '3DS版本，如 1.0.2、2.2.0。',
  `three_ds_transaction_id` VARCHAR(128) NULL COMMENT '3DS交易ID。',
  `three_ds_server_transaction_id` VARCHAR(128) NULL COMMENT '3DS Server交易ID。',
  `acs_transaction_id` VARCHAR(128) NULL COMMENT 'ACS交易ID。',
  `ds_transaction_id` VARCHAR(128) NULL COMMENT 'Directory Server交易ID。',
  `eci` VARCHAR(8) NULL COMMENT '电子商务交易指示值 ECI。',
  `cavv` VARCHAR(256) NULL COMMENT 'CAVV/AAV认证值，按合规要求可脱敏或加密保存。',
  `xid` VARCHAR(256) NULL COMMENT '3DS 1.x XID。',
  `liability_shift` TINYINT NULL COMMENT '是否责任转移，0否，1是。',
  `challenge_required` TINYINT NULL COMMENT '是否需要挑战认证，0否，1是。',
  `challenge_status` VARCHAR(32) NULL COMMENT '挑战认证状态，如 REQUIRED、COMPLETED、FAILED、CANCELLED。',
  `authentication_redirect_url_hash` CHAR(64) NULL COMMENT '认证跳转地址哈希，用于排查。',
  `authentication_result_code` VARCHAR(64) NULL COMMENT '认证结果码。',
  `authentication_result_message` VARCHAR(512) NULL COMMENT '认证结果描述。',
  `authentication_time` DATETIME(3) NULL COMMENT '认证完成或结果确认时间。',
  `authentication_extra_json` JSON NULL COMMENT '认证扩展摘要，保存渠道/卡组织非高频字段。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_authentication_info_id` (`authentication_info_id`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_operation_time` (`operation_id`, `transaction_date_time`),
  KEY `idx_three_ds_transaction` (`three_ds_transaction_id`, `transaction_date_time`),
  KEY `idx_auth_status_time` (`authentication_status`, `authentication_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='保存3DS、SCA、渠道/卡组织认证结果，支撑交易详情页认证信息展示和后续责任转移判断。';

CREATE TABLE IF NOT EXISTS `transaction_product_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `product_item_id` VARCHAR(64) NOT NULL COMMENT '商品明细ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识；订单级商品明细可为空。',
  `merchant_id` VARCHAR(64) NOT NULL COMMENT '平台商户号。',
  `merchant_order_no` VARCHAR(128) NOT NULL COMMENT '商户订单号。',
  `item_sequence` INT NOT NULL COMMENT '商品行序号，从1递增。',
  `product_code` VARCHAR(128) NULL COMMENT '商户侧商品编码或SKU。',
  `product_name` VARCHAR(256) NULL COMMENT '交易发生时商品名称快照。',
  `product_category` VARCHAR(128) NULL COMMENT '商品分类。',
  `quantity` DECIMAL(20,6) NOT NULL DEFAULT 1 COMMENT '购买数量，支持小数数量场景。',
  `unit_price_currency` CHAR(3) NULL COMMENT '商品单价币种。',
  `unit_price_amount` DECIMAL(20,6) NULL COMMENT '商品单价金额。',
  `item_currency` CHAR(3) NOT NULL COMMENT '商品行金额币种。',
  `item_amount` DECIMAL(20,6) NOT NULL COMMENT '商品行金额，等于数量、单价、折扣、税费等计算后的行金额。',
  `tax_currency` CHAR(3) NULL COMMENT '商品行税费币种。',
  `tax_amount` DECIMAL(20,6) NULL COMMENT '商品行税费金额。',
  `discount_currency` CHAR(3) NULL COMMENT '商品行折扣币种。',
  `discount_amount` DECIMAL(20,6) NULL COMMENT '商品行折扣金额。',
  `description` VARCHAR(512) NULL COMMENT '商品描述摘要。',
  `product_extra_json` JSON NULL COMMENT '商品扩展摘要。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_product_item_id` (`product_item_id`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_operation_time` (`operation_id`, `transaction_date_time`),
  KEY `idx_product_code_time` (`product_code`, `transaction_date_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='保存商户上送的商品/订单项目明细，支撑交易详情页商品列表、风控摘要、争议和人工排查。';

CREATE TABLE IF NOT EXISTS `transaction_channel_request` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `request_id` VARCHAR(64) NOT NULL COMMENT '平台渠道请求ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识，授权、请款、退款、撤销每个动作各自唯一。',
  `operation_id` VARCHAR(64) NOT NULL COMMENT '平台内部生命周期关联标识。',
  `channel_id` BIGINT NULL COMMENT '渠道信息ID；路由失败或仅记录异常链路时可为空。',
  `channel_code` VARCHAR(32) NOT NULL COMMENT '渠道编码。',
  `channel_mid_config_id` BIGINT NULL COMMENT '渠道MID配置ID。',
  `transaction_type` VARCHAR(32) NOT NULL COMMENT '交易类型，对齐字典 transaction_type。',
  `request_scene` VARCHAR(64) NOT NULL COMMENT '渠道请求场景，如 AUTHORIZATION、CAPTURE、REFUND、VOID、RETRIEVE、QUERY_CONFIRM。',
  `channel_match_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '是否为渠道结果勾兑/查询确认请求，0否，1是。',
  `request_status` VARCHAR(32) NOT NULL COMMENT '请求状态，如 INIT、SUCCESS、FAILED、TIMEOUT。',
  `http_method` VARCHAR(16) NULL COMMENT 'HTTP方法。',
  `request_url_masked` VARCHAR(512) NULL COMMENT '脱敏后的请求URL。',
  `request_currency` CHAR(3) NULL COMMENT '上送渠道币种。',
  `request_amount` DECIMAL(20,6) NULL COMMENT '上送渠道金额。',
  `channel_order_no` VARCHAR(128) NULL COMMENT '渠道订单号。',
  `channel_transaction_id` VARCHAR(128) NULL COMMENT '渠道交易ID。',
  `gateway_result` VARCHAR(64) NULL COMMENT '渠道网关外层结果，如 MPGS result。',
  `gateway_code` VARCHAR(64) NULL COMMENT '渠道网关码，如 MPGS response.gatewayCode。',
  `acquirer_code` VARCHAR(64) NULL COMMENT '收单响应码，如 MPGS response.acquirerCode；授权/支付成功重点判断字段。',
  `acquirer_message` VARCHAR(512) NULL COMMENT '收单响应描述。',
  `channel_status` VARCHAR(64) NULL COMMENT '渠道原始交易状态。',
  `platform_success` TINYINT NOT NULL DEFAULT 0 COMMENT '平台按渠道规则判断是否成功。',
  `platform_result_code` VARCHAR(64) NULL COMMENT '平台统一结果码。',
  `platform_fail_reason` VARCHAR(512) NULL COMMENT '后台可见失败原因。',
  `request_start_time` DATETIME(3) NOT NULL COMMENT '渠道请求发起时间。',
  `response_time` DATETIME(3) NULL COMMENT '渠道响应时间。',
  `duration_millis` INT NULL COMMENT '渠道请求耗时，单位毫秒。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号。',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标识。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_request_id` (`request_id`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_operation_time` (`operation_id`, `transaction_date_time`),
  KEY `idx_channel_order` (`channel_code`, `channel_order_no`, `transaction_date_time`),
  KEY `idx_channel_transaction_identity` (`channel_code`, `channel_order_no`, `channel_transaction_id`, `transaction_date_time`),
  KEY `idx_request_status_time` (`request_status`, `request_start_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='保存一次渠道请求的核心字段、同步响应摘要和渠道结果判断。';

CREATE TABLE IF NOT EXISTS `transaction_channel_interaction_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `interaction_log_id` VARCHAR(64) NOT NULL COMMENT '渠道交互日志ID。',
  `request_id` VARCHAR(64) NOT NULL COMMENT '平台渠道请求ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NOT NULL COMMENT '平台内部生命周期关联标识。',
  `channel_code` VARCHAR(32) NOT NULL COMMENT '渠道编码。',
  `interaction_type` VARCHAR(32) NOT NULL COMMENT '交互类型：REQUEST、RESPONSE、EXCEPTION。',
  `http_method` VARCHAR(16) NULL COMMENT 'HTTP方法。',
  `request_url_masked` VARCHAR(512) NULL COMMENT '脱敏请求URL。',
  `http_status` INT NULL COMMENT 'HTTP状态码。',
  `request_header_json_masked` JSON NULL COMMENT '脱敏请求头 JSON。',
  `request_body_json_masked` MEDIUMTEXT NULL COMMENT '脱敏请求体 JSON 字符串，便于复制到 JSON 工具查看。',
  `response_header_json_masked` JSON NULL COMMENT '脱敏响应头 JSON。',
  `response_body_json_masked` MEDIUMTEXT NULL COMMENT '脱敏响应体 JSON 字符串，便于复制到 JSON 工具查看。',
  `exception_type` VARCHAR(128) NULL COMMENT '异常类型。',
  `exception_message` VARCHAR(1024) NULL COMMENT '异常摘要。',
  `duration_millis` INT NULL COMMENT '耗时毫秒。',
  `trace_id` VARCHAR(128) NULL COMMENT '链路追踪ID。',
  `interaction_time` DATETIME(3) NOT NULL COMMENT '交互日志产生时间。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_interaction_log_id` (`interaction_log_id`),
  KEY `idx_request_time` (`request_id`, `transaction_date_time`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_channel_time` (`channel_code`, `interaction_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='保存渠道请求、响应、异常的可审计日志；请求/响应对象直接转 JSON 后脱敏入库。';

CREATE TABLE IF NOT EXISTS `transaction_channel_callback_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `callback_log_id` VARCHAR(64) NOT NULL COMMENT '渠道回调日志ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识，可由回调解析或业务处理后回填。',
  `channel_code` VARCHAR(32) NOT NULL COMMENT '渠道编码。',
  `callback_type` VARCHAR(64) NOT NULL COMMENT '回调类型。',
  `channel_order_no` VARCHAR(128) NULL COMMENT '渠道订单号。',
  `channel_transaction_id` VARCHAR(128) NULL COMMENT '渠道交易ID。',
  `request_uri` VARCHAR(512) NULL COMMENT '回调请求URI。',
  `http_method` VARCHAR(16) NULL COMMENT 'HTTP方法。',
  `source_ip` VARCHAR(64) NULL COMMENT '渠道回调来源IP。',
  `request_header_json_masked` JSON NULL COMMENT '脱敏请求头 JSON。',
  `request_body_json_masked` MEDIUMTEXT NULL COMMENT '脱敏回调原文 JSON 字符串。',
  `signature_valid` TINYINT NOT NULL DEFAULT 0 COMMENT '签名校验是否通过。',
  `ip_allowed` TINYINT NOT NULL DEFAULT 0 COMMENT 'IP白名单是否通过。',
  `platform_response_code` VARCHAR(64) NULL COMMENT '平台返回给渠道的响应码。',
  `platform_response_body` VARCHAR(1024) NULL COMMENT '平台返回给渠道的响应摘要。',
  `callback_received_time` DATETIME(3) NOT NULL COMMENT '渠道回调接收时间。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '原交易业务时间，所有交易分表统一字段。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '原交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '原交易业务时间所属 IANA 时区。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_callback_log_id` (`callback_log_id`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_channel_order` (`channel_code`, `channel_order_no`, `transaction_date_time`),
  KEY `idx_received_time` (`callback_received_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='保存渠道回调原文、验签、IP校验和平台响应日志。';

CREATE TABLE IF NOT EXISTS `transaction_channel_callback` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `callback_id` VARCHAR(64) NOT NULL COMMENT '渠道回调业务ID。',
  `callback_log_id` VARCHAR(64) NOT NULL COMMENT '渠道回调日志ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识。',
  `channel_code` VARCHAR(32) NOT NULL COMMENT '渠道编码。',
  `channel_order_no` VARCHAR(128) NULL COMMENT '渠道订单号。',
  `channel_transaction_id` VARCHAR(128) NULL COMMENT '渠道交易ID。',
  `callback_type` VARCHAR(64) NOT NULL COMMENT '回调类型。',
  `channel_event_type` VARCHAR(64) NULL COMMENT '渠道原始事件类型。',
  `callback_status` VARCHAR(32) NOT NULL COMMENT '回调处理状态：RECEIVED、PROCESSED、IGNORED、FAILED。',
  `idempotency_key` VARCHAR(256) NOT NULL COMMENT '渠道回调幂等键。',
  `signature_valid` TINYINT NOT NULL DEFAULT 0 COMMENT '签名校验是否通过。',
  `ip_allowed` TINYINT NOT NULL DEFAULT 0 COMMENT 'IP白名单是否通过。',
  `parsed_transaction_status` VARCHAR(32) NULL COMMENT '从渠道回调解析出的平台目标状态。',
  `previous_transaction_status` VARCHAR(32) NULL COMMENT '状态推进前平台状态。',
  `target_transaction_status` VARCHAR(32) NULL COMMENT '状态推进目标状态。',
  `process_result` VARCHAR(64) NULL COMMENT '业务处理结果，如 STATUS_CHANGED、DUPLICATE、TERMINAL_IGNORED。',
  `fail_reason` VARCHAR(512) NULL COMMENT '处理失败原因。',
  `callback_received_time` DATETIME(3) NOT NULL COMMENT '渠道回调接收时间。',
  `processed_time` DATETIME(3) NULL COMMENT '回调处理完成时间。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '原交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '原交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '原交易业务时间所属 IANA 时区。',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号。',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标识。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_callback_id` (`callback_id`),
  UNIQUE KEY `uk_callback_idempotency` (`channel_code`, `idempotency_key`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_callback_status_time` (`callback_status`, `callback_received_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='保存渠道回调解析后的业务处理结果、幂等和状态推进结果。';

CREATE TABLE IF NOT EXISTS `transaction_flow_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `flow_event_id` VARCHAR(64) NOT NULL COMMENT '流程事件ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识。',
  `event_type` VARCHAR(64) NOT NULL COMMENT '事件类型，如 API_ACCEPTED、PARAM_VALIDATED、MERCHANT_CHECKED、CHANNEL_CALLED、CHANNEL_MATCHED。',
  `event_stage` VARCHAR(64) NOT NULL COMMENT '事件阶段，如 API、VALIDATION、MERCHANT、CONFIG、RISK、ROUTE、CHANNEL、CALLBACK、MQ。',
  `event_status` VARCHAR(32) NOT NULL COMMENT '事件状态，如 SUCCESS、FAILED、SKIPPED。',
  `event_name` VARCHAR(128) NOT NULL COMMENT '页面展示的事件名称。',
  `event_content` VARCHAR(1024) NULL COMMENT '事件摘要说明。',
  `previous_status` VARCHAR(32) NULL COMMENT '事件发生前交易状态。',
  `current_status` VARCHAR(32) NULL COMMENT '事件发生后交易状态。',
  `operator_type` VARCHAR(32) NOT NULL DEFAULT 'SYSTEM' COMMENT '操作者类型：SYSTEM、MERCHANT、CHANNEL、JOB、ADMIN。',
  `operator_id` VARCHAR(128) NULL COMMENT '操作者标识。',
  `reference_type` VARCHAR(64) NULL COMMENT '关联对象类型，如 REQUEST、CALLBACK、OUTBOX。',
  `reference_id` VARCHAR(64) NULL COMMENT '关联对象ID。',
  `error_code` VARCHAR(64) NULL COMMENT '错误码。',
  `error_message` VARCHAR(512) NULL COMMENT '错误摘要。',
  `event_time` DATETIME(3) NOT NULL COMMENT '事件发生时间。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_flow_event_id` (`flow_event_id`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`, `event_time`),
  KEY `idx_operation_time` (`operation_id`, `transaction_date_time`, `event_time`),
  KEY `idx_event_type_time` (`event_type`, `event_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='记录交易每一个流程事件，用于后台时间线展示和问题追踪。';

CREATE TABLE IF NOT EXISTS `transaction_status_history` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `status_history_id` VARCHAR(64) NOT NULL COMMENT '状态历史ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识。',
  `status_object` VARCHAR(32) NOT NULL COMMENT '状态对象：ORDER、OPERATION、FINANCE、NOTIFICATION。',
  `from_status` VARCHAR(32) NULL COMMENT '流转前状态。',
  `to_status` VARCHAR(32) NOT NULL COMMENT '流转后状态。',
  `trigger_type` VARCHAR(64) NOT NULL COMMENT '触发类型：API、CHANNEL_RESPONSE、CHANNEL_CALLBACK、CHANNEL_QUERY_CONFIRM、JOB、ADMIN、RECONCILIATION。',
  `trigger_id` VARCHAR(64) NULL COMMENT '触发对象ID，如 request_id、callback_id、job_log_id。',
  `transition_result` VARCHAR(32) NOT NULL COMMENT '流转结果：SUCCESS、REJECTED、IGNORED。',
  `fail_reason` VARCHAR(512) NULL COMMENT '流转失败或忽略原因。',
  `version_before` INT NULL COMMENT '流转前版本号。',
  `version_after` INT NULL COMMENT '流转后版本号。',
  `status_time` DATETIME(3) NOT NULL COMMENT '状态流转时间。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_status_history_id` (`status_history_id`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`, `status_time`),
  KEY `idx_operation_time` (`operation_id`, `transaction_date_time`, `status_time`),
  KEY `idx_status_object_time` (`status_object`, `to_status`, `status_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='记录订单、动作、财务状态机每一次流转，支持审计和问题追踪。';

CREATE TABLE IF NOT EXISTS `transaction_amount_change_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `amount_change_id` VARCHAR(64) NOT NULL COMMENT '金额变动ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NOT NULL COMMENT '触发金额变动的平台内部生命周期关联标识。',
  `source_operation_id` VARCHAR(64) NULL COMMENT '被影响或被引用的源动作ID。',
  `change_type` VARCHAR(64) NOT NULL COMMENT '变动类型：AUTH_INCREASE、CAPTURE、REFUND、VOID、CHARGEBACK。',
  `amount_currency` CHAR(3) NOT NULL COMMENT '金额币种。',
  `change_amount` DECIMAL(20,6) NOT NULL COMMENT '本次变动金额，可正可负。',
  `authorized_before` DECIMAL(20,6) NOT NULL COMMENT '变动前累计授权金额。',
  `authorized_after` DECIMAL(20,6) NOT NULL COMMENT '变动后累计授权金额。',
  `captured_before` DECIMAL(20,6) NOT NULL COMMENT '变动前累计请款金额。',
  `captured_after` DECIMAL(20,6) NOT NULL COMMENT '变动后累计请款金额。',
  `refunded_before` DECIMAL(20,6) NOT NULL COMMENT '变动前累计退款金额。',
  `refunded_after` DECIMAL(20,6) NOT NULL COMMENT '变动后累计退款金额。',
  `available_capture_before` DECIMAL(20,6) NOT NULL COMMENT '变动前可请款金额。',
  `available_capture_after` DECIMAL(20,6) NOT NULL COMMENT '变动后可请款金额。',
  `available_refund_before` DECIMAL(20,6) NOT NULL COMMENT '变动前可退款金额。',
  `available_refund_after` DECIMAL(20,6) NOT NULL COMMENT '变动后可退款金额。',
  `change_reason` VARCHAR(512) NULL COMMENT '金额变动原因。',
  `change_time` DATETIME(3) NOT NULL COMMENT '金额变动时间。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_amount_change_id` (`amount_change_id`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`, `change_time`),
  KEY `idx_operation_time` (`operation_id`, `transaction_date_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='记录授权、请款、退款、拒付等动作对订单累计金额的影响。';

CREATE TABLE IF NOT EXISTS `transaction_finance_state` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `finance_state_id` VARCHAR(64) NOT NULL COMMENT '财务状态ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NOT NULL COMMENT '平台内部生命周期关联标识。',
  `transaction_type` VARCHAR(32) NOT NULL COMMENT '交易类型。',
  `settlement_status` VARCHAR(32) NOT NULL DEFAULT 'NOT_SETTLED' COMMENT '结算状态。',
  `settlement_currency` CHAR(3) NULL COMMENT '结算币种。',
  `settlement_amount` DECIMAL(20,6) NULL COMMENT '结算金额。',
  `settlement_date` DATE NULL COMMENT '结算业务日期。',
  `settlement_cycle` VARCHAR(16) NULL COMMENT '结算周期，如 T+0、T+1、T+2。',
  `settlement_batch_no` VARCHAR(64) NULL COMMENT '结算批次号。',
  `reconciliation_status` VARCHAR(32) NOT NULL DEFAULT 'NOT_RECONCILED' COMMENT '对账状态。',
  `reconciliation_date` DATE NULL COMMENT '对账业务日期。',
  `reconciliation_batch_no` VARCHAR(64) NULL COMMENT '对账批次号。',
  `accounting_status` VARCHAR(32) NOT NULL DEFAULT 'NOT_ACCOUNTED' COMMENT '入账状态。',
  `accounting_time` DATETIME(3) NULL COMMENT '入账时间。',
  `channel_fee_currency` CHAR(3) NULL COMMENT '渠道手续费币种。',
  `channel_fee_amount` DECIMAL(20,6) NULL COMMENT '渠道手续费金额。',
  `platform_fee_currency` CHAR(3) NULL COMMENT '平台手续费币种。',
  `platform_fee_amount` DECIMAL(20,6) NULL COMMENT '平台手续费金额。',
  `merchant_receivable_currency` CHAR(3) NULL COMMENT '商户应收币种。',
  `merchant_receivable_amount` DECIMAL(20,6) NULL COMMENT '商户应收金额。',
  `reserve_currency` CHAR(3) NULL COMMENT '保证金币种。',
  `reserve_amount` DECIMAL(20,6) NULL COMMENT '保证金金额。',
  `net_settlement_currency` CHAR(3) NULL COMMENT '净结算币种。',
  `net_settlement_amount` DECIMAL(20,6) NULL COMMENT '净结算金额。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号。',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标识。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_finance_state_id` (`finance_state_id`),
  UNIQUE KEY `uk_operation_finance` (`operation_id`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_settlement_status_time` (`settlement_status`, `transaction_date_time`),
  KEY `idx_reconciliation_status_time` (`reconciliation_status`, `transaction_date_time`),
  KEY `idx_accounting_status_time` (`accounting_status`, `transaction_date_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='保存交易维度结算、对账、入账当前状态和批次关联。';

CREATE TABLE IF NOT EXISTS `transaction_currency_conversion` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `conversion_id` VARCHAR(64) NOT NULL COMMENT '币种转换ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识。',
  `conversion_scene` VARCHAR(32) NOT NULL COMMENT '换汇场景：DCC、EDC、SETTLEMENT、REFUND、RECONCILIATION。',
  `source_currency` CHAR(3) NOT NULL COMMENT '源币种。',
  `source_amount` DECIMAL(20,6) NOT NULL COMMENT '源金额。',
  `target_currency` CHAR(3) NOT NULL COMMENT '目标币种。',
  `target_amount` DECIMAL(20,6) NOT NULL COMMENT '目标金额。',
  `exchange_rate` DECIMAL(24,12) NOT NULL COMMENT '换汇汇率。',
  `rate_source` VARCHAR(64) NULL COMMENT '汇率来源。',
  `rate_quote_id` VARCHAR(128) NULL COMMENT '汇率报价ID。',
  `rate_time` DATETIME(3) NOT NULL COMMENT '汇率报价或生效时间。',
  `rounding_mode` VARCHAR(32) NOT NULL COMMENT '舍入规则，如 HALF_UP、HALF_EVEN。',
  `source_currency_exponent` TINYINT NOT NULL COMMENT '源币种小数位。',
  `target_currency_exponent` TINYINT NOT NULL COMMENT '目标币种小数位。',
  `dcc_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '是否DCC换汇记录。',
  `edc_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '是否EDC换汇记录。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_conversion_id` (`conversion_id`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_operation_time` (`operation_id`, `transaction_date_time`),
  KEY `idx_scene_time` (`conversion_scene`, `rate_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='保存DCC、渠道币种转换EDC、结算换汇、退款换汇等汇率报价、换算金额和舍入规则快照。';

CREATE TABLE IF NOT EXISTS `transaction_merchant_notification` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `notify_id` VARCHAR(64) NOT NULL COMMENT '商户通知任务ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识。',
  `merchant_id` VARCHAR(64) NOT NULL COMMENT '平台商户号。',
  `merchant_order_no` VARCHAR(128) NOT NULL COMMENT '商户订单号。',
  `notify_type` VARCHAR(64) NOT NULL COMMENT '通知类型，如 PAYMENT_RESULT、REFUND_RESULT、CHARGEBACK。',
  `event_type` VARCHAR(64) NOT NULL COMMENT '触发通知的交易事件类型。',
  `notify_status` VARCHAR(32) NOT NULL COMMENT '通知状态：INIT、PROCESSING、SUCCESS、FAILED、CLOSED。',
  `notify_config_version` VARCHAR(64) NULL COMMENT '商户通知配置版本，来自MQ同步配置。',
  `notify_config_snapshot_json` JSON NULL COMMENT '触发时使用的通知配置摘要快照。',
  `target_url_hash` CHAR(64) NOT NULL COMMENT '通知URL哈希。',
  `target_url_masked` VARCHAR(512) NULL COMMENT '脱敏通知URL，用于后台排查。',
  `payload_json_masked` MEDIUMTEXT NULL COMMENT '脱敏通知载荷 JSON。',
  `sign_type` VARCHAR(32) NULL COMMENT '商户通知签名方式。',
  `last_attempt_no` INT NOT NULL DEFAULT 0 COMMENT '最近一次通知尝试次数。',
  `max_retry_count` INT NOT NULL DEFAULT 10 COMMENT '最大重试次数。',
  `next_retry_time` DATETIME(3) NULL COMMENT '下一次重试时间。',
  `success_time` DATETIME(3) NULL COMMENT '通知成功时间。',
  `fail_reason` VARCHAR(512) NULL COMMENT '最近失败原因。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号。',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标识。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notify_id` (`notify_id`),
  UNIQUE KEY `uk_notify_idempotency` (`merchant_id`, `transaction_id`, `notify_type`, `event_type`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_notify_status_retry` (`notify_status`, `next_retry_time`),
  KEY `idx_merchant_time` (`merchant_id`, `transaction_date_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='保存给商户异步通知的任务当前状态、重试计划和成功记录。';

CREATE TABLE IF NOT EXISTS `transaction_merchant_notification_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `notify_log_id` VARCHAR(64) NOT NULL COMMENT '商户通知日志ID。',
  `notify_id` VARCHAR(64) NOT NULL COMMENT '商户通知任务ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识。',
  `merchant_id` VARCHAR(64) NOT NULL COMMENT '平台商户号。',
  `attempt_no` INT NOT NULL COMMENT '通知尝试次数。',
  `target_url_hash` CHAR(64) NOT NULL COMMENT '商户通知URL哈希。',
  `http_status` INT NULL COMMENT 'HTTP状态码。',
  `request_header_json_masked` JSON NULL COMMENT '脱敏请求头 JSON。',
  `request_body_json_masked` MEDIUMTEXT NULL COMMENT '脱敏请求体 JSON。',
  `response_body_json_masked` MEDIUMTEXT NULL COMMENT '脱敏商户响应体 JSON。',
  `success` TINYINT NOT NULL DEFAULT 0 COMMENT '通知是否成功。',
  `error_message` VARCHAR(1024) NULL COMMENT '错误摘要。',
  `notify_time` DATETIME(3) NOT NULL COMMENT '通知发起时间。',
  `duration_millis` INT NULL COMMENT '通知耗时毫秒。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notify_log_id` (`notify_log_id`),
  UNIQUE KEY `uk_notify_attempt` (`notify_id`, `attempt_no`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_notify_time` (`notify_id`, `notify_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='保存每一次商户通知请求/响应日志。';

CREATE TABLE IF NOT EXISTS `transaction_merchant_api_interaction_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `api_log_id` VARCHAR(64) NOT NULL COMMENT '商户 API 交互日志唯一标识。',
  `request_id` VARCHAR(64) NOT NULL COMMENT '商户请求唯一号，当前通常等于 orderInfo.orderId。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识，不返回商户。',
  `merchant_id` VARCHAR(64) NOT NULL COMMENT '平台商户号。',
  `merchant_order_no` VARCHAR(128) NOT NULL COMMENT '商户订单号。',
  `merchant_order_id` VARCHAR(128) NULL COMMENT '商户本次 API 请求唯一标识。',
  `api_operation` VARCHAR(64) NOT NULL COMMENT '商户 API 动作，如 AUTHORIZATION、CAPTURE、REFUND。',
  `request_path` VARCHAR(256) NOT NULL COMMENT '商户请求路径。',
  `request_time` DATETIME(3) NOT NULL COMMENT '商户请求进入支付核心的时间。',
  `request_result` VARCHAR(32) NOT NULL COMMENT '请求处理结果，如 SUCCESS、FAILED、PROCESSING。',
  `request_cipher_digest` VARCHAR(128) NULL COMMENT '商户请求密文摘要，使用平台安全指纹，不保存完整密文。',
  `request_cipher_masked` VARCHAR(256) NULL COMMENT '商户请求密文掩码，只保留极短首尾片段用于人工核对。',
  `request_plain_json_masked` MEDIUMTEXT NULL COMMENT '商户请求脱敏明文 JSON。',
  `response_time` DATETIME(3) NULL COMMENT '平台响应生成时间。',
  `response_result` VARCHAR(32) NULL COMMENT '平台响应处理结果。',
  `merchant_response_code` VARCHAR(64) NULL COMMENT '商户侧可见响应码。',
  `merchant_response_message` VARCHAR(512) NULL COMMENT '商户侧可见响应描述。',
  `response_plain_json_masked` MEDIUMTEXT NULL COMMENT '平台响应商户的脱敏明文 JSON。',
  `response_cipher_digest` VARCHAR(128) NULL COMMENT '平台响应密文摘要。',
  `response_cipher_masked` VARCHAR(256) NULL COMMENT '平台响应密文掩码。',
  `duration_millis` INT NULL COMMENT 'OpenAPI 到支付核心处理耗时，单位毫秒。',
  `trace_id` VARCHAR(128) NULL COMMENT '链路追踪 ID。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间，用于分表路由。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时区。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_api_log_id` (`api_log_id`),
  KEY `idx_request_time` (`request_id`, `transaction_date_time`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_operation_time` (`operation_id`, `transaction_date_time`),
  KEY `idx_merchant_order_time` (`merchant_id`, `merchant_order_no`, `transaction_date_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='保存商户 OpenAPI 请求和平台响应的脱敏审计日志。';

CREATE TABLE IF NOT EXISTS `transaction_event_outbox` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `event_no` VARCHAR(64) NOT NULL COMMENT '本地事务事件号。',
  `aggregate_type` VARCHAR(64) NOT NULL COMMENT '聚合类型，如 PAYMENT_TRANSACTION、TRANSACTION_CALLBACK。',
  `aggregate_no` VARCHAR(64) NOT NULL COMMENT '聚合标识，建议使用 transaction_id 或 callback_id。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识。',
  `merchant_id` VARCHAR(64) NULL COMMENT '平台商户号。',
  `merchant_order_no` VARCHAR(128) NULL COMMENT '商户订单号，用于商户侧查询和补偿排查。',
  `transaction_type` VARCHAR(32) NULL COMMENT '交易类型，对齐字典 transaction_type。',
  `event_type` VARCHAR(64) NOT NULL COMMENT '事件类型，如 PAYMENT_CREATED、STATUS_CHANGED、CALLBACK_PROCESSED。',
  `event_status` VARCHAR(32) NOT NULL COMMENT '事件发布状态：INIT、SENT、FAILED、CLOSED。',
  `topic` VARCHAR(128) NOT NULL COMMENT 'RocketMQ Topic。',
  `tag` VARCHAR(128) NULL COMMENT 'RocketMQ Tag。',
  `message_key` VARCHAR(128) NOT NULL COMMENT 'MQ消息Key，下游消费幂等使用。',
  `message_group` VARCHAR(128) NULL COMMENT '顺序消息分组键，如 transaction_id。',
  `payload_json` JSON NOT NULL COMMENT '事件载荷。',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '发布重试次数。',
  `max_retry_count` INT NOT NULL DEFAULT 10 COMMENT '最大重试次数。',
  `next_retry_time` DATETIME(3) NULL COMMENT '下一次发布重试时间。',
  `sent_time` DATETIME(3) NULL COMMENT '投递成功时间。',
  `fail_reason` VARCHAR(512) NULL COMMENT '最近一次投递失败原因。',
  `event_time` DATETIME(3) NOT NULL COMMENT '事件产生时间，只做业务排序和重试扫描条件。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间，最终分表字段。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号。',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标识。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_event_no` (`event_no`),
  UNIQUE KEY `uk_message_key` (`message_key`),
  KEY `idx_event_status_retry` (`event_status`, `next_retry_time`),
  KEY `idx_aggregate` (`aggregate_type`, `aggregate_no`),
  KEY `idx_transaction_event` (`transaction_id`, `transaction_date_time`, `event_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='交易本地事务内写入事件，事务提交后可靠投递 RocketMQ。';

CREATE TABLE IF NOT EXISTS `transaction_abnormal_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理表主键ID。',
  `abnormal_event_id` VARCHAR(64) NOT NULL COMMENT '异常事件ID。',
  `transaction_id` VARCHAR(64) NOT NULL COMMENT '平台当前交易唯一标识。',
  `operation_id` VARCHAR(64) NULL COMMENT '平台内部生命周期关联标识。',
  `abnormal_type` VARCHAR(64) NOT NULL COMMENT '异常类型，如 STATE_CONFLICT、AMOUNT_MISMATCH、CALLBACK_UNHANDLED、CHANNEL_RESULT_MISMATCH。',
  `severity` VARCHAR(32) NOT NULL COMMENT '严重级别：P0、P1、P2、P3。',
  `event_status` VARCHAR(32) NOT NULL COMMENT '异常状态：OPEN、PROCESSING、RESOLVED、IGNORED。',
  `source_table` VARCHAR(128) NULL COMMENT '来源表名。',
  `source_id` VARCHAR(64) NULL COMMENT '来源记录ID。',
  `description` VARCHAR(1024) NULL COMMENT '异常描述。',
  `raw_reference_json` JSON NULL COMMENT '异常排查引用摘要。',
  `first_seen_time` DATETIME(3) NOT NULL COMMENT '首次发现时间。',
  `resolved_time` DATETIME(3) NULL COMMENT '解决时间。',
  `resolved_by` VARCHAR(128) NULL COMMENT '处理人或处理任务。',
  `resolution` VARCHAR(1024) NULL COMMENT '处理结果说明。',
  `transaction_date_time` DATETIME(3) NOT NULL COMMENT '交易业务时间。',
  `transaction_utc_time` DATETIME(3) NOT NULL COMMENT '交易业务时间对应 UTC 时间。',
  `transaction_time_zone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '交易业务时间所属 IANA 时区。',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间。',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_abnormal_event_id` (`abnormal_event_id`),
  KEY `idx_transaction_time` (`transaction_id`, `transaction_date_time`),
  KEY `idx_status_time` (`event_status`, `first_seen_time`),
  KEY `idx_type_time` (`abnormal_type`, `first_seen_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='保存已能定位交易时间的交易异常事件，如状态推进失败、金额校验失败、回调无法处理等。';
