transport {
  type = "TCP"
  server = "NIO"
  heartbeat = true
}

service {
  vgroupMapping.global-payment-dev = "default"
  vgroupMapping.global-payment-test = "default"
  vgroupMapping.global-payment-uat = "default"
  vgroupMapping.global-payment-prod = "default"
}

