<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.scott.payment</groupId>
        <artifactId>component-library</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>
    <artifactId>component-mq</artifactId>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>com.scott.payment</groupId>
            <artifactId>component-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.scott.payment</groupId>
            <artifactId>component-redis</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
        </dependency>
    </dependencies>
</project>

