package com.scott.payment.component.core.iso;

import java.math.BigDecimal;
import java.util.List;

/**
 * @author : scott
 * @version : v1.0.0
 * @classname : IsoStandardData
 * @date : 2026-06-03 16:20
 * @email : scott_x@163.com
 * @description : ISO 3166 国家地区与 ISO 4217 币种基础字典，数据由标准库生成后内置
 * @status : create
 */
final class IsoStandardData {

    /**
     * ISO 3166-1 国家地区基础数据。
     */
    static final List<IsoCountryInfo> COUNTRIES = List.of(
            new IsoCountryInfo("AD", "AND", "020", "Principality of Andorra", "Andorra", "安道尔", "EU", "欧洲", "🇦🇩", "", "", "", "EUR" ),
            new IsoCountryInfo("AE", "ARE", "784", "United Arab Emirates", "United Arab Emirates", "阿拉伯联合酋长国", "AS", "亚洲", "🇦🇪", "ar", "Arabic", "阿拉伯语", "AED" ),
            new IsoCountryInfo("AF", "AFG", "004", "Islamic Republic of Afghanistan", "Afghanistan", "阿富汗", "AS", "亚洲", "🇦🇫", "", "", "", "AFN" ),
            new IsoCountryInfo("AG", "ATG", "028", "Antigua and Barbuda", "Antigua and Barbuda", "安提瓜和巴布达", "NA", "北美洲", "🇦🇬", "", "", "", "XCD" ),
            new IsoCountryInfo("AI", "AIA", "660", "Anguilla", "Anguilla", "安圭拉", "NA", "北美洲", "🇦🇮", "", "", "", "XCD" ),
            new IsoCountryInfo("AL", "ALB", "008", "Republic of Albania", "Albania", "阿尔巴尼亚", "EU", "欧洲", "🇦🇱", "", "", "", "ALL" ),
            new IsoCountryInfo("AM", "ARM", "051", "Republic of Armenia", "Armenia", "亚美尼亚", "AS", "亚洲", "🇦🇲", "", "", "", "AMD" ),
            new IsoCountryInfo("AO", "AGO", "024", "Republic of Angola", "Angola", "安哥拉", "AF", "非洲", "🇦🇴", "", "", "", "AOA" ),
            new IsoCountryInfo("AQ", "ATA", "010", "Antarctica", "Antarctica", "南极洲", "AN", "南极洲", "🇦🇶", "", "", "", "" ),
            new IsoCountryInfo("AR", "ARG", "032", "Argentine Republic", "Argentina", "阿根廷", "SA", "南美洲", "🇦🇷", "es", "Spanish", "西班牙语", "ARS" ),
            new IsoCountryInfo("AS", "ASM", "016", "American Samoa", "American Samoa", "美属萨摩亚", "OC", "大洋洲", "🇦🇸", "", "", "", "USD" ),
            new IsoCountryInfo("AT", "AUT", "040", "Republic of Austria", "Austria", "奥地利", "EU", "欧洲", "🇦🇹", "de", "German", "德语", "EUR" ),
            new IsoCountryInfo("AU", "AUS", "036", "Australia", "Australia", "澳大利亚", "OC", "大洋洲", "🇦🇺", "en", "English", "英语", "AUD" ),
            new IsoCountryInfo("AW", "ABW", "533", "Aruba", "Aruba", "阿鲁巴", "NA", "北美洲", "🇦🇼", "", "", "", "AWG" ),
            new IsoCountryInfo("AX", "ALA", "248", "Åland Islands", "Åland Islands", "奥兰群岛", "EU", "欧洲", "🇦🇽", "", "", "", "EUR" ),
            new IsoCountryInfo("AZ", "AZE", "031", "Republic of Azerbaijan", "Azerbaijan", "阿塞拜疆", "AS", "亚洲", "🇦🇿", "", "", "", "AZN" ),
            new IsoCountryInfo("BA", "BIH", "070", "Republic of Bosnia and Herzegovina", "Bosnia and Herzegovina", "波斯尼亚和黑塞哥维那", "EU", "欧洲", "🇧🇦", "", "", "", "BAM" ),
            new IsoCountryInfo("BB", "BRB", "052", "Barbados", "Barbados", "巴巴多斯", "NA", "北美洲", "🇧🇧", "", "", "", "BBD" ),
            new IsoCountryInfo("BD", "BGD", "050", "People's Republic of Bangladesh", "Bangladesh", "孟加拉国", "AS", "亚洲", "🇧🇩", "bn", "Bengali", "孟加拉语", "BDT" ),
            new IsoCountryInfo("BE", "BEL", "056", "Kingdom of Belgium", "Belgium", "比利时", "EU", "欧洲", "🇧🇪", "nl", "Dutch", "荷兰语", "EUR" ),
            new IsoCountryInfo("BF", "BFA", "854", "Burkina Faso", "Burkina Faso", "布基纳法索", "AF", "非洲", "🇧🇫", "", "", "", "XOF" ),
            new IsoCountryInfo("BG", "BGR", "100", "Republic of Bulgaria", "Bulgaria", "保加利亚", "EU", "欧洲", "🇧🇬", "bg", "Bulgarian", "保加利亚语", "BGN" ),
            new IsoCountryInfo("BH", "BHR", "048", "Kingdom of Bahrain", "Bahrain", "巴林", "AS", "亚洲", "🇧🇭", "ar", "Arabic", "阿拉伯语", "BHD" ),
            new IsoCountryInfo("BI", "BDI", "108", "Republic of Burundi", "Burundi", "布隆迪", "AF", "非洲", "🇧🇮", "", "", "", "BIF" ),
            new IsoCountryInfo("BJ", "BEN", "204", "Republic of Benin", "Benin", "贝宁", "AF", "非洲", "🇧🇯", "", "", "", "XOF" ),
            new IsoCountryInfo("BL", "BLM", "652", "Saint Barthélemy", "Saint Barthélemy", "圣巴泰勒米", "NA", "北美洲", "🇧🇱", "", "", "", "EUR" ),
            new IsoCountryInfo("BM", "BMU", "060", "Bermuda", "Bermuda", "百慕大", "NA", "北美洲", "🇧🇲", "", "", "", "BMD" ),
            new IsoCountryInfo("BN", "BRN", "096", "Brunei Darussalam", "Brunei Darussalam", "文莱", "AS", "亚洲", "🇧🇳", "", "", "", "BND" ),
            new IsoCountryInfo("BO", "BOL", "068", "Plurinational State of Bolivia", "Bolivia, Plurinational State of", "玻利维亚", "SA", "南美洲", "🇧🇴", "", "", "", "BOB" ),
            new IsoCountryInfo("BQ", "BES", "535", "Bonaire, Sint Eustatius and Saba", "Bonaire, Sint Eustatius and Saba", "荷属加勒比区", "NA", "北美洲", "🇧🇶", "", "", "", "USD" ),
            new IsoCountryInfo("BR", "BRA", "076", "Federative Republic of Brazil", "Brazil", "巴西", "SA", "南美洲", "🇧🇷", "pt", "Portuguese", "葡萄牙语", "BRL" ),
            new IsoCountryInfo("BS", "BHS", "044", "Commonwealth of the Bahamas", "Bahamas", "巴哈马", "NA", "北美洲", "🇧🇸", "", "", "", "BSD" ),
            new IsoCountryInfo("BT", "BTN", "064", "Kingdom of Bhutan", "Bhutan", "不丹", "AS", "亚洲", "🇧🇹", "", "", "", "INR" ),
            new IsoCountryInfo("BV", "BVT", "074", "Bouvet Island", "Bouvet Island", "布韦岛", "AN", "南极洲", "🇧🇻", "", "", "", "NOK" ),
            new IsoCountryInfo("BW", "BWA", "072", "Republic of Botswana", "Botswana", "博茨瓦纳", "AF", "非洲", "🇧🇼", "", "", "", "BWP" ),
            new IsoCountryInfo("BY", "BLR", "112", "Republic of Belarus", "Belarus", "白俄罗斯", "EU", "欧洲", "🇧🇾", "", "", "", "BYN" ),
            new IsoCountryInfo("BZ", "BLZ", "084", "Belize", "Belize", "伯利兹", "NA", "北美洲", "🇧🇿", "", "", "", "BZD" ),
            new IsoCountryInfo("CA", "CAN", "124", "Canada", "Canada", "加拿大", "NA", "北美洲", "🇨🇦", "en", "English", "英语", "CAD" ),
            new IsoCountryInfo("CC", "CCK", "166", "Cocos (Keeling) Islands", "Cocos (Keeling) Islands", "科科斯（基林）群岛", "AS", "亚洲", "🇨🇨", "", "", "", "AUD" ),
            new IsoCountryInfo("CD", "COD", "180", "Congo, The Democratic Republic of the", "Congo, The Democratic Republic of the", "刚果（金）", "AF", "非洲", "🇨🇩", "", "", "", "CDF" ),
            new IsoCountryInfo("CF", "CAF", "140", "Central African Republic", "Central African Republic", "中非共和国", "AF", "非洲", "🇨🇫", "", "", "", "XAF" ),
            new IsoCountryInfo("CG", "COG", "178", "Republic of the Congo", "Congo", "刚果（布）", "AF", "非洲", "🇨🇬", "", "", "", "XAF" ),
            new IsoCountryInfo("CH", "CHE", "756", "Swiss Confederation", "Switzerland", "瑞士", "EU", "欧洲", "🇨🇭", "de", "German", "德语", "CHF" ),
            new IsoCountryInfo("CI", "CIV", "384", "Republic of Côte d'Ivoire", "Côte d'Ivoire", "科特迪瓦", "AF", "非洲", "🇨🇮", "", "", "", "XOF" ),
            new IsoCountryInfo("CK", "COK", "184", "Cook Islands", "Cook Islands", "库克群岛", "OC", "大洋洲", "🇨🇰", "", "", "", "NZD" ),
            new IsoCountryInfo("CL", "CHL", "152", "Republic of Chile", "Chile", "智利", "SA", "南美洲", "🇨🇱", "es", "Spanish", "西班牙语", "CLP" ),
            new IsoCountryInfo("CM", "CMR", "120", "Republic of Cameroon", "Cameroon", "喀麦隆", "AF", "非洲", "🇨🇲", "", "", "", "XAF" ),
            new IsoCountryInfo("CN", "CHN", "156", "People's Republic of China", "China", "中国", "AS", "亚洲", "🇨🇳", "zh", "Chinese", "中文", "CNY" ),
            new IsoCountryInfo("CO", "COL", "170", "Republic of Colombia", "Colombia", "哥伦比亚", "SA", "南美洲", "🇨🇴", "es", "Spanish", "西班牙语", "COP" ),
            new IsoCountryInfo("CR", "CRI", "188", "Republic of Costa Rica", "Costa Rica", "哥斯达黎加", "NA", "北美洲", "🇨🇷", "", "", "", "CRC" ),
            new IsoCountryInfo("CU", "CUB", "192", "Republic of Cuba", "Cuba", "古巴", "NA", "北美洲", "🇨🇺", "", "", "", "CUP" ),
            new IsoCountryInfo("CV", "CPV", "132", "Republic of Cabo Verde", "Cabo Verde", "佛得角", "AF", "非洲", "🇨🇻", "", "", "", "CVE" ),
            new IsoCountryInfo("CW", "CUW", "531", "Curaçao", "Curaçao", "库拉索", "NA", "北美洲", "🇨🇼", "", "", "", "XCG" ),
            new IsoCountryInfo("CX", "CXR", "162", "Christmas Island", "Christmas Island", "圣诞岛", "AS", "亚洲", "🇨🇽", "", "", "", "AUD" ),
            new IsoCountryInfo("CY", "CYP", "196", "Republic of Cyprus", "Cyprus", "塞浦路斯", "EU", "欧洲", "🇨🇾", "", "", "", "EUR" ),
            new IsoCountryInfo("CZ", "CZE", "203", "Czech Republic", "Czechia", "捷克", "EU", "欧洲", "🇨🇿", "cs", "Czech", "捷克语", "CZK" ),
            new IsoCountryInfo("DE", "DEU", "276", "Federal Republic of Germany", "Germany", "德国", "EU", "欧洲", "🇩🇪", "de", "German", "德语", "EUR" ),
            new IsoCountryInfo("DJ", "DJI", "262", "Republic of Djibouti", "Djibouti", "吉布提", "AF", "非洲", "🇩🇯", "", "", "", "DJF" ),
            new IsoCountryInfo("DK", "DNK", "208", "Kingdom of Denmark", "Denmark", "丹麦", "EU", "欧洲", "🇩🇰", "da", "Danish", "丹麦语", "DKK" ),
            new IsoCountryInfo("DM", "DMA", "212", "Commonwealth of Dominica", "Dominica", "多米尼克", "NA", "北美洲", "🇩🇲", "", "", "", "XCD" ),
            new IsoCountryInfo("DO", "DOM", "214", "Dominican Republic", "Dominican Republic", "多米尼加共和国", "NA", "北美洲", "🇩🇴", "", "", "", "DOP" ),
            new IsoCountryInfo("DZ", "DZA", "012", "People's Democratic Republic of Algeria", "Algeria", "阿尔及利亚", "AF", "非洲", "🇩🇿", "", "", "", "DZD" ),
            new IsoCountryInfo("EC", "ECU", "218", "Republic of Ecuador", "Ecuador", "厄瓜多尔", "SA", "南美洲", "🇪🇨", "", "", "", "USD" ),
            new IsoCountryInfo("EE", "EST", "233", "Republic of Estonia", "Estonia", "爱沙尼亚", "EU", "欧洲", "🇪🇪", "", "", "", "EUR" ),
            new IsoCountryInfo("EG", "EGY", "818", "Arab Republic of Egypt", "Egypt", "埃及", "AF", "非洲", "🇪🇬", "ar", "Arabic", "阿拉伯语", "EGP" ),
            new IsoCountryInfo("EH", "ESH", "732", "Western Sahara", "Western Sahara", "西撒哈拉", "AF", "非洲", "🇪🇭", "", "", "", "MAD" ),
            new IsoCountryInfo("ER", "ERI", "232", "the State of Eritrea", "Eritrea", "厄立特里亚", "AF", "非洲", "🇪🇷", "", "", "", "ERN" ),
            new IsoCountryInfo("ES", "ESP", "724", "Kingdom of Spain", "Spain", "西班牙", "EU", "欧洲", "🇪🇸", "es", "Spanish", "西班牙语", "EUR" ),
            new IsoCountryInfo("ET", "ETH", "231", "Federal Democratic Republic of Ethiopia", "Ethiopia", "埃塞俄比亚", "AF", "非洲", "🇪🇹", "", "", "", "ETB" ),
            new IsoCountryInfo("FI", "FIN", "246", "Republic of Finland", "Finland", "芬兰", "EU", "欧洲", "🇫🇮", "fi", "Finnish", "芬兰语", "EUR" ),
            new IsoCountryInfo("FJ", "FJI", "242", "Republic of Fiji", "Fiji", "斐济", "OC", "大洋洲", "🇫🇯", "", "", "", "FJD" ),
            new IsoCountryInfo("FK", "FLK", "238", "Falkland Islands (Malvinas)", "Falkland Islands (Malvinas)", "福克兰群岛", "SA", "南美洲", "🇫🇰", "", "", "", "FKP" ),
            new IsoCountryInfo("FM", "FSM", "583", "Federated States of Micronesia", "Micronesia, Federated States of", "密克罗尼西亚", "OC", "大洋洲", "🇫🇲", "", "", "", "USD" ),
            new IsoCountryInfo("FO", "FRO", "234", "Faroe Islands", "Faroe Islands", "法罗群岛", "EU", "欧洲", "🇫🇴", "", "", "", "DKK" ),
            new IsoCountryInfo("FR", "FRA", "250", "French Republic", "France", "法国", "EU", "欧洲", "🇫🇷", "fr", "French", "法语", "EUR" ),
            new IsoCountryInfo("GA", "GAB", "266", "Gabonese Republic", "Gabon", "加蓬", "AF", "非洲", "🇬🇦", "", "", "", "XAF" ),
            new IsoCountryInfo("GB", "GBR", "826", "United Kingdom of Great Britain and Northern Ireland", "United Kingdom", "英国", "EU", "欧洲", "🇬🇧", "en", "English", "英语", "GBP" ),
            new IsoCountryInfo("GD", "GRD", "308", "Grenada", "Grenada", "格林纳达", "NA", "北美洲", "🇬🇩", "", "", "", "XCD" ),
            new IsoCountryInfo("GE", "GEO", "268", "Georgia", "Georgia", "格鲁吉亚", "AS", "亚洲", "🇬🇪", "", "", "", "GEL" ),
            new IsoCountryInfo("GF", "GUF", "254", "French Guiana", "French Guiana", "法属圭亚那", "SA", "南美洲", "🇬🇫", "", "", "", "EUR" ),
            new IsoCountryInfo("GG", "GGY", "831", "Guernsey", "Guernsey", "根西岛", "EU", "欧洲", "🇬🇬", "", "", "", "GBP" ),
            new IsoCountryInfo("GH", "GHA", "288", "Republic of Ghana", "Ghana", "加纳", "AF", "非洲", "🇬🇭", "", "", "", "GHS" ),
            new IsoCountryInfo("GI", "GIB", "292", "Gibraltar", "Gibraltar", "直布罗陀", "EU", "欧洲", "🇬🇮", "", "", "", "GIP" ),
            new IsoCountryInfo("GL", "GRL", "304", "Greenland", "Greenland", "格陵兰", "NA", "北美洲", "🇬🇱", "", "", "", "DKK" ),
            new IsoCountryInfo("GM", "GMB", "270", "Republic of the Gambia", "Gambia", "冈比亚", "AF", "非洲", "🇬🇲", "", "", "", "GMD" ),
            new IsoCountryInfo("GN", "GIN", "324", "Republic of Guinea", "Guinea", "几内亚", "AF", "非洲", "🇬🇳", "", "", "", "GNF" ),
            new IsoCountryInfo("GP", "GLP", "312", "Guadeloupe", "Guadeloupe", "瓜德罗普", "NA", "北美洲", "🇬🇵", "", "", "", "EUR" ),
            new IsoCountryInfo("GQ", "GNQ", "226", "Republic of Equatorial Guinea", "Equatorial Guinea", "赤道几内亚", "AF", "非洲", "🇬🇶", "", "", "", "XAF" ),
            new IsoCountryInfo("GR", "GRC", "300", "Hellenic Republic", "Greece", "希腊", "EU", "欧洲", "🇬🇷", "el", "Greek", "希腊语", "EUR" ),
            new IsoCountryInfo("GS", "SGS", "239", "South Georgia and the South Sandwich Islands", "South Georgia and the South Sandwich Islands", "南乔治亚和南桑威奇群岛", "SA", "南美洲", "🇬🇸", "", "", "", "GBP" ),
            new IsoCountryInfo("GT", "GTM", "320", "Republic of Guatemala", "Guatemala", "危地马拉", "NA", "北美洲", "🇬🇹", "", "", "", "GTQ" ),
            new IsoCountryInfo("GU", "GUM", "316", "Guam", "Guam", "关岛", "OC", "大洋洲", "🇬🇺", "", "", "", "USD" ),
            new IsoCountryInfo("GW", "GNB", "624", "Republic of Guinea-Bissau", "Guinea-Bissau", "几内亚比绍", "AF", "非洲", "🇬🇼", "", "", "", "XOF" ),
            new IsoCountryInfo("GY", "GUY", "328", "Republic of Guyana", "Guyana", "圭亚那", "SA", "南美洲", "🇬🇾", "", "", "", "GYD" ),
            new IsoCountryInfo("HK", "HKG", "344", "Hong Kong Special Administrative Region of China", "Hong Kong", "中国香港特别行政区", "AS", "亚洲", "🇭🇰", "zh", "Chinese", "中文", "HKD" ),
            new IsoCountryInfo("HM", "HMD", "334", "Heard Island and McDonald Islands", "Heard Island and McDonald Islands", "赫德岛和麦克唐纳群岛", "AN", "南极洲", "🇭🇲", "", "", "", "AUD" ),
            new IsoCountryInfo("HN", "HND", "340", "Republic of Honduras", "Honduras", "洪都拉斯", "NA", "北美洲", "🇭🇳", "", "", "", "HNL" ),
            new IsoCountryInfo("HR", "HRV", "191", "Republic of Croatia", "Croatia", "克罗地亚", "EU", "欧洲", "🇭🇷", "", "", "", "EUR" ),
            new IsoCountryInfo("HT", "HTI", "332", "Republic of Haiti", "Haiti", "海地", "NA", "北美洲", "🇭🇹", "", "", "", "HTG" ),
            new IsoCountryInfo("HU", "HUN", "348", "Hungary", "Hungary", "匈牙利", "EU", "欧洲", "🇭🇺", "hu", "Hungarian", "匈牙利语", "HUF" ),
            new IsoCountryInfo("ID", "IDN", "360", "Republic of Indonesia", "Indonesia", "印度尼西亚", "AS", "亚洲", "🇮🇩", "id", "Indonesian", "印尼语", "IDR" ),
            new IsoCountryInfo("IE", "IRL", "372", "Ireland", "Ireland", "爱尔兰", "EU", "欧洲", "🇮🇪", "en", "English", "英语", "EUR" ),
            new IsoCountryInfo("IL", "ISR", "376", "State of Israel", "Israel", "以色列", "AS", "亚洲", "🇮🇱", "he", "Hebrew", "希伯来语", "ILS" ),
            new IsoCountryInfo("IM", "IMN", "833", "Isle of Man", "Isle of Man", "马恩岛", "EU", "欧洲", "🇮🇲", "", "", "", "GBP" ),
            new IsoCountryInfo("IN", "IND", "356", "Republic of India", "India", "印度", "AS", "亚洲", "🇮🇳", "hi", "Hindi", "印地语", "INR" ),
            new IsoCountryInfo("IO", "IOT", "086", "British Indian Ocean Territory", "British Indian Ocean Territory", "英属印度洋领地", "AS", "亚洲", "🇮🇴", "", "", "", "USD" ),
            new IsoCountryInfo("IQ", "IRQ", "368", "Republic of Iraq", "Iraq", "伊拉克", "AS", "亚洲", "🇮🇶", "", "", "", "IQD" ),
            new IsoCountryInfo("IR", "IRN", "364", "Islamic Republic of Iran", "Iran, Islamic Republic of", "伊朗", "AS", "亚洲", "🇮🇷", "", "", "", "IRR" ),
            new IsoCountryInfo("IS", "ISL", "352", "Republic of Iceland", "Iceland", "冰岛", "EU", "欧洲", "🇮🇸", "", "", "", "ISK" ),
            new IsoCountryInfo("IT", "ITA", "380", "Italian Republic", "Italy", "意大利", "EU", "欧洲", "🇮🇹", "it", "Italian", "意大利语", "EUR" ),
            new IsoCountryInfo("JE", "JEY", "832", "Jersey", "Jersey", "泽西岛", "EU", "欧洲", "🇯🇪", "", "", "", "GBP" ),
            new IsoCountryInfo("JM", "JAM", "388", "Jamaica", "Jamaica", "牙买加", "NA", "北美洲", "🇯🇲", "", "", "", "JMD" ),
            new IsoCountryInfo("JO", "JOR", "400", "Hashemite Kingdom of Jordan", "Jordan", "约旦", "AS", "亚洲", "🇯🇴", "", "", "", "JOD" ),
            new IsoCountryInfo("JP", "JPN", "392", "Japan", "Japan", "日本", "AS", "亚洲", "🇯🇵", "ja", "Japanese", "日语", "JPY" ),
            new IsoCountryInfo("KE", "KEN", "404", "Republic of Kenya", "Kenya", "肯尼亚", "AF", "非洲", "🇰🇪", "sw", "Swahili", "斯瓦希里语", "KES" ),
            new IsoCountryInfo("KG", "KGZ", "417", "Kyrgyz Republic", "Kyrgyzstan", "吉尔吉斯斯坦", "AS", "亚洲", "🇰🇬", "", "", "", "KGS" ),
            new IsoCountryInfo("KH", "KHM", "116", "Kingdom of Cambodia", "Cambodia", "柬埔寨", "AS", "亚洲", "🇰🇭", "", "", "", "KHR" ),
            new IsoCountryInfo("KI", "KIR", "296", "Republic of Kiribati", "Kiribati", "基里巴斯", "OC", "大洋洲", "🇰🇮", "", "", "", "AUD" ),
            new IsoCountryInfo("KM", "COM", "174", "Union of the Comoros", "Comoros", "科摩罗", "AF", "非洲", "🇰🇲", "", "", "", "KMF" ),
            new IsoCountryInfo("KN", "KNA", "659", "Saint Kitts and Nevis", "Saint Kitts and Nevis", "圣基茨和尼维斯", "NA", "北美洲", "🇰🇳", "", "", "", "XCD" ),
            new IsoCountryInfo("KP", "PRK", "408", "Democratic People's Republic of Korea", "Korea, Democratic People's Republic of", "朝鲜", "AS", "亚洲", "🇰🇵", "", "", "", "KPW" ),
            new IsoCountryInfo("KR", "KOR", "410", "Korea, Republic of", "Korea, Republic of", "韩国", "AS", "亚洲", "🇰🇷", "ko", "Korean", "韩语", "KRW" ),
            new IsoCountryInfo("KW", "KWT", "414", "State of Kuwait", "Kuwait", "科威特", "AS", "亚洲", "🇰🇼", "ar", "Arabic", "阿拉伯语", "KWD" ),
            new IsoCountryInfo("KY", "CYM", "136", "Cayman Islands", "Cayman Islands", "开曼群岛", "NA", "北美洲", "🇰🇾", "", "", "", "KYD" ),
            new IsoCountryInfo("KZ", "KAZ", "398", "Republic of Kazakhstan", "Kazakhstan", "哈萨克斯坦", "AS", "亚洲", "🇰🇿", "", "", "", "KZT" ),
            new IsoCountryInfo("LA", "LAO", "418", "Lao People's Democratic Republic", "Lao People's Democratic Republic", "老挝", "AS", "亚洲", "🇱🇦", "", "", "", "LAK" ),
            new IsoCountryInfo("LB", "LBN", "422", "Lebanese Republic", "Lebanon", "黎巴嫩", "AS", "亚洲", "🇱🇧", "", "", "", "LBP" ),
            new IsoCountryInfo("LC", "LCA", "662", "Saint Lucia", "Saint Lucia", "圣卢西亚", "NA", "北美洲", "🇱🇨", "", "", "", "XCD" ),
            new IsoCountryInfo("LI", "LIE", "438", "Principality of Liechtenstein", "Liechtenstein", "列支敦士登", "EU", "欧洲", "🇱🇮", "", "", "", "CHF" ),
            new IsoCountryInfo("LK", "LKA", "144", "Democratic Socialist Republic of Sri Lanka", "Sri Lanka", "斯里兰卡", "AS", "亚洲", "🇱🇰", "", "", "", "LKR" ),
            new IsoCountryInfo("LR", "LBR", "430", "Republic of Liberia", "Liberia", "利比里亚", "AF", "非洲", "🇱🇷", "", "", "", "LRD" ),
            new IsoCountryInfo("LS", "LSO", "426", "Kingdom of Lesotho", "Lesotho", "莱索托", "AF", "非洲", "🇱🇸", "", "", "", "ZAR" ),
            new IsoCountryInfo("LT", "LTU", "440", "Republic of Lithuania", "Lithuania", "立陶宛", "EU", "欧洲", "🇱🇹", "", "", "", "EUR" ),
            new IsoCountryInfo("LU", "LUX", "442", "Grand Duchy of Luxembourg", "Luxembourg", "卢森堡", "EU", "欧洲", "🇱🇺", "", "", "", "EUR" ),
            new IsoCountryInfo("LV", "LVA", "428", "Republic of Latvia", "Latvia", "拉脱维亚", "EU", "欧洲", "🇱🇻", "", "", "", "EUR" ),
            new IsoCountryInfo("LY", "LBY", "434", "Libya", "Libya", "利比亚", "AF", "非洲", "🇱🇾", "", "", "", "LYD" ),
            new IsoCountryInfo("MA", "MAR", "504", "Kingdom of Morocco", "Morocco", "摩洛哥", "AF", "非洲", "🇲🇦", "", "", "", "MAD" ),
            new IsoCountryInfo("MC", "MCO", "492", "Principality of Monaco", "Monaco", "摩纳哥", "EU", "欧洲", "🇲🇨", "", "", "", "EUR" ),
            new IsoCountryInfo("MD", "MDA", "498", "Republic of Moldova", "Moldova, Republic of", "摩尔多瓦", "EU", "欧洲", "🇲🇩", "", "", "", "MDL" ),
            new IsoCountryInfo("ME", "MNE", "499", "Montenegro", "Montenegro", "黑山", "EU", "欧洲", "🇲🇪", "", "", "", "EUR" ),
            new IsoCountryInfo("MF", "MAF", "663", "Saint Martin (French part)", "Saint Martin (French part)", "法属圣马丁", "NA", "北美洲", "🇲🇫", "", "", "", "EUR" ),
            new IsoCountryInfo("MG", "MDG", "450", "Republic of Madagascar", "Madagascar", "马达加斯加", "AF", "非洲", "🇲🇬", "", "", "", "MGA" ),
            new IsoCountryInfo("MH", "MHL", "584", "Republic of the Marshall Islands", "Marshall Islands", "马绍尔群岛", "OC", "大洋洲", "🇲🇭", "", "", "", "USD" ),
            new IsoCountryInfo("MK", "MKD", "807", "Republic of North Macedonia", "North Macedonia", "北马其顿", "EU", "欧洲", "🇲🇰", "", "", "", "MKD" ),
            new IsoCountryInfo("ML", "MLI", "466", "Republic of Mali", "Mali", "马里", "AF", "非洲", "🇲🇱", "", "", "", "XOF" ),
            new IsoCountryInfo("MM", "MMR", "104", "Republic of Myanmar", "Myanmar", "缅甸", "AS", "亚洲", "🇲🇲", "", "", "", "MMK" ),
            new IsoCountryInfo("MN", "MNG", "496", "Mongolia", "Mongolia", "蒙古", "AS", "亚洲", "🇲🇳", "", "", "", "MNT" ),
            new IsoCountryInfo("MO", "MAC", "446", "Macao Special Administrative Region of China", "Macao", "中国澳门特别行政区", "AS", "亚洲", "🇲🇴", "zh", "Chinese", "中文", "MOP" ),
            new IsoCountryInfo("MP", "MNP", "580", "Commonwealth of the Northern Mariana Islands", "Northern Mariana Islands", "北马里亚纳群岛", "OC", "大洋洲", "🇲🇵", "", "", "", "USD" ),
            new IsoCountryInfo("MQ", "MTQ", "474", "Martinique", "Martinique", "马提尼克", "NA", "北美洲", "🇲🇶", "", "", "", "EUR" ),
            new IsoCountryInfo("MR", "MRT", "478", "Islamic Republic of Mauritania", "Mauritania", "毛里塔尼亚", "AF", "非洲", "🇲🇷", "", "", "", "MRU" ),
            new IsoCountryInfo("MS", "MSR", "500", "Montserrat", "Montserrat", "蒙特塞拉特", "NA", "北美洲", "🇲🇸", "", "", "", "XCD" ),
            new IsoCountryInfo("MT", "MLT", "470", "Republic of Malta", "Malta", "马耳他", "EU", "欧洲", "🇲🇹", "", "", "", "EUR" ),
            new IsoCountryInfo("MU", "MUS", "480", "Republic of Mauritius", "Mauritius", "毛里求斯", "AF", "非洲", "🇲🇺", "", "", "", "MUR" ),
            new IsoCountryInfo("MV", "MDV", "462", "Republic of Maldives", "Maldives", "马尔代夫", "AS", "亚洲", "🇲🇻", "", "", "", "MVR" ),
            new IsoCountryInfo("MW", "MWI", "454", "Republic of Malawi", "Malawi", "马拉维", "AF", "非洲", "🇲🇼", "", "", "", "MWK" ),
            new IsoCountryInfo("MX", "MEX", "484", "United Mexican States", "Mexico", "墨西哥", "NA", "北美洲", "🇲🇽", "es", "Spanish", "西班牙语", "MXN" ),
            new IsoCountryInfo("MY", "MYS", "458", "Malaysia", "Malaysia", "马来西亚", "AS", "亚洲", "🇲🇾", "ms", "Malay", "马来语", "MYR" ),
            new IsoCountryInfo("MZ", "MOZ", "508", "Republic of Mozambique", "Mozambique", "莫桑比克", "AF", "非洲", "🇲🇿", "", "", "", "MZN" ),
            new IsoCountryInfo("NA", "NAM", "516", "Republic of Namibia", "Namibia", "纳米比亚", "AF", "非洲", "🇳🇦", "", "", "", "ZAR" ),
            new IsoCountryInfo("NC", "NCL", "540", "New Caledonia", "New Caledonia", "新喀里多尼亚", "OC", "大洋洲", "🇳🇨", "", "", "", "XPF" ),
            new IsoCountryInfo("NE", "NER", "562", "Republic of the Niger", "Niger", "尼日尔", "AF", "非洲", "🇳🇪", "", "", "", "XOF" ),
            new IsoCountryInfo("NF", "NFK", "574", "Norfolk Island", "Norfolk Island", "诺福克岛", "OC", "大洋洲", "🇳🇫", "", "", "", "AUD" ),
            new IsoCountryInfo("NG", "NGA", "566", "Federal Republic of Nigeria", "Nigeria", "尼日利亚", "AF", "非洲", "🇳🇬", "en", "English", "英语", "NGN" ),
            new IsoCountryInfo("NI", "NIC", "558", "Republic of Nicaragua", "Nicaragua", "尼加拉瓜", "NA", "北美洲", "🇳🇮", "", "", "", "NIO" ),
            new IsoCountryInfo("NL", "NLD", "528", "Kingdom of the Netherlands", "Netherlands", "荷兰", "EU", "欧洲", "🇳🇱", "nl", "Dutch", "荷兰语", "EUR" ),
            new IsoCountryInfo("NO", "NOR", "578", "Kingdom of Norway", "Norway", "挪威", "EU", "欧洲", "🇳🇴", "no", "Norwegian", "挪威语", "NOK" ),
            new IsoCountryInfo("NP", "NPL", "524", "Federal Democratic Republic of Nepal", "Nepal", "尼泊尔", "AS", "亚洲", "🇳🇵", "", "", "", "NPR" ),
            new IsoCountryInfo("NR", "NRU", "520", "Republic of Nauru", "Nauru", "瑙鲁", "OC", "大洋洲", "🇳🇷", "", "", "", "AUD" ),
            new IsoCountryInfo("NU", "NIU", "570", "Niue", "Niue", "纽埃", "OC", "大洋洲", "🇳🇺", "", "", "", "NZD" ),
            new IsoCountryInfo("NZ", "NZL", "554", "New Zealand", "New Zealand", "新西兰", "OC", "大洋洲", "🇳🇿", "en", "English", "英语", "NZD" ),
            new IsoCountryInfo("OM", "OMN", "512", "Sultanate of Oman", "Oman", "阿曼", "AS", "亚洲", "🇴🇲", "", "", "", "OMR" ),
            new IsoCountryInfo("PA", "PAN", "591", "Republic of Panama", "Panama", "巴拿马", "NA", "北美洲", "🇵🇦", "", "", "", "PAB" ),
            new IsoCountryInfo("PE", "PER", "604", "Republic of Peru", "Peru", "秘鲁", "SA", "南美洲", "🇵🇪", "es", "Spanish", "西班牙语", "PEN" ),
            new IsoCountryInfo("PF", "PYF", "258", "French Polynesia", "French Polynesia", "法属波利尼西亚", "OC", "大洋洲", "🇵🇫", "", "", "", "XPF" ),
            new IsoCountryInfo("PG", "PNG", "598", "Independent State of Papua New Guinea", "Papua New Guinea", "巴布亚新几内亚", "OC", "大洋洲", "🇵🇬", "", "", "", "PGK" ),
            new IsoCountryInfo("PH", "PHL", "608", "Republic of the Philippines", "Philippines", "菲律宾", "AS", "亚洲", "🇵🇭", "fil", "Filipino", "菲律宾语", "PHP" ),
            new IsoCountryInfo("PK", "PAK", "586", "Islamic Republic of Pakistan", "Pakistan", "巴基斯坦", "AS", "亚洲", "🇵🇰", "ur", "Urdu", "乌尔都语", "PKR" ),
            new IsoCountryInfo("PL", "POL", "616", "Republic of Poland", "Poland", "波兰", "EU", "欧洲", "🇵🇱", "pl", "Polish", "波兰语", "PLN" ),
            new IsoCountryInfo("PM", "SPM", "666", "Saint Pierre and Miquelon", "Saint Pierre and Miquelon", "圣皮埃尔和密克隆群岛", "NA", "北美洲", "🇵🇲", "", "", "", "EUR" ),
            new IsoCountryInfo("PN", "PCN", "612", "Pitcairn", "Pitcairn", "皮特凯恩群岛", "OC", "大洋洲", "🇵🇳", "", "", "", "NZD" ),
            new IsoCountryInfo("PR", "PRI", "630", "Puerto Rico", "Puerto Rico", "波多黎各", "NA", "北美洲", "🇵🇷", "", "", "", "USD" ),
            new IsoCountryInfo("PS", "PSE", "275", "the State of Palestine", "Palestine, State of", "巴勒斯坦领土", "AS", "亚洲", "🇵🇸", "", "", "", "ILS" ),
            new IsoCountryInfo("PT", "PRT", "620", "Portuguese Republic", "Portugal", "葡萄牙", "EU", "欧洲", "🇵🇹", "pt", "Portuguese", "葡萄牙语", "EUR" ),
            new IsoCountryInfo("PW", "PLW", "585", "Republic of Palau", "Palau", "帕劳", "OC", "大洋洲", "🇵🇼", "", "", "", "USD" ),
            new IsoCountryInfo("PY", "PRY", "600", "Republic of Paraguay", "Paraguay", "巴拉圭", "SA", "南美洲", "🇵🇾", "", "", "", "PYG" ),
            new IsoCountryInfo("QA", "QAT", "634", "State of Qatar", "Qatar", "卡塔尔", "AS", "亚洲", "🇶🇦", "ar", "Arabic", "阿拉伯语", "QAR" ),
            new IsoCountryInfo("RE", "REU", "638", "Réunion", "Réunion", "留尼汪", "AF", "非洲", "🇷🇪", "", "", "", "EUR" ),
            new IsoCountryInfo("RO", "ROU", "642", "Romania", "Romania", "罗马尼亚", "EU", "欧洲", "🇷🇴", "ro", "Romanian", "罗马尼亚语", "RON" ),
            new IsoCountryInfo("RS", "SRB", "688", "Republic of Serbia", "Serbia", "塞尔维亚", "EU", "欧洲", "🇷🇸", "", "", "", "RSD" ),
            new IsoCountryInfo("RU", "RUS", "643", "Russian Federation", "Russian Federation", "俄罗斯", "EU", "欧洲", "🇷🇺", "ru", "Russian", "俄语", "RUB" ),
            new IsoCountryInfo("RW", "RWA", "646", "Rwandese Republic", "Rwanda", "卢旺达", "AF", "非洲", "🇷🇼", "", "", "", "RWF" ),
            new IsoCountryInfo("SA", "SAU", "682", "Kingdom of Saudi Arabia", "Saudi Arabia", "沙特阿拉伯", "AS", "亚洲", "🇸🇦", "ar", "Arabic", "阿拉伯语", "SAR" ),
            new IsoCountryInfo("SB", "SLB", "090", "Solomon Islands", "Solomon Islands", "所罗门群岛", "OC", "大洋洲", "🇸🇧", "", "", "", "SBD" ),
            new IsoCountryInfo("SC", "SYC", "690", "Republic of Seychelles", "Seychelles", "塞舌尔", "AF", "非洲", "🇸🇨", "", "", "", "SCR" ),
            new IsoCountryInfo("SD", "SDN", "729", "Republic of the Sudan", "Sudan", "苏丹", "AF", "非洲", "🇸🇩", "", "", "", "SDG" ),
            new IsoCountryInfo("SE", "SWE", "752", "Kingdom of Sweden", "Sweden", "瑞典", "EU", "欧洲", "🇸🇪", "sv", "Swedish", "瑞典语", "SEK" ),
            new IsoCountryInfo("SG", "SGP", "702", "Republic of Singapore", "Singapore", "新加坡", "AS", "亚洲", "🇸🇬", "en", "English", "英语", "SGD" ),
            new IsoCountryInfo("SH", "SHN", "654", "Saint Helena, Ascension and Tristan da Cunha", "Saint Helena, Ascension and Tristan da Cunha", "圣赫勒拿", "AF", "非洲", "🇸🇭", "", "", "", "SHP" ),
            new IsoCountryInfo("SI", "SVN", "705", "Republic of Slovenia", "Slovenia", "斯洛文尼亚", "EU", "欧洲", "🇸🇮", "", "", "", "EUR" ),
            new IsoCountryInfo("SJ", "SJM", "744", "Svalbard and Jan Mayen", "Svalbard and Jan Mayen", "斯瓦尔巴和扬马延", "EU", "欧洲", "🇸🇯", "", "", "", "NOK" ),
            new IsoCountryInfo("SK", "SVK", "703", "Slovak Republic", "Slovakia", "斯洛伐克", "EU", "欧洲", "🇸🇰", "sk", "Slovak", "斯洛伐克语", "EUR" ),
            new IsoCountryInfo("SL", "SLE", "694", "Republic of Sierra Leone", "Sierra Leone", "塞拉利昂", "AF", "非洲", "🇸🇱", "", "", "", "SLE" ),
            new IsoCountryInfo("SM", "SMR", "674", "Republic of San Marino", "San Marino", "圣马力诺", "EU", "欧洲", "🇸🇲", "", "", "", "EUR" ),
            new IsoCountryInfo("SN", "SEN", "686", "Republic of Senegal", "Senegal", "塞内加尔", "AF", "非洲", "🇸🇳", "", "", "", "XOF" ),
            new IsoCountryInfo("SO", "SOM", "706", "Federal Republic of Somalia", "Somalia", "索马里", "AF", "非洲", "🇸🇴", "", "", "", "SOS" ),
            new IsoCountryInfo("SR", "SUR", "740", "Republic of Suriname", "Suriname", "苏里南", "SA", "南美洲", "🇸🇷", "", "", "", "SRD" ),
            new IsoCountryInfo("SS", "SSD", "728", "Republic of South Sudan", "South Sudan", "南苏丹", "AF", "非洲", "🇸🇸", "", "", "", "SSP" ),
            new IsoCountryInfo("ST", "STP", "678", "Democratic Republic of Sao Tome and Principe", "Sao Tome and Principe", "圣多美和普林西比", "AF", "非洲", "🇸🇹", "", "", "", "STN" ),
            new IsoCountryInfo("SV", "SLV", "222", "Republic of El Salvador", "El Salvador", "萨尔瓦多", "NA", "北美洲", "🇸🇻", "", "", "", "USD" ),
            new IsoCountryInfo("SX", "SXM", "534", "Sint Maarten (Dutch part)", "Sint Maarten (Dutch part)", "荷属圣马丁", "NA", "北美洲", "🇸🇽", "", "", "", "XCG" ),
            new IsoCountryInfo("SY", "SYR", "760", "Syrian Arab Republic", "Syrian Arab Republic", "叙利亚", "AS", "亚洲", "🇸🇾", "", "", "", "SYP" ),
            new IsoCountryInfo("SZ", "SWZ", "748", "Kingdom of Eswatini", "Eswatini", "斯威士兰", "AF", "非洲", "🇸🇿", "", "", "", "SZL" ),
            new IsoCountryInfo("TC", "TCA", "796", "Turks and Caicos Islands", "Turks and Caicos Islands", "特克斯和凯科斯群岛", "NA", "北美洲", "🇹🇨", "", "", "", "USD" ),
            new IsoCountryInfo("TD", "TCD", "148", "Republic of Chad", "Chad", "乍得", "AF", "非洲", "🇹🇩", "", "", "", "XAF" ),
            new IsoCountryInfo("TF", "ATF", "260", "French Southern Territories", "French Southern Territories", "法属南部领地", "AN", "南极洲", "🇹🇫", "", "", "", "EUR" ),
            new IsoCountryInfo("TG", "TGO", "768", "Togolese Republic", "Togo", "多哥", "AF", "非洲", "🇹🇬", "", "", "", "XOF" ),
            new IsoCountryInfo("TH", "THA", "764", "Kingdom of Thailand", "Thailand", "泰国", "AS", "亚洲", "🇹🇭", "th", "Thai", "泰语", "THB" ),
            new IsoCountryInfo("TJ", "TJK", "762", "Republic of Tajikistan", "Tajikistan", "塔吉克斯坦", "AS", "亚洲", "🇹🇯", "", "", "", "TJS" ),
            new IsoCountryInfo("TK", "TKL", "772", "Tokelau", "Tokelau", "托克劳", "OC", "大洋洲", "🇹🇰", "", "", "", "NZD" ),
            new IsoCountryInfo("TL", "TLS", "626", "Democratic Republic of Timor-Leste", "Timor-Leste", "东帝汶", "AS", "亚洲", "🇹🇱", "", "", "", "USD" ),
            new IsoCountryInfo("TM", "TKM", "795", "Turkmenistan", "Turkmenistan", "土库曼斯坦", "AS", "亚洲", "🇹🇲", "", "", "", "TMT" ),
            new IsoCountryInfo("TN", "TUN", "788", "Republic of Tunisia", "Tunisia", "突尼斯", "AF", "非洲", "🇹🇳", "", "", "", "TND" ),
            new IsoCountryInfo("TO", "TON", "776", "Kingdom of Tonga", "Tonga", "汤加", "OC", "大洋洲", "🇹🇴", "", "", "", "TOP" ),
            new IsoCountryInfo("TR", "TUR", "792", "Republic of Türkiye", "Türkiye", "土耳其", "AS", "亚洲", "🇹🇷", "tr", "Turkish", "土耳其语", "TRY" ),
            new IsoCountryInfo("TT", "TTO", "780", "Republic of Trinidad and Tobago", "Trinidad and Tobago", "特立尼达和多巴哥", "NA", "北美洲", "🇹🇹", "", "", "", "TTD" ),
            new IsoCountryInfo("TV", "TUV", "798", "Tuvalu", "Tuvalu", "图瓦卢", "OC", "大洋洲", "🇹🇻", "", "", "", "AUD" ),
            new IsoCountryInfo("TW", "TWN", "158", "Taiwan, Province of China", "Taiwan, Province of China", "台湾", "AS", "亚洲", "🇹🇼", "zh", "Chinese", "中文", "TWD" ),
            new IsoCountryInfo("TZ", "TZA", "834", "United Republic of Tanzania", "Tanzania, United Republic of", "坦桑尼亚", "AF", "非洲", "🇹🇿", "", "", "", "TZS" ),
            new IsoCountryInfo("UA", "UKR", "804", "Ukraine", "Ukraine", "乌克兰", "EU", "欧洲", "🇺🇦", "", "", "", "UAH" ),
            new IsoCountryInfo("UG", "UGA", "800", "Republic of Uganda", "Uganda", "乌干达", "AF", "非洲", "🇺🇬", "", "", "", "UGX" ),
            new IsoCountryInfo("UM", "UMI", "581", "United States Minor Outlying Islands", "United States Minor Outlying Islands", "美国本土外小岛屿", "OC", "大洋洲", "🇺🇲", "", "", "", "USD" ),
            new IsoCountryInfo("US", "USA", "840", "United States of America", "United States", "美国", "NA", "北美洲", "🇺🇸", "en", "English", "英语", "USD" ),
            new IsoCountryInfo("UY", "URY", "858", "Eastern Republic of Uruguay", "Uruguay", "乌拉圭", "SA", "南美洲", "🇺🇾", "es", "Spanish", "西班牙语", "UYU" ),
            new IsoCountryInfo("UZ", "UZB", "860", "Republic of Uzbekistan", "Uzbekistan", "乌兹别克斯坦", "AS", "亚洲", "🇺🇿", "", "", "", "UZS" ),
            new IsoCountryInfo("VA", "VAT", "336", "Holy See (Vatican City State)", "Holy See (Vatican City State)", "梵蒂冈", "EU", "欧洲", "🇻🇦", "", "", "", "EUR" ),
            new IsoCountryInfo("VC", "VCT", "670", "Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines", "圣文森特和格林纳丁斯", "NA", "北美洲", "🇻🇨", "", "", "", "XCD" ),
            new IsoCountryInfo("VE", "VEN", "862", "Bolivarian Republic of Venezuela", "Venezuela, Bolivarian Republic of", "委内瑞拉", "SA", "南美洲", "🇻🇪", "", "", "", "VES" ),
            new IsoCountryInfo("VG", "VGB", "092", "British Virgin Islands", "Virgin Islands, British", "英属维尔京群岛", "NA", "北美洲", "🇻🇬", "", "", "", "USD" ),
            new IsoCountryInfo("VI", "VIR", "850", "Virgin Islands of the United States", "Virgin Islands, U.S.", "美属维尔京群岛", "NA", "北美洲", "🇻🇮", "", "", "", "USD" ),
            new IsoCountryInfo("VN", "VNM", "704", "Socialist Republic of Viet Nam", "Viet Nam", "越南", "AS", "亚洲", "🇻🇳", "vi", "Vietnamese", "越南语", "VND" ),
            new IsoCountryInfo("VU", "VUT", "548", "Republic of Vanuatu", "Vanuatu", "瓦努阿图", "OC", "大洋洲", "🇻🇺", "", "", "", "VUV" ),
            new IsoCountryInfo("WF", "WLF", "876", "Wallis and Futuna", "Wallis and Futuna", "瓦利斯和富图纳", "OC", "大洋洲", "🇼🇫", "", "", "", "XPF" ),
            new IsoCountryInfo("WS", "WSM", "882", "Independent State of Samoa", "Samoa", "萨摩亚", "OC", "大洋洲", "🇼🇸", "", "", "", "WST" ),
            new IsoCountryInfo("YE", "YEM", "887", "Republic of Yemen", "Yemen", "也门", "AS", "亚洲", "🇾🇪", "", "", "", "YER" ),
            new IsoCountryInfo("YT", "MYT", "175", "Mayotte", "Mayotte", "马约特", "AF", "非洲", "🇾🇹", "", "", "", "EUR" ),
            new IsoCountryInfo("ZA", "ZAF", "710", "Republic of South Africa", "South Africa", "南非", "AF", "非洲", "🇿🇦", "en", "English", "英语", "ZAR" ),
            new IsoCountryInfo("ZM", "ZMB", "894", "Republic of Zambia", "Zambia", "赞比亚", "AF", "非洲", "🇿🇲", "", "", "", "ZMW" ),
            new IsoCountryInfo("ZW", "ZWE", "716", "Republic of Zimbabwe", "Zimbabwe", "津巴布韦", "AF", "非洲", "🇿🇼", "", "", "", "USD" )
    );

    /**
     * ISO 4217 币种基础数据。
     */
    static final List<IsoCurrencyInfo> CURRENCIES = List.of(
            new IsoCurrencyInfo("ADP", "020", "Andorran Peseta", "安道尔比塞塔", 0, 1L, new BigDecimal("1"), "ADP" ),
            new IsoCurrencyInfo("AED", "784", "United Arab Emirates Dirham", "阿联酋迪拉姆", 2, 100L, new BigDecimal("0.01"), "AED" ),
            new IsoCurrencyInfo("AFA", "004", "Afghan Afghani (1927–2002)", "阿富汗尼 (1927–2002)", 2, 100L, new BigDecimal("0.01"), "AFA" ),
            new IsoCurrencyInfo("AFN", "971", "Afghan Afghani", "阿富汗尼", 2, 100L, new BigDecimal("0.01"), "AFN" ),
            new IsoCurrencyInfo("ALL", "008", "Albanian Lek", "阿尔巴尼亚列克", 2, 100L, new BigDecimal("0.01"), "ALL" ),
            new IsoCurrencyInfo("AMD", "051", "Armenian Dram", "亚美尼亚德拉姆", 2, 100L, new BigDecimal("0.01"), "AMD" ),
            new IsoCurrencyInfo("ANG", "532", "Netherlands Antillean Guilder", "荷属安的列斯盾", 2, 100L, new BigDecimal("0.01"), "ANG" ),
            new IsoCurrencyInfo("AOA", "973", "Angolan Kwanza", "安哥拉宽扎", 2, 100L, new BigDecimal("0.01"), "AOA" ),
            new IsoCurrencyInfo("ARS", "032", "Argentine Peso", "阿根廷比索", 2, 100L, new BigDecimal("0.01"), "ARS" ),
            new IsoCurrencyInfo("ATS", "040", "Austrian Schilling", "奥地利先令", 2, 100L, new BigDecimal("0.01"), "ATS" ),
            new IsoCurrencyInfo("AUD", "036", "Australian Dollar", "澳大利亚元", 2, 100L, new BigDecimal("0.01"), "A$" ),
            new IsoCurrencyInfo("AWG", "533", "Aruban Florin", "阿鲁巴弗罗林", 2, 100L, new BigDecimal("0.01"), "AWG" ),
            new IsoCurrencyInfo("AYM", "945", "AYM", "AYM", 2, 100L, new BigDecimal("0.01"), "AYM" ),
            new IsoCurrencyInfo("AZM", "031", "Azerbaijani Manat (1993–2006)", "阿塞拜疆马纳特 (1993–2006)", 2, 100L, new BigDecimal("0.01"), "AZM" ),
            new IsoCurrencyInfo("AZN", "944", "Azerbaijani Manat", "阿塞拜疆马纳特", 2, 100L, new BigDecimal("0.01"), "AZN" ),
            new IsoCurrencyInfo("BAM", "977", "Bosnia-Herzegovina Convertible Mark", "波斯尼亚-黑塞哥维那可兑换马克", 2, 100L, new BigDecimal("0.01"), "BAM" ),
            new IsoCurrencyInfo("BBD", "052", "Barbadian Dollar", "巴巴多斯元", 2, 100L, new BigDecimal("0.01"), "BBD" ),
            new IsoCurrencyInfo("BDT", "050", "Bangladeshi Taka", "孟加拉塔卡", 2, 100L, new BigDecimal("0.01"), "BDT" ),
            new IsoCurrencyInfo("BEF", "056", "Belgian Franc", "比利时法郎", 0, 1L, new BigDecimal("1"), "BEF" ),
            new IsoCurrencyInfo("BGL", "100", "Bulgarian Hard Lev", "保加利亚硬列弗", 2, 100L, new BigDecimal("0.01"), "BGL" ),
            new IsoCurrencyInfo("BGN", "975", "Bulgarian Lev", "保加利亚列弗", 2, 100L, new BigDecimal("0.01"), "BGN" ),
            new IsoCurrencyInfo("BHD", "048", "Bahraini Dinar", "巴林第纳尔", 3, 1000L, new BigDecimal("0.001"), "BHD" ),
            new IsoCurrencyInfo("BIF", "108", "Burundian Franc", "布隆迪法郎", 0, 1L, new BigDecimal("1"), "BIF" ),
            new IsoCurrencyInfo("BMD", "060", "Bermudan Dollar", "百慕大元", 2, 100L, new BigDecimal("0.01"), "BMD" ),
            new IsoCurrencyInfo("BND", "096", "Brunei Dollar", "文莱元", 2, 100L, new BigDecimal("0.01"), "BND" ),
            new IsoCurrencyInfo("BOB", "068", "Bolivian Boliviano", "玻利维亚诺", 2, 100L, new BigDecimal("0.01"), "BOB" ),
            new IsoCurrencyInfo("BOV", "984", "Bolivian Mvdol", "玻利维亚 Mvdol（资金）", 2, 100L, new BigDecimal("0.01"), "BOV" ),
            new IsoCurrencyInfo("BRL", "986", "Brazilian Real", "巴西雷亚尔", 2, 100L, new BigDecimal("0.01"), "R$" ),
            new IsoCurrencyInfo("BSD", "044", "Bahamian Dollar", "巴哈马元", 2, 100L, new BigDecimal("0.01"), "BSD" ),
            new IsoCurrencyInfo("BTN", "064", "Bhutanese Ngultrum", "不丹努尔特鲁姆", 2, 100L, new BigDecimal("0.01"), "BTN" ),
            new IsoCurrencyInfo("BWP", "072", "Botswanan Pula", "博茨瓦纳普拉", 2, 100L, new BigDecimal("0.01"), "BWP" ),
            new IsoCurrencyInfo("BYB", "112", "Belarusian Ruble (1994–1999)", "白俄罗斯新卢布 (1994–1999)", 0, 1L, new BigDecimal("1"), "BYB" ),
            new IsoCurrencyInfo("BYN", "933", "Belarusian Ruble", "白俄罗斯卢布", 2, 100L, new BigDecimal("0.01"), "BYN" ),
            new IsoCurrencyInfo("BYR", "974", "Belarusian Ruble (2000–2016)", "白俄罗斯卢布 (2000–2016)", 0, 1L, new BigDecimal("1"), "BYR" ),
            new IsoCurrencyInfo("BZD", "084", "Belize Dollar", "伯利兹元", 2, 100L, new BigDecimal("0.01"), "BZD" ),
            new IsoCurrencyInfo("CAD", "124", "Canadian Dollar", "加拿大元", 2, 100L, new BigDecimal("0.01"), "CA$" ),
            new IsoCurrencyInfo("CDF", "976", "Congolese Franc", "刚果法郎", 2, 100L, new BigDecimal("0.01"), "CDF" ),
            new IsoCurrencyInfo("CHE", "947", "WIR Euro", "欧元 (WIR)", 2, 100L, new BigDecimal("0.01"), "CHE" ),
            new IsoCurrencyInfo("CHF", "756", "Swiss Franc", "瑞士法郎", 2, 100L, new BigDecimal("0.01"), "CHF" ),
            new IsoCurrencyInfo("CHW", "948", "WIR Franc", "法郎 (WIR)", 2, 100L, new BigDecimal("0.01"), "CHW" ),
            new IsoCurrencyInfo("CLF", "990", "Chilean Unit of Account (UF)", "智利（资金）", 4, 10000L, new BigDecimal("0.0001"), "CLF" ),
            new IsoCurrencyInfo("CLP", "152", "Chilean Peso", "智利比索", 0, 1L, new BigDecimal("1"), "CLP" ),
            new IsoCurrencyInfo("CNY", "156", "Chinese Yuan", "人民币", 2, 100L, new BigDecimal("0.01"), "CN¥" ),
            new IsoCurrencyInfo("COP", "170", "Colombian Peso", "哥伦比亚比索", 2, 100L, new BigDecimal("0.01"), "COP" ),
            new IsoCurrencyInfo("COU", "970", "Colombian Real Value Unit", "哥伦比亚币", 2, 100L, new BigDecimal("0.01"), "COU" ),
            new IsoCurrencyInfo("CRC", "188", "Costa Rican Colón", "哥斯达黎加科朗", 2, 100L, new BigDecimal("0.01"), "CRC" ),
            new IsoCurrencyInfo("CSD", "891", "Serbian Dinar (2002–2006)", "旧塞尔维亚第纳尔", 2, 100L, new BigDecimal("0.01"), "CSD" ),
            new IsoCurrencyInfo("CUC", "931", "Cuban Convertible Peso", "古巴可兑换比索", 2, 100L, new BigDecimal("0.01"), "CUC" ),
            new IsoCurrencyInfo("CUP", "192", "Cuban Peso", "古巴比索", 2, 100L, new BigDecimal("0.01"), "CUP" ),
            new IsoCurrencyInfo("CVE", "132", "Cape Verdean Escudo", "佛得角埃斯库多", 2, 100L, new BigDecimal("0.01"), "CVE" ),
            new IsoCurrencyInfo("CYP", "196", "Cypriot Pound", "塞浦路斯镑", 2, 100L, new BigDecimal("0.01"), "CYP" ),
            new IsoCurrencyInfo("CZK", "203", "Czech Koruna", "捷克克朗", 2, 100L, new BigDecimal("0.01"), "CZK" ),
            new IsoCurrencyInfo("DEM", "276", "German Mark", "德国马克", 2, 100L, new BigDecimal("0.01"), "DEM" ),
            new IsoCurrencyInfo("DJF", "262", "Djiboutian Franc", "吉布提法郎", 0, 1L, new BigDecimal("1"), "DJF" ),
            new IsoCurrencyInfo("DKK", "208", "Danish Krone", "丹麦克朗", 2, 100L, new BigDecimal("0.01"), "DKK" ),
            new IsoCurrencyInfo("DOP", "214", "Dominican Peso", "多米尼加比索", 2, 100L, new BigDecimal("0.01"), "DOP" ),
            new IsoCurrencyInfo("DZD", "012", "Algerian Dinar", "阿尔及利亚第纳尔", 2, 100L, new BigDecimal("0.01"), "DZD" ),
            new IsoCurrencyInfo("EEK", "233", "Estonian Kroon", "爱沙尼亚克朗", 2, 100L, new BigDecimal("0.01"), "EEK" ),
            new IsoCurrencyInfo("EGP", "818", "Egyptian Pound", "埃及镑", 2, 100L, new BigDecimal("0.01"), "EGP" ),
            new IsoCurrencyInfo("ERN", "232", "Eritrean Nakfa", "厄立特里亚纳克法", 2, 100L, new BigDecimal("0.01"), "ERN" ),
            new IsoCurrencyInfo("ESP", "724", "Spanish Peseta", "西班牙比塞塔", 0, 1L, new BigDecimal("1"), "ESP" ),
            new IsoCurrencyInfo("ETB", "230", "Ethiopian Birr", "埃塞俄比亚比尔", 2, 100L, new BigDecimal("0.01"), "ETB" ),
            new IsoCurrencyInfo("EUR", "978", "Euro", "欧元", 2, 100L, new BigDecimal("0.01"), "€" ),
            new IsoCurrencyInfo("FIM", "246", "Finnish Markka", "芬兰马克", 2, 100L, new BigDecimal("0.01"), "FIM" ),
            new IsoCurrencyInfo("FJD", "242", "Fijian Dollar", "斐济元", 2, 100L, new BigDecimal("0.01"), "FJD" ),
            new IsoCurrencyInfo("FKP", "238", "Falkland Islands Pound", "福克兰群岛镑", 2, 100L, new BigDecimal("0.01"), "FKP" ),
            new IsoCurrencyInfo("FRF", "250", "French Franc", "法国法郎", 2, 100L, new BigDecimal("0.01"), "FRF" ),
            new IsoCurrencyInfo("GBP", "826", "British Pound", "英镑", 2, 100L, new BigDecimal("0.01"), "£" ),
            new IsoCurrencyInfo("GEL", "981", "Georgian Lari", "格鲁吉亚拉里", 2, 100L, new BigDecimal("0.01"), "GEL" ),
            new IsoCurrencyInfo("GHC", "288", "Ghanaian Cedi (1979–2007)", "加纳塞第", 2, 100L, new BigDecimal("0.01"), "GHC" ),
            new IsoCurrencyInfo("GHS", "936", "Ghanaian Cedi", "加纳塞地", 2, 100L, new BigDecimal("0.01"), "GHS" ),
            new IsoCurrencyInfo("GIP", "292", "Gibraltar Pound", "直布罗陀镑", 2, 100L, new BigDecimal("0.01"), "GIP" ),
            new IsoCurrencyInfo("GMD", "270", "Gambian Dalasi", "冈比亚达拉西", 2, 100L, new BigDecimal("0.01"), "GMD" ),
            new IsoCurrencyInfo("GNF", "324", "Guinean Franc", "几内亚法郎", 0, 1L, new BigDecimal("1"), "GNF" ),
            new IsoCurrencyInfo("GRD", "300", "Greek Drachma", "希腊德拉克马", 0, 1L, new BigDecimal("1"), "GRD" ),
            new IsoCurrencyInfo("GTQ", "320", "Guatemalan Quetzal", "危地马拉格查尔", 2, 100L, new BigDecimal("0.01"), "GTQ" ),
            new IsoCurrencyInfo("GWP", "624", "Guinea-Bissau Peso", "几内亚比绍比索", 2, 100L, new BigDecimal("0.01"), "GWP" ),
            new IsoCurrencyInfo("GYD", "328", "Guyanaese Dollar", "圭亚那元", 2, 100L, new BigDecimal("0.01"), "GYD" ),
            new IsoCurrencyInfo("HKD", "344", "Hong Kong Dollar", "港元", 2, 100L, new BigDecimal("0.01"), "HK$" ),
            new IsoCurrencyInfo("HNL", "340", "Honduran Lempira", "洪都拉斯伦皮拉", 2, 100L, new BigDecimal("0.01"), "HNL" ),
            new IsoCurrencyInfo("HRK", "191", "Croatian Kuna", "克罗地亚库纳", 2, 100L, new BigDecimal("0.01"), "HRK" ),
            new IsoCurrencyInfo("HTG", "332", "Haitian Gourde", "海地古德", 2, 100L, new BigDecimal("0.01"), "HTG" ),
            new IsoCurrencyInfo("HUF", "348", "Hungarian Forint", "匈牙利福林", 2, 100L, new BigDecimal("0.01"), "HUF" ),
            new IsoCurrencyInfo("IDR", "360", "Indonesian Rupiah", "印度尼西亚卢比", 2, 100L, new BigDecimal("0.01"), "IDR" ),
            new IsoCurrencyInfo("IEP", "372", "Irish Pound", "爱尔兰镑", 2, 100L, new BigDecimal("0.01"), "IEP" ),
            new IsoCurrencyInfo("ILS", "376", "Israeli New Shekel", "以色列新谢克尔", 2, 100L, new BigDecimal("0.01"), "₪" ),
            new IsoCurrencyInfo("INR", "356", "Indian Rupee", "印度卢比", 2, 100L, new BigDecimal("0.01"), "₹" ),
            new IsoCurrencyInfo("IQD", "368", "Iraqi Dinar", "伊拉克第纳尔", 3, 1000L, new BigDecimal("0.001"), "IQD" ),
            new IsoCurrencyInfo("IRR", "364", "Iranian Rial", "伊朗里亚尔", 2, 100L, new BigDecimal("0.01"), "IRR" ),
            new IsoCurrencyInfo("ISK", "352", "Icelandic Króna", "冰岛克朗", 0, 1L, new BigDecimal("1"), "ISK" ),
            new IsoCurrencyInfo("ITL", "380", "Italian Lira", "意大利里拉", 0, 1L, new BigDecimal("1"), "ITL" ),
            new IsoCurrencyInfo("JMD", "388", "Jamaican Dollar", "牙买加元", 2, 100L, new BigDecimal("0.01"), "JMD" ),
            new IsoCurrencyInfo("JOD", "400", "Jordanian Dinar", "约旦第纳尔", 3, 1000L, new BigDecimal("0.001"), "JOD" ),
            new IsoCurrencyInfo("JPY", "392", "Japanese Yen", "日元", 0, 1L, new BigDecimal("1"), "¥" ),
            new IsoCurrencyInfo("KES", "404", "Kenyan Shilling", "肯尼亚先令", 2, 100L, new BigDecimal("0.01"), "KES" ),
            new IsoCurrencyInfo("KGS", "417", "Kyrgystani Som", "吉尔吉斯斯坦索姆", 2, 100L, new BigDecimal("0.01"), "KGS" ),
            new IsoCurrencyInfo("KHR", "116", "Cambodian Riel", "柬埔寨瑞尔", 2, 100L, new BigDecimal("0.01"), "KHR" ),
            new IsoCurrencyInfo("KMF", "174", "Comorian Franc", "科摩罗法郎", 0, 1L, new BigDecimal("1"), "KMF" ),
            new IsoCurrencyInfo("KPW", "408", "North Korean Won", "朝鲜元", 2, 100L, new BigDecimal("0.01"), "KPW" ),
            new IsoCurrencyInfo("KRW", "410", "South Korean Won", "韩元", 0, 1L, new BigDecimal("1"), "₩" ),
            new IsoCurrencyInfo("KWD", "414", "Kuwaiti Dinar", "科威特第纳尔", 3, 1000L, new BigDecimal("0.001"), "KWD" ),
            new IsoCurrencyInfo("KYD", "136", "Cayman Islands Dollar", "开曼元", 2, 100L, new BigDecimal("0.01"), "KYD" ),
            new IsoCurrencyInfo("KZT", "398", "Kazakhstani Tenge", "哈萨克斯坦坚戈", 2, 100L, new BigDecimal("0.01"), "KZT" ),
            new IsoCurrencyInfo("LAK", "418", "Laotian Kip", "老挝基普", 2, 100L, new BigDecimal("0.01"), "LAK" ),
            new IsoCurrencyInfo("LBP", "422", "Lebanese Pound", "黎巴嫩镑", 2, 100L, new BigDecimal("0.01"), "LBP" ),
            new IsoCurrencyInfo("LKR", "144", "Sri Lankan Rupee", "斯里兰卡卢比", 2, 100L, new BigDecimal("0.01"), "LKR" ),
            new IsoCurrencyInfo("LRD", "430", "Liberian Dollar", "利比里亚元", 2, 100L, new BigDecimal("0.01"), "LRD" ),
            new IsoCurrencyInfo("LSL", "426", "Lesotho Loti", "莱索托洛蒂", 2, 100L, new BigDecimal("0.01"), "LSL" ),
            new IsoCurrencyInfo("LTL", "440", "Lithuanian Litas", "立陶宛立特", 2, 100L, new BigDecimal("0.01"), "LTL" ),
            new IsoCurrencyInfo("LUF", "442", "Luxembourgian Franc", "卢森堡法郎", 0, 1L, new BigDecimal("1"), "LUF" ),
            new IsoCurrencyInfo("LVL", "428", "Latvian Lats", "拉脱维亚拉特", 2, 100L, new BigDecimal("0.01"), "LVL" ),
            new IsoCurrencyInfo("LYD", "434", "Libyan Dinar", "利比亚第纳尔", 3, 1000L, new BigDecimal("0.001"), "LYD" ),
            new IsoCurrencyInfo("MAD", "504", "Moroccan Dirham", "摩洛哥迪拉姆", 2, 100L, new BigDecimal("0.01"), "MAD" ),
            new IsoCurrencyInfo("MDL", "498", "Moldovan Leu", "摩尔多瓦列伊", 2, 100L, new BigDecimal("0.01"), "MDL" ),
            new IsoCurrencyInfo("MGA", "969", "Malagasy Ariary", "马达加斯加阿里亚里", 2, 100L, new BigDecimal("0.01"), "MGA" ),
            new IsoCurrencyInfo("MGF", "450", "Malagasy Franc", "马达加斯加法郎", 0, 1L, new BigDecimal("1"), "MGF" ),
            new IsoCurrencyInfo("MKD", "807", "Macedonian Denar", "马其顿第纳尔", 2, 100L, new BigDecimal("0.01"), "MKD" ),
            new IsoCurrencyInfo("MMK", "104", "Myanmar Kyat", "缅甸元", 2, 100L, new BigDecimal("0.01"), "MMK" ),
            new IsoCurrencyInfo("MNT", "496", "Mongolian Tugrik", "蒙古图格里克", 2, 100L, new BigDecimal("0.01"), "MNT" ),
            new IsoCurrencyInfo("MOP", "446", "Macanese Pataca", "澳门币", 2, 100L, new BigDecimal("0.01"), "MOP" ),
            new IsoCurrencyInfo("MRO", "478", "Mauritanian Ouguiya (1973–2017)", "毛里塔尼亚乌吉亚 (1973–2017)", 2, 100L, new BigDecimal("0.01"), "MRO" ),
            new IsoCurrencyInfo("MRU", "929", "Mauritanian Ouguiya", "毛里塔尼亚乌吉亚", 2, 100L, new BigDecimal("0.01"), "MRU" ),
            new IsoCurrencyInfo("MTL", "470", "Maltese Lira", "马耳他里拉", 2, 100L, new BigDecimal("0.01"), "MTL" ),
            new IsoCurrencyInfo("MUR", "480", "Mauritian Rupee", "毛里求斯卢比", 2, 100L, new BigDecimal("0.01"), "MUR" ),
            new IsoCurrencyInfo("MVR", "462", "Maldivian Rufiyaa", "马尔代夫卢菲亚", 2, 100L, new BigDecimal("0.01"), "MVR" ),
            new IsoCurrencyInfo("MWK", "454", "Malawian Kwacha", "马拉维克瓦查", 2, 100L, new BigDecimal("0.01"), "MWK" ),
            new IsoCurrencyInfo("MXN", "484", "Mexican Peso", "墨西哥比索", 2, 100L, new BigDecimal("0.01"), "MX$" ),
            new IsoCurrencyInfo("MXV", "979", "Mexican Investment Unit", "墨西哥（资金）", 2, 100L, new BigDecimal("0.01"), "MXV" ),
            new IsoCurrencyInfo("MYR", "458", "Malaysian Ringgit", "马来西亚林吉特", 2, 100L, new BigDecimal("0.01"), "MYR" ),
            new IsoCurrencyInfo("MZM", "508", "Mozambican Metical (1980–2006)", "旧莫桑比克美提卡", 2, 100L, new BigDecimal("0.01"), "MZM" ),
            new IsoCurrencyInfo("MZN", "943", "Mozambican Metical", "莫桑比克美提卡", 2, 100L, new BigDecimal("0.01"), "MZN" ),
            new IsoCurrencyInfo("NAD", "516", "Namibian Dollar", "纳米比亚元", 2, 100L, new BigDecimal("0.01"), "NAD" ),
            new IsoCurrencyInfo("NGN", "566", "Nigerian Naira", "尼日利亚奈拉", 2, 100L, new BigDecimal("0.01"), "NGN" ),
            new IsoCurrencyInfo("NIO", "558", "Nicaraguan Córdoba", "尼加拉瓜科多巴", 2, 100L, new BigDecimal("0.01"), "NIO" ),
            new IsoCurrencyInfo("NLG", "528", "Dutch Guilder", "荷兰盾", 2, 100L, new BigDecimal("0.01"), "NLG" ),
            new IsoCurrencyInfo("NOK", "578", "Norwegian Krone", "挪威克朗", 2, 100L, new BigDecimal("0.01"), "NOK" ),
            new IsoCurrencyInfo("NPR", "524", "Nepalese Rupee", "尼泊尔卢比", 2, 100L, new BigDecimal("0.01"), "NPR" ),
            new IsoCurrencyInfo("NZD", "554", "New Zealand Dollar", "新西兰元", 2, 100L, new BigDecimal("0.01"), "NZ$" ),
            new IsoCurrencyInfo("OMR", "512", "Omani Rial", "阿曼里亚尔", 3, 1000L, new BigDecimal("0.001"), "OMR" ),
            new IsoCurrencyInfo("PAB", "590", "Panamanian Balboa", "巴拿马巴波亚", 2, 100L, new BigDecimal("0.01"), "PAB" ),
            new IsoCurrencyInfo("PEN", "604", "Peruvian Sol", "秘鲁索尔", 2, 100L, new BigDecimal("0.01"), "PEN" ),
            new IsoCurrencyInfo("PGK", "598", "Papua New Guinean Kina", "巴布亚新几内亚基那", 2, 100L, new BigDecimal("0.01"), "PGK" ),
            new IsoCurrencyInfo("PHP", "608", "Philippine Peso", "菲律宾比索", 2, 100L, new BigDecimal("0.01"), "₱" ),
            new IsoCurrencyInfo("PKR", "586", "Pakistani Rupee", "巴基斯坦卢比", 2, 100L, new BigDecimal("0.01"), "PKR" ),
            new IsoCurrencyInfo("PLN", "985", "Polish Zloty", "波兰兹罗提", 2, 100L, new BigDecimal("0.01"), "PLN" ),
            new IsoCurrencyInfo("PTE", "620", "Portuguese Escudo", "葡萄牙埃斯库多", 0, 1L, new BigDecimal("1"), "PTE" ),
            new IsoCurrencyInfo("PYG", "600", "Paraguayan Guarani", "巴拉圭瓜拉尼", 0, 1L, new BigDecimal("1"), "PYG" ),
            new IsoCurrencyInfo("QAR", "634", "Qatari Riyal", "卡塔尔里亚尔", 2, 100L, new BigDecimal("0.01"), "QAR" ),
            new IsoCurrencyInfo("ROL", "642", "Romanian Leu (1952–2006)", "旧罗马尼亚列伊", 0, 1L, new BigDecimal("1"), "ROL" ),
            new IsoCurrencyInfo("RON", "946", "Romanian Leu", "罗马尼亚列伊", 2, 100L, new BigDecimal("0.01"), "RON" ),
            new IsoCurrencyInfo("RSD", "941", "Serbian Dinar", "塞尔维亚第纳尔", 2, 100L, new BigDecimal("0.01"), "RSD" ),
            new IsoCurrencyInfo("RUB", "643", "Russian Ruble", "俄罗斯卢布", 2, 100L, new BigDecimal("0.01"), "RUB" ),
            new IsoCurrencyInfo("RUR", "810", "Russian Ruble (1991–1998)", "俄国卢布 (1991–1998)", 2, 100L, new BigDecimal("0.01"), "RUR" ),
            new IsoCurrencyInfo("RWF", "646", "Rwandan Franc", "卢旺达法郎", 0, 1L, new BigDecimal("1"), "RWF" ),
            new IsoCurrencyInfo("SAR", "682", "Saudi Riyal", "沙特里亚尔", 2, 100L, new BigDecimal("0.01"), "SAR" ),
            new IsoCurrencyInfo("SBD", "090", "Solomon Islands Dollar", "所罗门群岛元", 2, 100L, new BigDecimal("0.01"), "SBD" ),
            new IsoCurrencyInfo("SCR", "690", "Seychellois Rupee", "塞舌尔卢比", 2, 100L, new BigDecimal("0.01"), "SCR" ),
            new IsoCurrencyInfo("SDD", "736", "Sudanese Dinar (1992–2007)", "苏丹第纳尔 (1992–2007)", 2, 100L, new BigDecimal("0.01"), "SDD" ),
            new IsoCurrencyInfo("SDG", "938", "Sudanese Pound", "苏丹镑", 2, 100L, new BigDecimal("0.01"), "SDG" ),
            new IsoCurrencyInfo("SEK", "752", "Swedish Krona", "瑞典克朗", 2, 100L, new BigDecimal("0.01"), "SEK" ),
            new IsoCurrencyInfo("SGD", "702", "Singapore Dollar", "新加坡元", 2, 100L, new BigDecimal("0.01"), "SGD" ),
            new IsoCurrencyInfo("SHP", "654", "St. Helena Pound", "圣赫勒拿群岛磅", 2, 100L, new BigDecimal("0.01"), "SHP" ),
            new IsoCurrencyInfo("SIT", "705", "Slovenian Tolar", "斯洛文尼亚托拉尔", 2, 100L, new BigDecimal("0.01"), "SIT" ),
            new IsoCurrencyInfo("SKK", "703", "Slovak Koruna", "斯洛伐克克朗", 2, 100L, new BigDecimal("0.01"), "SKK" ),
            new IsoCurrencyInfo("SLE", "925", "Sierra Leonean Leone", "塞拉利昂新利昂", 2, 100L, new BigDecimal("0.01"), "SLE" ),
            new IsoCurrencyInfo("SLL", "694", "Sierra Leonean Leone (1964—2022)", "塞拉利昂利昂", 2, 100L, new BigDecimal("0.01"), "SLL" ),
            new IsoCurrencyInfo("SOS", "706", "Somali Shilling", "索马里先令", 2, 100L, new BigDecimal("0.01"), "SOS" ),
            new IsoCurrencyInfo("SRD", "968", "Surinamese Dollar", "苏里南元", 2, 100L, new BigDecimal("0.01"), "SRD" ),
            new IsoCurrencyInfo("SRG", "740", "Surinamese Guilder", "苏里南盾", 2, 100L, new BigDecimal("0.01"), "SRG" ),
            new IsoCurrencyInfo("SSP", "728", "South Sudanese Pound", "南苏丹镑", 2, 100L, new BigDecimal("0.01"), "SSP" ),
            new IsoCurrencyInfo("STD", "678", "São Tomé & Príncipe Dobra (1977–2017)", "圣多美和普林西比多布拉 (1977–2017)", 2, 100L, new BigDecimal("0.01"), "STD" ),
            new IsoCurrencyInfo("STN", "930", "São Tomé & Príncipe Dobra", "圣多美和普林西比多布拉", 2, 100L, new BigDecimal("0.01"), "STN" ),
            new IsoCurrencyInfo("SVC", "222", "Salvadoran Colón", "萨尔瓦多科朗", 2, 100L, new BigDecimal("0.01"), "SVC" ),
            new IsoCurrencyInfo("SYP", "760", "Syrian Pound", "叙利亚镑", 2, 100L, new BigDecimal("0.01"), "SYP" ),
            new IsoCurrencyInfo("SZL", "748", "Swazi Lilangeni", "斯威士兰里兰吉尼", 2, 100L, new BigDecimal("0.01"), "SZL" ),
            new IsoCurrencyInfo("THB", "764", "Thai Baht", "泰铢", 2, 100L, new BigDecimal("0.01"), "THB" ),
            new IsoCurrencyInfo("TJS", "972", "Tajikistani Somoni", "塔吉克斯坦索莫尼", 2, 100L, new BigDecimal("0.01"), "TJS" ),
            new IsoCurrencyInfo("TMM", "795", "Turkmenistani Manat (1993–2009)", "土库曼斯坦马纳特 (1993–2009)", 2, 100L, new BigDecimal("0.01"), "TMM" ),
            new IsoCurrencyInfo("TMT", "934", "Turkmenistani Manat", "土库曼斯坦马纳特", 2, 100L, new BigDecimal("0.01"), "TMT" ),
            new IsoCurrencyInfo("TND", "788", "Tunisian Dinar", "突尼斯第纳尔", 3, 1000L, new BigDecimal("0.001"), "TND" ),
            new IsoCurrencyInfo("TOP", "776", "Tongan Paʻanga", "汤加潘加", 2, 100L, new BigDecimal("0.01"), "TOP" ),
            new IsoCurrencyInfo("TPE", "626", "Timorese Escudo", "帝汶埃斯库多", 0, 1L, new BigDecimal("1"), "TPE" ),
            new IsoCurrencyInfo("TRL", "792", "Turkish Lira (1922–2005)", "土耳其里拉 (1922–2005)", 0, 1L, new BigDecimal("1"), "TRL" ),
            new IsoCurrencyInfo("TRY", "949", "Turkish Lira", "土耳其里拉", 2, 100L, new BigDecimal("0.01"), "TRY" ),
            new IsoCurrencyInfo("TTD", "780", "Trinidad & Tobago Dollar", "特立尼达和多巴哥元", 2, 100L, new BigDecimal("0.01"), "TTD" ),
            new IsoCurrencyInfo("TWD", "901", "New Taiwan Dollar", "新台币", 2, 100L, new BigDecimal("0.01"), "NT$" ),
            new IsoCurrencyInfo("TZS", "834", "Tanzanian Shilling", "坦桑尼亚先令", 2, 100L, new BigDecimal("0.01"), "TZS" ),
            new IsoCurrencyInfo("UAH", "980", "Ukrainian Hryvnia", "乌克兰格里夫纳", 2, 100L, new BigDecimal("0.01"), "UAH" ),
            new IsoCurrencyInfo("UGX", "800", "Ugandan Shilling", "乌干达先令", 0, 1L, new BigDecimal("1"), "UGX" ),
            new IsoCurrencyInfo("USD", "840", "US Dollar", "美元", 2, 100L, new BigDecimal("0.01"), "$" ),
            new IsoCurrencyInfo("USN", "997", "US Dollar (Next day)", "美元（次日）", 2, 100L, new BigDecimal("0.01"), "USN" ),
            new IsoCurrencyInfo("USS", "998", "US Dollar (Same day)", "美元（当日）", 2, 100L, new BigDecimal("0.01"), "USS" ),
            new IsoCurrencyInfo("UYI", "940", "Uruguayan Peso (Indexed Units)", "乌拉圭比索（索引单位）", 0, 1L, new BigDecimal("1"), "UYI" ),
            new IsoCurrencyInfo("UYU", "858", "Uruguayan Peso", "乌拉圭比索", 2, 100L, new BigDecimal("0.01"), "UYU" ),
            new IsoCurrencyInfo("UZS", "860", "Uzbekistani Som", "乌兹别克斯坦苏姆", 2, 100L, new BigDecimal("0.01"), "UZS" ),
            new IsoCurrencyInfo("VEB", "862", "Venezuelan Bolívar (1871–2008)", "委内瑞拉玻利瓦尔 (1871–2008)", 2, 100L, new BigDecimal("0.01"), "VEB" ),
            new IsoCurrencyInfo("VED", "926", "Bolívar Soberano", "委内瑞拉主权币", 2, 100L, new BigDecimal("0.01"), "VED" ),
            new IsoCurrencyInfo("VEF", "937", "Venezuelan Bolívar (2008–2018)", "委内瑞拉玻利瓦尔 (2008–2018)", 2, 100L, new BigDecimal("0.01"), "VEF" ),
            new IsoCurrencyInfo("VES", "928", "Venezuelan Bolívar", "委内瑞拉玻利瓦尔", 2, 100L, new BigDecimal("0.01"), "VES" ),
            new IsoCurrencyInfo("VND", "704", "Vietnamese Dong", "越南盾", 0, 1L, new BigDecimal("1"), "₫" ),
            new IsoCurrencyInfo("VUV", "548", "Vanuatu Vatu", "瓦努阿图瓦图", 0, 1L, new BigDecimal("1"), "VUV" ),
            new IsoCurrencyInfo("WST", "882", "Samoan Tala", "萨摩亚塔拉", 2, 100L, new BigDecimal("0.01"), "WST" ),
            new IsoCurrencyInfo("XAD", "396", "XAD", "XAD", 2, 100L, new BigDecimal("0.01"), "XAD" ),
            new IsoCurrencyInfo("XAF", "950", "Central African CFA Franc", "中非法郎", 0, 1L, new BigDecimal("1"), "FCFA" ),
            new IsoCurrencyInfo("XAG", "961", "Silver", "银", -1, 0L, new BigDecimal("0"), "XAG" ),
            new IsoCurrencyInfo("XAU", "959", "Gold", "黄金", -1, 0L, new BigDecimal("0"), "XAU" ),
            new IsoCurrencyInfo("XBA", "955", "European Composite Unit", "欧洲复合单位", -1, 0L, new BigDecimal("0"), "XBA" ),
            new IsoCurrencyInfo("XBB", "956", "European Monetary Unit", "欧洲货币联盟", -1, 0L, new BigDecimal("0"), "XBB" ),
            new IsoCurrencyInfo("XBC", "957", "European Unit of Account (XBC)", "欧洲计算单位 (XBC)", -1, 0L, new BigDecimal("0"), "XBC" ),
            new IsoCurrencyInfo("XBD", "958", "European Unit of Account (XBD)", "欧洲计算单位 (XBD)", -1, 0L, new BigDecimal("0"), "XBD" ),
            new IsoCurrencyInfo("XCD", "951", "East Caribbean Dollar", "东加勒比元", 2, 100L, new BigDecimal("0.01"), "EC$" ),
            new IsoCurrencyInfo("XCG", "532", "Caribbean guilder", "XCG", 2, 100L, new BigDecimal("0.01"), "Cg." ),
            new IsoCurrencyInfo("XDR", "960", "Special Drawing Rights", "特别提款权", -1, 0L, new BigDecimal("0"), "XDR" ),
            new IsoCurrencyInfo("XFO", "000", "French Gold Franc", "法国金法郎", -1, 0L, new BigDecimal("0"), "XFO" ),
            new IsoCurrencyInfo("XFU", "000", "French UIC-Franc", "法国法郎 (UIC)", -1, 0L, new BigDecimal("0"), "XFU" ),
            new IsoCurrencyInfo("XOF", "952", "West African CFA Franc", "西非法郎", 0, 1L, new BigDecimal("1"), "F CFA" ),
            new IsoCurrencyInfo("XPD", "964", "Palladium", "钯", -1, 0L, new BigDecimal("0"), "XPD" ),
            new IsoCurrencyInfo("XPF", "953", "CFP Franc", "太平洋法郎", 0, 1L, new BigDecimal("1"), "CFPF" ),
            new IsoCurrencyInfo("XPT", "962", "Platinum", "铂", -1, 0L, new BigDecimal("0"), "XPT" ),
            new IsoCurrencyInfo("XSU", "994", "Sucre", "苏克雷", -1, 0L, new BigDecimal("0"), "XSU" ),
            new IsoCurrencyInfo("XTS", "963", "Testing Currency Code", "测试货币代码", -1, 0L, new BigDecimal("0"), "XTS" ),
            new IsoCurrencyInfo("XUA", "965", "ADB Unit of Account", "非洲开发银行记账单位", -1, 0L, new BigDecimal("0"), "XUA" ),
            new IsoCurrencyInfo("XXX", "999", "Unknown Currency", "未知货币", -1, 0L, new BigDecimal("0"), "¤" ),
            new IsoCurrencyInfo("YER", "886", "Yemeni Rial", "也门里亚尔", 2, 100L, new BigDecimal("0.01"), "YER" ),
            new IsoCurrencyInfo("YUM", "891", "Yugoslavian New Dinar (1994–2002)", "南斯拉夫新第纳尔 (1994–2002)", 2, 100L, new BigDecimal("0.01"), "YUM" ),
            new IsoCurrencyInfo("ZAR", "710", "South African Rand", "南非兰特", 2, 100L, new BigDecimal("0.01"), "ZAR" ),
            new IsoCurrencyInfo("ZMK", "894", "Zambian Kwacha (1968–2012)", "赞比亚克瓦查 (1968–2012)", 2, 100L, new BigDecimal("0.01"), "ZMK" ),
            new IsoCurrencyInfo("ZMW", "967", "Zambian Kwacha", "赞比亚克瓦查", 2, 100L, new BigDecimal("0.01"), "ZMW" ),
            new IsoCurrencyInfo("ZWD", "716", "Zimbabwean Dollar (1980–2008)", "津巴布韦元 (1980–2008)", 2, 100L, new BigDecimal("0.01"), "ZWD" ),
            new IsoCurrencyInfo("ZWG", "924", "Zimbabwean Gold", "ZWG", 2, 100L, new BigDecimal("0.01"), "ZWG" ),
            new IsoCurrencyInfo("ZWL", "932", "Zimbabwean Dollar (2009–2024)", "津巴布韦元 (2009)", 2, 100L, new BigDecimal("0.01"), "ZWL" ),
            new IsoCurrencyInfo("ZWN", "942", "ZWN", "ZWN", 2, 100L, new BigDecimal("0.01"), "ZWN" ),
            new IsoCurrencyInfo("ZWR", "935", "Zimbabwean Dollar (2008)", "津巴布韦元 (2008)", 2, 100L, new BigDecimal("0.01"), "ZWR" )
    );

    /**
     * 工具类不允许实例化。
     */
    private IsoStandardData() {
    }
}
