SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS risk_config_change_log (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    module_type VARCHAR(32) NOT NULL COMMENT '模块类型：AML、BLACK、WHITE、RULE、TRADE_BLACK',
    function_code VARCHAR(64) NOT NULL COMMENT '功能编码，对应管理端风险功能定义',
    business_id BIGINT NULL COMMENT '业务记录ID',
    operation_type VARCHAR(32) NOT NULL COMMENT '操作类型：CREATE、UPDATE、DELETE、STATUS、IMPORT、BATCH',
    before_snapshot JSON NULL COMMENT '变更前快照，敏感字段必须脱敏',
    after_snapshot JSON NULL COMMENT '变更后快照，敏感字段必须脱敏',
    operator VARCHAR(64) NULL COMMENT '操作人',
    operation_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '操作时间',
    remark VARCHAR(500) NULL COMMENT '备注',
    PRIMARY KEY (id),
    KEY idx_risk_change_function_time (module_type, function_code, operation_time),
    KEY idx_risk_change_business (module_type, function_code, business_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='风控配置变更日志表';

CREATE TABLE IF NOT EXISTS risk_cache_invalidation_outbox (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    event_id VARCHAR(64) NOT NULL COMMENT '失效事件唯一编号',
    namespace VARCHAR(64) NOT NULL COMMENT '缓存代际命名空间',
    publication_token VARCHAR(128) NOT NULL COMMENT 'Redis 发布门禁持有者 token',
    generation VARCHAR(128) NOT NULL COMMENT '待切换的新缓存代际',
    event_status VARCHAR(16) NOT NULL DEFAULT 'INIT' COMMENT '状态：INIT、FAILED、SENT',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '已重试次数',
    next_retry_time DATETIME(3) NULL COMMENT '下次重试时间',
    published_time DATETIME(3) NULL COMMENT '发布成功时间',
    failure_reason VARCHAR(512) NULL COMMENT '最近一次失败原因摘要',
    version INT NOT NULL DEFAULT 0 COMMENT 'CAS 版本号',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_risk_cache_invalidation_event (event_id),
    KEY idx_risk_cache_invalidation_due (event_status, next_retry_time, create_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='风控规则缓存失效事件表';

CREATE TABLE IF NOT EXISTS risk_import_batch (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    module_type VARCHAR(32) NOT NULL COMMENT '模块类型：AML、BLACK、WHITE、RULE',
    function_code VARCHAR(64) NOT NULL COMMENT '功能编码',
    batch_no VARCHAR(64) NOT NULL COMMENT '导入批次号',
    file_name VARCHAR(255) NULL COMMENT '导入文件名',
    total_count INT NOT NULL DEFAULT 0 COMMENT '总条数',
    success_count INT NOT NULL DEFAULT 0 COMMENT '成功条数',
    failed_count INT NOT NULL DEFAULT 0 COMMENT '失败条数',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0处理中，1成功，2部分成功，3失败',
    operator VARCHAR(64) NULL COMMENT '操作人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    remark VARCHAR(500) NULL COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_risk_import_batch_no (batch_no),
    KEY idx_risk_import_function_time (module_type, function_code, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='风控名单导入批次表';

CREATE TABLE IF NOT EXISTS risk_import_error (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    batch_no VARCHAR(64) NOT NULL COMMENT '导入批次号',
    row_no INT NOT NULL COMMENT '文件行号',
    raw_content TEXT NULL COMMENT '原始行内容，敏感字段必须脱敏',
    error_message VARCHAR(1000) NOT NULL COMMENT '错误说明',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    PRIMARY KEY (id),
    KEY idx_risk_import_error_batch (batch_no, row_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='风控名单导入错误表';

CREATE TABLE IF NOT EXISTS risk_evaluation_record (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    risk_record_no VARCHAR(64) NOT NULL COMMENT '风控记录号',
    merchant_id VARCHAR(32) NULL COMMENT '商户号',
    merchant_name VARCHAR(128) NULL COMMENT '商户名称',
    merchant_order_no VARCHAR(64) NULL COMMENT '商户订单号',
    payment_order_no VARCHAR(64) NULL COMMENT '平台支付订单号',
    transaction_amount DECIMAL(18,6) NULL COMMENT '交易金额',
    transaction_currency VARCHAR(3) NULL COMMENT '交易币种，ISO 4217 Alpha-3',
    risk_level VARCHAR(32) NULL COMMENT '风险等级：LOW、MEDIUM、HIGH、CRITICAL',
    decision_result VARCHAR(32) NOT NULL DEFAULT 'REVIEW' COMMENT '决策结果：PASS、REJECT、REVIEW',
    decision_reason VARCHAR(500) NULL COMMENT '决策说明',
    hit_count INT NOT NULL DEFAULT 0 COMMENT '命中规则数量',
    evaluation_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '风控决策时间',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_risk_record_no (risk_record_no),
    KEY idx_risk_eval_merchant_time (merchant_id, evaluation_time),
    KEY idx_risk_eval_order (merchant_order_no, payment_order_no),
    KEY idx_risk_eval_payment_time (payment_order_no, evaluation_time, risk_record_no),
    KEY idx_risk_eval_result_time (decision_result, evaluation_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='风控评估记录表';

CREATE TABLE IF NOT EXISTS risk_evaluation_hit_detail (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    risk_record_no VARCHAR(64) NOT NULL COMMENT '风控记录号',
    module_type VARCHAR(32) NOT NULL COMMENT '命中模块类型：AML、BLACK、WHITE、RULE',
    function_code VARCHAR(64) NOT NULL COMMENT '命中功能编码',
    function_name VARCHAR(128) NULL COMMENT '命中功能名称',
    rule_id BIGINT NULL COMMENT '命中名单或规则ID',
    hit_element VARCHAR(64) NULL COMMENT '命中元素类型',
    hit_value_masked VARCHAR(255) NULL COMMENT '命中值脱敏展示',
    risk_level VARCHAR(32) NULL COMMENT '风险等级',
    decision_result VARCHAR(32) NOT NULL COMMENT '本项决策结果',
    decision_reason VARCHAR(500) NULL COMMENT '本项决策说明',
    decision_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '本项决策时间',
    time_window_seconds INT NULL COMMENT '频率规则统计窗口秒数',
    threshold_count INT NULL COMMENT '频率规则阈值次数',
    elements_json JSON NULL COMMENT '规则统计元素配置快照',
    current_count BIGINT NULL COMMENT '频率规则当前计数',
    stage_code VARCHAR(64) NULL COMMENT '风控执行阶段编码',
    stage_name VARCHAR(128) NULL COMMENT '风控执行阶段名称',
    stage_order INT NULL COMMENT '风控执行阶段顺序',
    match_result VARCHAR(32) NULL COMMENT '匹配结果：HIT、MISS、PASS、SKIPPED',
    decision_effect VARCHAR(32) NULL COMMENT '当前明细对最终决策的影响：ALLOW、BLOCK、REVIEW、CHALLENGE、NONE',
    PRIMARY KEY (id),
    KEY idx_risk_hit_record (risk_record_no),
    KEY idx_risk_hit_record_stage (risk_record_no, stage_order, id),
    KEY idx_risk_hit_function_time (module_type, function_code, decision_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='风控评估命中明细表';

CREATE TABLE IF NOT EXISTS risk_trade_black_record (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_id VARCHAR(32) NULL COMMENT '商户号',
    merchant_name VARCHAR(128) NULL COMMENT '商户名称',
    merchant_order_no VARCHAR(64) NULL COMMENT '商户订单号',
    payment_order_no VARCHAR(64) NULL COMMENT '平台支付订单号',
    black_target_type VARCHAR(64) NOT NULL COMMENT '加黑对象类型：CARD、CARD_FINGERPRINT、EMAIL、PHONE、IP、DEVICE、CUSTOMER',
    black_target_value_masked VARCHAR(255) NOT NULL COMMENT '加黑对象脱敏展示值',
    black_target_hash VARCHAR(128) NULL COMMENT '加黑对象哈希值，禁止保存完整敏感明文',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL、BATCH、SYSTEM',
    action_type VARCHAR(32) NOT NULL DEFAULT 'ADD' COMMENT '动作类型：ADD、RELEASE',
    action_reason VARCHAR(500) NULL COMMENT '操作原因',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0已解除，1已加黑',
    operator VARCHAR(64) NULL COMMENT '操作人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    KEY idx_trade_black_order (merchant_order_no, payment_order_no, deleted),
    KEY idx_trade_black_target (black_target_type, black_target_hash, status, deleted),
    KEY idx_trade_black_merchant_time (merchant_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='系统交易加黑记录表';

CREATE TABLE IF NOT EXISTS risk_aml_card (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '匹配值脱敏展示',
    match_value_hash VARCHAR(128) NULL COMMENT '匹配值哈希，卡号等敏感信息禁止保存明文',
    match_value_cipher VARCHAR(1024) NULL COMMENT '匹配值密文，仅编辑授权时解密回显',
    match_value_start VARCHAR(128) NULL COMMENT '区间起始值，用于BIN或IP等区间类场景',
    match_value_end VARCHAR(128) NULL COMMENT '区间结束值，用于BIN或IP等区间类场景',
    match_value_start_number DECIMAL(39,0) NULL COMMENT '区间起始数值，BIN和IP交易检索使用',
    match_value_end_number DECIMAL(39,0) NULL COMMENT '区间结束数值，BIN和IP交易检索使用',
    card_brand VARCHAR(64) NULL COMMENT '卡品牌，复用 card_brand 字典',
    country_alpha2 VARCHAR(2) NULL COMMENT '国家或地区 Alpha-2 编码',
    country_alpha3 VARCHAR(3) NULL COMMENT '国家或地区 Alpha-3 编码',
    country_numeric VARCHAR(3) NULL COMMENT '国家或地区数字编码',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'CRITICAL' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    KEY idx_risk_aml_card_hash (match_value_hash, status, deleted),
    KEY idx_risk_aml_card_merchant (merchant_scope, merchant_id, status, deleted),
    KEY idx_risk_aml_card_uniq_lookup (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_risk_aml_card_range_num (match_value_start_number, match_value_end_number, status, deleted),
    KEY idx_risk_aml_card_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='卡号卡指纹AML名单表';

CREATE TABLE IF NOT EXISTS risk_aml_card_bin LIKE risk_aml_card;
ALTER TABLE risk_aml_card_bin COMMENT = '卡BIN区间AML名单表';
CREATE TABLE IF NOT EXISTS risk_aml_ip (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(128) NOT NULL COMMENT 'IP地址或区间展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT 'IP区间归一化哈希，用于重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT 'IP地址默认不保存敏感密文',
    match_value_start VARCHAR(128) NOT NULL COMMENT '起始IP',
    match_value_end VARCHAR(128) NOT NULL COMMENT '截止IP',
    match_value_start_number DECIMAL(39,0) NOT NULL COMMENT '起始IP数值，交易检索使用',
    match_value_end_number DECIMAL(39,0) NOT NULL COMMENT '截止IP数值，交易检索使用',
    ip_version VARCHAR(8) NOT NULL COMMENT 'IP版本：IPV4、IPV6',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'CRITICAL' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_aml_ip_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_aml_ip_trade_lookup (ip_version, match_value_start_number, match_value_end_number, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_aml_ip_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_aml_ip_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='IP地址区间AML名单表';
CREATE TABLE IF NOT EXISTS risk_aml_country LIKE risk_aml_card;
ALTER TABLE risk_aml_country COMMENT = '国家地区AML名单表';
CREATE TABLE IF NOT EXISTS risk_aml_email (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '邮箱地址或域名展示值，邮箱地址需脱敏展示',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '邮箱地址或域名归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT '邮箱地址密文，域名类记录为空',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'CRITICAL' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_aml_email_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_aml_email_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_aml_email_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_aml_email_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='邮箱域名AML名单表';
CREATE TABLE IF NOT EXISTS risk_aml_phone LIKE risk_aml_card;
ALTER TABLE risk_aml_phone COMMENT = '手机号AML名单表';
CREATE TABLE IF NOT EXISTS risk_aml_cardholder_name LIKE risk_aml_card;
ALTER TABLE risk_aml_cardholder_name COMMENT = '持卡人姓名AML名单表';
CREATE TABLE IF NOT EXISTS risk_aml_legal_person (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '法人名称脱敏展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '法人名称归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT '法人名称密文，仅编辑授权时解密回显',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'CRITICAL' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_aml_legal_person_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_aml_legal_person_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_aml_legal_person_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_aml_legal_person_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AML法人名单表';
CREATE TABLE IF NOT EXISTS risk_aml_enterprise (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '企业名称脱敏展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '企业名称归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT '企业名称密文，仅编辑授权时解密回显',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'CRITICAL' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_aml_enterprise_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_aml_enterprise_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_aml_enterprise_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_aml_enterprise_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AML企业名单表';
CREATE TABLE IF NOT EXISTS risk_aml_merchant_billing_address (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '商户账单地址明文展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '商户账单地址归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT '商户账单地址默认不加密存储',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'CRITICAL' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_aml_merchant_billing_address_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_aml_merchant_billing_address_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_aml_merchant_billing_address_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_aml_merchant_billing_address_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AML商户账单地址名单表';
CREATE TABLE IF NOT EXISTS risk_aml_source_url LIKE risk_aml_card;
ALTER TABLE risk_aml_source_url
    ADD COLUMN source_host VARCHAR(255) NULL COMMENT '来源网址Host，交易和商户进件按全局Host匹配' AFTER match_value_cipher,
    ADD UNIQUE KEY uk_aml_source_url_host_deleted (source_host, deleted),
    ADD KEY idx_aml_source_url_host_lookup (source_host, status, deleted, effective_time, expire_time),
    COMMENT = '来源网址AML名单表';

CREATE TABLE IF NOT EXISTS risk_black_card_no (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '卡号脱敏展示值，禁止保存完整卡号明文',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '卡号归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT '卡号密文，仅编辑授权时解密回显',
    card_brand VARCHAR(64) NULL COMMENT '卡品牌，复用 card_brand 字典',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'HIGH' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_black_card_no_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_black_card_no_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_black_card_no_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_black_card_no_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='卡号黑名单表';

CREATE TABLE IF NOT EXISTS risk_black_card_fingerprint (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '卡指纹脱敏展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '卡指纹归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT '卡指纹密文，仅编辑授权时解密回显',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'HIGH' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_black_card_fingerprint_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_black_card_fingerprint_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_black_card_fingerprint_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_black_card_fingerprint_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='卡指纹黑名单表';

CREATE TABLE IF NOT EXISTS risk_black_card_bin (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '卡BIN区间展示值，保存为补齐后的起止值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT 'BIN区间归一化哈希，用于重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT 'BIN区间默认不保存敏感密文',
    match_value_start VARCHAR(11) NULL COMMENT '起始BIN，录入不足11位时右补0',
    match_value_end VARCHAR(11) NULL COMMENT '截止BIN，录入不足11位时右补9',
    match_value_start_number DECIMAL(39,0) NULL COMMENT '起始BIN数值，交易卡号区间检索使用',
    match_value_end_number DECIMAL(39,0) NULL COMMENT '截止BIN数值，交易卡号区间检索使用',
    card_brand VARCHAR(64) NULL COMMENT '卡品牌，后端根据起始BIN自动识别',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'HIGH' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_black_card_bin_scope_range_deleted (merchant_scope, merchant_id, match_value_start_number, match_value_end_number, deleted),
    KEY idx_black_card_bin_bin_lookup (status, deleted, merchant_scope, merchant_id, match_value_start_number, match_value_end_number, effective_time, expire_time),
    KEY idx_black_card_bin_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_black_card_bin_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='卡BIN区间黑名单表';

CREATE TABLE IF NOT EXISTS risk_black_cardholder_name (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '持卡人姓名脱敏展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '持卡人姓名归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT '持卡人姓名密文，仅编辑授权时解密回显',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'HIGH' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_black_cardholder_name_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_black_cardholder_name_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_black_cardholder_name_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_black_cardholder_name_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='持卡人姓名黑名单表';
CREATE TABLE IF NOT EXISTS risk_black_phone (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(64) NOT NULL COMMENT '电话号码展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '电话号码归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(512) NULL COMMENT '电话号码密文，仅编辑授权时解密回显',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'HIGH' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_black_phone_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_black_phone_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_black_phone_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_black_phone_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='电话号码黑名单表';
CREATE TABLE IF NOT EXISTS risk_black_ip (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(128) NOT NULL COMMENT 'IP地址或区间展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT 'IP区间归一化哈希，用于重复校验',
    match_value_cipher VARCHAR(512) NULL COMMENT 'IP地址或区间密文，仅编辑授权时解密回显',
    match_value_start VARCHAR(128) NOT NULL COMMENT 'IP起始值',
    match_value_end VARCHAR(128) NOT NULL COMMENT 'IP截止值',
    match_value_start_number DECIMAL(39,0) NOT NULL COMMENT 'IP起始数值，交易区间检索使用',
    match_value_end_number DECIMAL(39,0) NOT NULL COMMENT 'IP截止数值，交易区间检索使用',
    ip_version VARCHAR(8) NOT NULL COMMENT 'IP版本：IPV4、IPV6',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'HIGH' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_black_ip_scope_range_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_black_ip_trade_lookup (ip_version, match_value_start_number, match_value_end_number, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_black_ip_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_black_ip_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='IP地址区间黑名单表';
CREATE TABLE IF NOT EXISTS risk_black_email (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '邮箱地址脱敏展示值，禁止保存完整邮箱明文',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '邮箱地址归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NOT NULL COMMENT '邮箱地址密文，仅编辑授权时解密回显',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'HIGH' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_black_email_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_black_email_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_black_email_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_black_email_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='邮箱地址黑名单表';
CREATE TABLE IF NOT EXISTS risk_black_email_username (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '邮箱用户名脱敏展示值，禁止保存完整明文',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '邮箱用户名归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NOT NULL COMMENT '邮箱用户名密文，仅编辑授权时解密回显',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'HIGH' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_black_email_username_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_black_email_username_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_black_email_username_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_black_email_username_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='邮箱用户名黑名单表';
CREATE TABLE IF NOT EXISTS risk_black_email_domain (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '邮箱域名展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '邮箱域名归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT '邮箱域名不属于敏感明文，默认不加密存储',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'HIGH' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_black_email_domain_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_black_email_domain_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_black_email_domain_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_black_email_domain_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='邮箱域名黑名单表';
CREATE TABLE IF NOT EXISTS risk_black_billing_address (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '账单地址明文展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '账单地址归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT '账单地址明文展示，默认不加密存储',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'HIGH' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_black_billing_address_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_black_billing_address_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_black_billing_address_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_black_billing_address_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='账单地址黑名单表';
CREATE TABLE IF NOT EXISTS risk_black_billing_zip (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(32) NOT NULL COMMENT '账单邮编展示值，按大写和单空格规范化',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '账单邮编检索哈希，按去除空格和短横线后的值生成',
    match_value_cipher VARCHAR(1024) NULL COMMENT '预留密文字段，账单邮编默认不加密存储',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'HIGH' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_black_billing_zip_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_black_billing_zip_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_black_billing_zip_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_black_billing_zip_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='账单邮编黑名单表';
CREATE TABLE IF NOT EXISTS risk_black_billing_country (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(3) NOT NULL COMMENT '国家或地区 Alpha-3 编码展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '国家或地区 Alpha-3 编码哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT '预留密文字段，国家或地区默认不加密存储',
    country_alpha2 VARCHAR(2) NULL COMMENT '国家或地区 Alpha-2 编码，仅用于管理端回显',
    country_alpha3 VARCHAR(3) NOT NULL COMMENT '国家或地区 Alpha-3 编码，交易匹配主字段',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'HIGH' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_black_billing_country_scope_country_deleted (merchant_scope, merchant_id, country_alpha3, deleted),
    KEY idx_black_billing_country_trade_lookup (country_alpha3, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_black_billing_country_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_black_billing_country_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='账单国家地区黑名单表';
CREATE TABLE IF NOT EXISTS risk_black_shipping_address LIKE risk_black_billing_address;
ALTER TABLE risk_black_shipping_address COMMENT = '收货地址黑名单表';
CREATE TABLE IF NOT EXISTS risk_black_shipping_zip LIKE risk_black_billing_zip;
ALTER TABLE risk_black_shipping_zip COMMENT = '收货邮编黑名单表';
CREATE TABLE IF NOT EXISTS risk_black_shipping_country LIKE risk_black_billing_country;
ALTER TABLE risk_black_shipping_country COMMENT = '收货国家地区黑名单表';
CREATE TABLE IF NOT EXISTS risk_black_issuer_country LIKE risk_black_billing_country;
ALTER TABLE risk_black_issuer_country COMMENT = '发卡行国家地区黑名单表';
CREATE TABLE IF NOT EXISTS risk_black_device_fingerprint (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '设备指纹脱敏展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '设备指纹归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT '设备指纹密文，仅编辑授权时解密回显',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'HIGH' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_black_device_fingerprint_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_black_device_fingerprint_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_black_device_fingerprint_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_black_device_fingerprint_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设备指纹黑名单表';

CREATE TABLE IF NOT EXISTS risk_black_region (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NULL COMMENT '商户号，仅商户范围生效时必填',
    region_match_level VARCHAR(32) NOT NULL COMMENT '区域匹配级别：COUNTRY国家、STATE州省、CITY城市',
    country_alpha3 VARCHAR(3) NOT NULL COMMENT '国家或地区 Alpha-3 编码',
    state_province_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT '州省名称',
    city_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT '城市名称',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'HIGH' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    KEY idx_black_region_level (region_match_level, status, deleted),
    UNIQUE KEY uk_black_region_scope_area (merchant_scope, merchant_id, region_match_level, country_alpha3, state_province_name, city_name, deleted),
    KEY idx_black_region_trade_lookup (merchant_scope, merchant_id, region_match_level, country_alpha3, state_province_name, city_name, status, deleted, effective_time, expire_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='高风险区域黑名单表';

CREATE TABLE IF NOT EXISTS risk_white_merchant (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'MERCHANT' COMMENT '固定为MERCHANT，商户白名单仅对商户自身生效',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '白名单商户号，与商户号展示值保持一致',
    match_value_masked VARCHAR(32) NOT NULL COMMENT '白名单商户号展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '白名单商户号哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT '商户白名单不保存敏感密文',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'LOW' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'PASS' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_white_merchant_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_white_merchant_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_white_merchant_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_white_merchant_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商户白名单表';
CREATE TABLE IF NOT EXISTS risk_white_card_no (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(32) NOT NULL COMMENT '卡号脱敏展示值，禁止保存完整卡号明文',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '卡号归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NOT NULL COMMENT '卡号密文，仅编辑授权时解密回显',
    card_brand VARCHAR(64) NULL COMMENT '卡品牌，后端根据卡号自动识别',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'LOW' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'PASS' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_white_card_no_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_white_card_no_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_white_card_no_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_white_card_no_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='卡号白名单表';
CREATE TABLE IF NOT EXISTS risk_white_card_fingerprint (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '卡指纹脱敏展示值，禁止保存完整明文',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '卡指纹归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NOT NULL COMMENT '卡指纹密文，仅编辑授权时解密回显',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'LOW' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'PASS' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_white_card_fingerprint_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_white_card_fingerprint_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_white_card_fingerprint_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_white_card_fingerprint_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='卡指纹白名单表';
CREATE TABLE IF NOT EXISTS risk_white_card_bin (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '卡BIN区间展示值，保存为补齐后的起止值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT 'BIN区间归一化哈希，用于重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT 'BIN区间默认不保存敏感密文',
    match_value_start VARCHAR(11) NULL COMMENT '起始BIN，录入不足11位时右补0',
    match_value_end VARCHAR(11) NULL COMMENT '截止BIN，录入不足11位时右补9',
    match_value_start_number DECIMAL(39,0) NULL COMMENT '起始BIN数值，交易卡号区间检索使用',
    match_value_end_number DECIMAL(39,0) NULL COMMENT '截止BIN数值，交易卡号区间检索使用',
    card_brand VARCHAR(64) NULL COMMENT '卡品牌，后端根据起始BIN自动识别',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'LOW' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'PASS' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_white_card_bin_scope_range_deleted (merchant_scope, merchant_id, match_value_start_number, match_value_end_number, deleted),
    KEY idx_white_card_bin_bin_lookup (status, deleted, merchant_scope, merchant_id, match_value_start_number, match_value_end_number, effective_time, expire_time),
    KEY idx_white_card_bin_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_white_card_bin_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='卡BIN区间白名单表';
CREATE TABLE IF NOT EXISTS risk_white_ip (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(128) NOT NULL COMMENT 'IP地址展示值，白名单仅支持单IP',
    match_value_hash VARCHAR(128) NOT NULL COMMENT 'IP地址归一化哈希，用于重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT 'IP地址默认不保存敏感密文',
    match_value_start VARCHAR(128) NOT NULL COMMENT 'IP地址值',
    match_value_end VARCHAR(128) NOT NULL COMMENT 'IP地址值，白名单与起始值一致',
    match_value_start_number DECIMAL(39,0) NOT NULL COMMENT 'IP数值，交易检索使用',
    match_value_end_number DECIMAL(39,0) NOT NULL COMMENT 'IP数值，白名单与起始数值一致',
    ip_version VARCHAR(8) NOT NULL COMMENT 'IP版本：IPV4、IPV6',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'LOW' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'PASS' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_white_ip_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_white_ip_trade_lookup (ip_version, match_value_start_number, match_value_end_number, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_white_ip_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_white_ip_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='IP地址白名单表';
CREATE TABLE IF NOT EXISTS risk_white_trade_country (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(3) NOT NULL COMMENT '国家或地区 Alpha-3 编码展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '国家或地区 Alpha-3 编码哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT '预留密文字段，国家或地区默认不加密存储',
    country_alpha2 VARCHAR(2) NULL COMMENT '国家或地区 Alpha-2 编码，仅用于管理端回显',
    country_alpha3 VARCHAR(3) NOT NULL COMMENT '国家或地区 Alpha-3 编码，交易匹配主字段',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'LOW' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'PASS' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_white_trade_country_scope_country_deleted (merchant_scope, merchant_id, country_alpha3, deleted),
    KEY idx_white_trade_country_trade_lookup (country_alpha3, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_white_trade_country_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_white_trade_country_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='交易国家地区白名单表';
CREATE TABLE IF NOT EXISTS risk_white_issuer_country (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(3) NOT NULL COMMENT '国家或地区 Alpha-3 编码展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '国家或地区 Alpha-3 编码哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT '预留密文字段，国家或地区默认不加密存储',
    country_alpha2 VARCHAR(2) NULL COMMENT '国家或地区 Alpha-2 编码，仅用于管理端回显',
    country_alpha3 VARCHAR(3) NOT NULL COMMENT '国家或地区 Alpha-3 编码，交易匹配主字段',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'LOW' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'PASS' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_white_issuer_country_scope_country_deleted (merchant_scope, merchant_id, country_alpha3, deleted),
    KEY idx_white_issuer_country_trade_lookup (country_alpha3, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_white_issuer_country_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_white_issuer_country_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='发卡行国家地区白名单表';
CREATE TABLE IF NOT EXISTS risk_white_email (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '邮箱地址脱敏展示值，禁止保存完整邮箱明文',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '邮箱地址归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NOT NULL COMMENT '邮箱地址密文，仅编辑授权时解密回显',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'LOW' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'PASS' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_white_email_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_white_email_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_white_email_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_white_email_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='邮箱地址白名单表';
CREATE TABLE IF NOT EXISTS risk_white_email_domain (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '邮箱域名展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '邮箱域名归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NULL COMMENT '邮箱域名不属于敏感明文，默认不加密存储',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'LOW' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'PASS' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_white_email_domain_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_white_email_domain_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_white_email_domain_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_white_email_domain_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='邮箱域名白名单表';
CREATE TABLE IF NOT EXISTS risk_white_phone (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(64) NOT NULL COMMENT '手机号展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '手机号归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NOT NULL COMMENT '手机号密文，仅编辑授权时解密回显',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'LOW' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'PASS' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_white_phone_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_white_phone_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_white_phone_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_white_phone_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='手机号白名单表';
CREATE TABLE IF NOT EXISTS risk_white_customer_id (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT 'Customer ID 脱敏展示值',
    match_value_hash VARCHAR(128) NOT NULL COMMENT 'Customer ID 归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NOT NULL COMMENT 'Customer ID 密文，仅编辑授权时解密回显',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'LOW' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'PASS' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_white_customer_id_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_white_customer_id_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_white_customer_id_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_white_customer_id_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Customer ID白名单表';
CREATE TABLE IF NOT EXISTS risk_white_device_fingerprint (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    match_value_masked VARCHAR(255) NOT NULL COMMENT '设备指纹脱敏展示值，禁止保存完整明文',
    match_value_hash VARCHAR(128) NOT NULL COMMENT '设备指纹归一化哈希，用于交易检索和重复校验',
    match_value_cipher VARCHAR(1024) NOT NULL COMMENT '设备指纹密文，仅编辑授权时解密回显',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'LOW' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'PASS' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    validity_type VARCHAR(32) NOT NULL DEFAULT 'SUPER_LONG' COMMENT '有效期类型：SUPER_LONG超长期、LONG长期、LIMITED限定有效期',
    validity_days INT NULL COMMENT '有效天数，长期和限定有效期使用',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型：MANUAL手工、IMPORT导入、SYSTEM系统',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_white_device_fingerprint_scope_hash_deleted (merchant_scope, merchant_id, match_value_hash, deleted),
    KEY idx_white_device_fingerprint_trade_lookup (match_value_hash, merchant_scope, merchant_id, status, deleted, effective_time, expire_time),
    KEY idx_white_device_fingerprint_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_white_device_fingerprint_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设备指纹白名单表';

CREATE TABLE IF NOT EXISTS risk_rule_source_url (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_id VARCHAR(32) NOT NULL COMMENT '商户号，来源网址限定按商户直接生效',
    source_url VARCHAR(512) NOT NULL COMMENT '商户录入来源网址，必须以http://或https://开头',
    source_host VARCHAR(255) NOT NULL COMMENT '来源网址Host，交易链路按商户号和Host匹配',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'MEDIUM' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REVIEW' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_rule_source_url_merchant_host_deleted (merchant_id, source_host, deleted),
    KEY idx_rule_source_url_trade_lookup (merchant_id, source_host, status, deleted, effective_time, expire_time),
    KEY idx_rule_source_url_merchant_time (merchant_id, update_time, id),
    KEY idx_rule_source_url_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商户来源网址限定表';

CREATE TABLE IF NOT EXISTS risk_rule_template (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NULL COMMENT '商户号，仅商户范围生效时必填',
    rule_name VARCHAR(128) NOT NULL COMMENT '规则名称',
    match_mode VARCHAR(32) NULL COMMENT '匹配方式：EXACT、DOMAIN、CONTAINS、REGEX',
    match_value VARCHAR(512) NULL COMMENT '匹配值，URL类规则不得写入卡号等敏感数据',
    limit_type VARCHAR(64) NULL COMMENT '限额类型，复用 channel_limit_type 或风险字典',
    amount_min DECIMAL(18,6) NULL COMMENT '最小金额',
    amount_max DECIMAL(18,6) NULL COMMENT '最大金额',
    currency VARCHAR(3) NULL COMMENT '币种，ISO 4217 Alpha-3',
    time_window_seconds INT NULL COMMENT '时间窗口秒数',
    threshold_count INT NULL COMMENT '阈值次数',
    elements_json JSON NULL COMMENT '限定元素或组合元素JSON',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'MEDIUM' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REVIEW' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    KEY idx_risk_rule_scope (merchant_scope, merchant_id, status, deleted),
    KEY idx_risk_rule_time (create_time),
    KEY idx_risk_rule_currency (currency, status, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='内风控通用规则模板表';

CREATE TABLE IF NOT EXISTS risk_rule_merchant_limit (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号，仅商户范围生效时必填；全局范围为空字符串',
    rule_name VARCHAR(128) NOT NULL COMMENT '规则名称',
    match_value VARCHAR(512) NOT NULL DEFAULT '' COMMENT '限额场景，可为空字符串；用于区分同一商户下不同交易场景',
    limit_type VARCHAR(64) NOT NULL COMMENT '限额类型：SINGLE_MIN、SINGLE_MAX、DAILY、WEEKLY、MONTHLY',
    amount_min DECIMAL(18,2) NULL COMMENT '最小金额，单笔最低限额使用，固定USD且保留2位小数',
    amount_max DECIMAL(18,2) NULL COMMENT '最大金额，单笔最高、日、周、月限额使用，固定USD且保留2位小数',
    currency VARCHAR(3) NOT NULL DEFAULT 'USD' COMMENT '限额币种，当前固定USD',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'HIGH' COMMENT '风险等级',
    decision_action VARCHAR(32) NOT NULL DEFAULT 'REJECT' COMMENT '命中动作：REJECT、REVIEW、PASS',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_rule_merchant_limit_scope_type_scene_deleted (merchant_scope, merchant_id, match_value, limit_type, deleted),
    KEY idx_rule_merchant_limit_trade_lookup (merchant_scope, merchant_id, match_value, limit_type, status, deleted, effective_time, expire_time),
    KEY idx_rule_merchant_limit_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_rule_merchant_limit_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商户交易限额规则表';
CREATE TABLE IF NOT EXISTS risk_rule_frequency LIKE risk_rule_template;
ALTER TABLE risk_rule_frequency COMMENT = '交易频率限定规则表';
CREATE TABLE IF NOT EXISTS risk_rule_3ds (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    rule_group_no VARCHAR(64) NOT NULL COMMENT '规则组编号',
    merchant_scope VARCHAR(32) NOT NULL DEFAULT 'GLOBAL' COMMENT '生效范围：GLOBAL全局、MERCHANT商户',
    merchant_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT '商户号；全局范围为空字符串',
    merchant_name VARCHAR(128) NULL COMMENT '商户名称，管理端展示辅助快照',
    rule_name VARCHAR(128) NOT NULL COMMENT '规则名称',
    rule_type VARCHAR(32) NOT NULL DEFAULT 'RISK_STRATEGY' COMMENT '规则类型：RISK_STRATEGY风险策略、EXEMPTION_STRATEGY豁免策略、CHANNEL_POLICY渠道策略',
    channel_code VARCHAR(64) NOT NULL DEFAULT 'ALL' COMMENT '收单渠道编码，ALL表示全部渠道',
    payment_method VARCHAR(64) NOT NULL DEFAULT 'ALL' COMMENT '支付方式，ALL表示全部支付方式',
    card_brand VARCHAR(64) NOT NULL DEFAULT 'ALL' COMMENT '卡品牌，ALL表示全部卡品牌',
    amount_match_type VARCHAR(32) NOT NULL DEFAULT 'ALL' COMMENT '金额匹配类型：ALL、GE、LE、BETWEEN',
    amount_min DECIMAL(18,2) NULL COMMENT '最小交易金额，固定USD且保留2位小数',
    amount_max DECIMAL(18,2) NULL COMMENT '最大交易金额，固定USD且保留2位小数',
    currency VARCHAR(3) NOT NULL DEFAULT 'USD' COMMENT '交易币种，当前固定USD',
    risk_condition VARCHAR(32) NOT NULL DEFAULT 'ANY' COMMENT '风险条件：ANY、LOW_AND_ABOVE、MEDIUM_AND_ABOVE、HIGH_AND_ABOVE、CRITICAL_ONLY',
    trigger_action VARCHAR(32) NOT NULL DEFAULT 'FORCE_3DS' COMMENT '触发动作：FORCE_3DS、SKIP_3DS、FOLLOW_DEFAULT',
    priority INT NOT NULL DEFAULT 100 COMMENT '优先级，数字越小越优先',
    effective_time DATETIME(3) NULL COMMENT '生效时间',
    expire_time DATETIME(3) NULL COMMENT '失效时间',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0停用，1启用',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_by VARCHAR(64) NULL COMMENT '创建人',
    update_by VARCHAR(64) NULL COMMENT '更新人',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted BIGINT NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，大于0为删除记录ID',
    PRIMARY KEY (id),
    UNIQUE KEY uk_rule_3ds_dimension_deleted (merchant_scope, merchant_id, channel_code, payment_method, card_brand, amount_match_type, amount_min, amount_max, currency, risk_condition, trigger_action, deleted),
    KEY idx_rule_3ds_trade_lookup (deleted, status, merchant_scope, merchant_id, channel_code, payment_method, card_brand, currency, priority, effective_time, expire_time),
    KEY idx_rule_3ds_merchant_time (merchant_scope, merchant_id, update_time, id),
    KEY idx_rule_3ds_time (update_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='3DS规则管理表';

SET FOREIGN_KEY_CHECKS = 1;
