spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
      config:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        file-extension: yml
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}

rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:127.0.0.1:9876}

xxl:
  job:
    admin:
      addresses: ${XXL_JOB_ADMIN:http://127.0.0.1:8088/xxl-job-admin}

seata:
  enabled: false
  tx-service-group: ${SEATA_TX_GROUP:global-payment-dev}

logging:
  config: classpath:log-config/logback-spring.xml

