<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.scott.payment</groupId>
        <artifactId>acquiring-orchestration</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>component-library</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>component-core</module>
        <module>component-excel</module>
        <module>component-web</module>
        <module>component-security</module>
        <module>component-http</module>
        <module>component-db</module>
        <module>component-redis</module>
        <module>component-mq</module>
        <module>component-job</module>
    </modules>
</project>
